---
title: "Parsing Real"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, include = FALSE, eval = FALSE}
setwd("Paper/Data/Bootstrap/")
states <- 12
list_of_names <- list.files()
reps <- length(list_of_names)
getwd()

init_init_array <- array(0,dim = c(1,states,reps))
tran_init_array <- array(0,dim = c(states,states,reps))
class_init_array <- array(0,dim = c(states,states,reps))

init_est_array <- array(0,dim = c(1,states,reps))
tran_est_array <- array(0,dim = c(states,states,reps))
class_est_array <- array(0,dim = c(states,states,reps))

likelihood_array <- numeric(reps)
pi_init_array <- numeric(reps)
pi_est_array <- numeric(reps)
time_array <- numeric(reps)

init_init_list <- vector("list", length = reps)
tran_init_list <- vector("list", length = reps)
class_init_list <- vector("list", length = reps)

init_est_list <- vector("list", length = reps)
tran_est_list <- vector("list", length = reps)
class_est_list <- vector("list", length = reps)

count <- 1

for (name in list_of_names){
  load(name)
  
  init_parameters <- to_save[[1]]
  est_parameters <- to_save[[2]]
  likelihood_array[count] <- to_save[[3]]
  # time_array[count] <- to_save[[4]] / (60 * 60 * 24)
  
  pi_init_array[count] <- init_parameters[[4]]
  pi_est_array[count] <- est_parameters[[4]]
  
  init_init_list[[count]] <- init_parameters[[1]]
  tran_init_list[[count]] <- init_parameters[[2]]
  class_init_list[[count]] <- init_parameters[[3]]
  
  init_est_list[[count]] <- est_parameters[[1]]
  tran_est_list[[count]] <- est_parameters[[2]]
  class_est_list[[count]] <- est_parameters[[3]]
  
  
  
  
  for (i in 1:states){
    init_init_array[1,i,count] <- init_init_list[[count]][i]
    init_est_array[1,i,count] <- init_est_list[[count]][i]
    
    for (j in 1:states){
      tran_init_array[i,j,count] <- tran_init_list[[count]][i,j]
      tran_est_array[i,j,count] <- tran_est_list[[count]][i,j]
      
      class_init_array[i,j,count] <- class_init_list[[count]][i,j]
      class_est_array[i,j,count] <- class_est_list[[count]][i,j]
    }
  }
  
  count <- count + 1
}


#############################################



```

```{r}
variance <- F
if (variance == T){
  init_var <- numeric(states)
  tran_var <- matrix(0,states,states)
  class_var <- matrix(0,states,states)
  
  for (i in 1:states){
    init_var[i] <- var(init_est_array[1,i,])
    for (j in 1:states){
      tran_var[i,j] <- var(tran_est_array[i,j,])
      class_var[i,j] <- var(class_est_array[i,j,])
      
    }
  }
}
```

```{r, echo = FALSE, fig.width=15, fig.height=15}
ClassificationHeatmap <- function(X_tran, state_labels = c(0:11), adj_labels){
  library(reshape)
  library(ggplot2)
  rownames(X_tran) <- c(state_labels)
  colnames(X_tran) <- c(state_labels)
  X_tran.m <- melt(X_tran)
  X_tran.m$X1 <- factor(X_tran.m$X1, levels = rev(adj_labels))
  X_tran.m$X2 <- factor(X_tran.m$X2, levels = (adj_labels))
  ggplot(X_tran.m,aes(X2, X1)) + 
    geom_tile(aes(fill = value),color = "white") + 
    scale_fill_gradient2(low = "blue",high = "red") +
    labs(x = "New State", y = "Initial State", caption = "Observed - True") + 
    theme(axis.text.y = element_text(size = 10), axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5)) + 
    theme(axis.text.x = element_text(angle = 0)) + 
    theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))) + 
    theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0))) +
    theme(plot.caption = element_text(hjust = .5))
}
```

```{r}
GenerateInitTable <- function(init, init_var, title){
  library(knitr)
  library(kableExtra)
  combined_mat <- rbind(init, init_var)
  rownames(combined_mat) <- c("Estimate", "Std Dev")
  colnames(combined_mat) <- c(0:(length(init) -1))
  
  kable(combined_mat, caption = title) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = T) %>%
    group_rows("State 0",1,2) 
}
```

```{r}
GenerateTable <- function(mean_mat,var_mat,title){
  library(knitr)
  library(kableExtra)
  row_names <- c("Estimate", "Std Dev")
  
  length_of_ind <- dim(mean_mat)[1]
  combined_mat <- matrix(0,length_of_ind*2, length_of_ind)
  
  for (i in 1:(length_of_ind * 2)){
    which_one <- i %% 2
    true_ind <- ceiling(i/2)
    if (which_one == 1){
      combined_mat[i,] <- mean_mat[true_ind,]
    } else if (which_one == 0){
      combined_mat[i,] <- var_mat[true_ind,]
    } 
  }
  
  rownames(combined_mat) <- rep(row_names,length_of_ind)

  colnames(combined_mat) <- c(0:(length_of_ind -1))
  
  kable(combined_mat, caption = title) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = T) %>%
    group_rows("State 0",1,2) %>%
    group_rows("State 1",3,4) %>%
    group_rows("State 2",5,6) %>%
    group_rows("State 3",7,8) %>%
    group_rows("State 4",9,10) %>%
    group_rows("State 5",11,12) %>%
    group_rows("State 6",13,14) %>%
    group_rows("State 7",15,16) %>%
    group_rows("State 8",17,18) %>%
    group_rows("State 9",19,20) %>%
    group_rows("State 10",21,22) %>%
    group_rows("State 11",23,24) 
    
  
    
}
```

```{r}

state_labels <- c(0:11)


# first <- which.max(likelihood_array)
# 
# 
# est_init <- init_est_array[1,,first]
# est_tran <- tran_est_array[,,first]
# est_class <- class_est_array[,,first]
# est_pi <- pi_est_array[first]
# 
# init <- est_init
# tran <- est_tran
# class <- est_class
# pi_0 <- est_pi
# 
# parameters <- list(est_init, est_tran,est_class, est_pi)
load("parameters.rda")
est_init <- to_save[[2]][[1]]
est_tran <- to_save[[2]][[2]]
est_class <- to_save[[2]][[3]]
est_pi <- to_save[[2]][[4]]



ClassificationHeatmap(est_tran, state_labels, state_labels) + ggtitle("Transition")
# ClassificationHeatmap(est_tran2, state_labels, state_labels) + ggtitle("Transition")
# ClassificationHeatmap(tran_sd, state_labels, state_labels) + ggtitle("Transition SD")

ClassificationHeatmap(est_class, state_labels, state_labels) + ggtitle("Classification")
# ClassificationHeatmap(est_class2, state_labels, state_labels) + ggtitle("Classification")
# ClassificationHeatmap(class_sd, state_labels, state_labels) + ggtitle("Classification SD")

```

```{r}

# GenerateInitTable(est_init, est_init, "Initial (Median")
# 
# GenerateTable(est_tran, est_tran,"Transition (Median)")
# 
# GenerateTable(est_class, est_class,"Classification (Median)")

GenerateInitTable(est_init, sqrt(init_var), "Initial")

GenerateTable(est_tran, sqrt(tran_var),"Transition")

GenerateTable(est_class, sqrt(class_var),"Classification")
```


```{r}
library(kableExtra)

init_hpv_neg <- sum(est_init[c(1:4)])
init_hpv_pos1 <- sum(est_init[c(5:8)])
init_hpv_pos2 <- sum(est_init[c(9:12)])
init_hpv <- matrix(c(init_hpv_neg, init_hpv_pos1, init_hpv_pos2),1,3)
colnames(init_hpv) <- c("HPV -", "HPV + ", "HPV ++")
kable_styling(kable(init_hpv))

init_cyt_neg <- sum(est_init[c(1,2,5,6,9,10)])
init_cyt_pos <- 1 - init_cyt_neg
init_cyt <- matrix(c(init_cyt_neg,init_cyt_pos),1,2)
colnames(init_cyt) <- c("Cyt Negative", "Cyt Positive")
kable_styling(kable(init_cyt))

init_copa_neg <-  sum(est_init[c(1,3,5,7,9)])
init_copa_pos <- 1 - init_copa_neg
init_copa <- matrix(c(init_copa_neg, init_copa_pos),1,2)
colnames(init_copa) <- c("Copa Negative", "Copa Positive")
kable_styling(kable(init_copa))
```

```{r}
#Tran
neg_hpv <- c(1,2,3,4)
pos_hpv <- c(5,6,7,8)
pos_pos_hpv <- c(9,10,11,12)
hpv_marg <- matrix(0,3,3)
hpv_marg[1,1] <- sum(est_tran[neg_hpv,neg_hpv])
hpv_marg[1,2] <- sum(est_tran[neg_hpv,pos_hpv])
hpv_marg[1,3] <- sum(est_tran[neg_hpv,pos_pos_hpv])
hpv_marg[2,1] <- sum(est_tran[pos_hpv,neg_hpv])
hpv_marg[2,2] <- sum(est_tran[pos_hpv,pos_hpv])
hpv_marg[2,3] <- sum(est_tran[pos_hpv,pos_pos_hpv])
hpv_marg[3,1] <- sum(est_tran[pos_pos_hpv,neg_hpv])
hpv_marg[3,2] <- sum(est_tran[pos_pos_hpv,pos_hpv])
hpv_marg[3,3] <- sum(est_tran[pos_pos_hpv,pos_pos_hpv])
hpv_marg <- hpv_marg / rowSums(hpv_marg)
colnames(hpv_marg) <- c("HPV -", "HPV +", "HPV ++")
rownames(hpv_marg) <- c("HPV -", "HPV +", "HPV ++")
kable_styling(kable(hpv_marg))

neg_hpv_neg_cyt <- c(1,2)
pos_hpv_neg_cyt <- c(5,6)
pos_pos_hpv_neg_cyt <- c(9,10)
hpv_marg <- matrix(0,3,3)
hpv_marg[1,1] <- sum(est_tran[neg_hpv_neg_cyt,neg_hpv])
hpv_marg[1,2] <- sum(est_tran[neg_hpv_neg_cyt,pos_hpv])
hpv_marg[1,3] <- sum(est_tran[neg_hpv_neg_cyt,pos_pos_hpv])
hpv_marg[2,1] <- sum(est_tran[pos_hpv_neg_cyt,neg_hpv])
hpv_marg[2,2] <- sum(est_tran[pos_hpv_neg_cyt,pos_hpv])
hpv_marg[2,3] <- sum(est_tran[pos_hpv_neg_cyt,pos_pos_hpv])
hpv_marg[3,1] <- sum(est_tran[pos_pos_hpv_neg_cyt,neg_hpv])
hpv_marg[3,2] <- sum(est_tran[pos_pos_hpv_neg_cyt,pos_hpv])
hpv_marg[3,3] <- sum(est_tran[pos_pos_hpv_neg_cyt,pos_pos_hpv])
hpv_marg <- hpv_marg / rowSums(hpv_marg)
colnames(hpv_marg) <- c("HPV -", "HPV +", "HPV ++")
rownames(hpv_marg) <- c("HPV - Cyt Neg", "HPV + Cyt Neg", "HPV ++ Cyt Neg")
kable_styling(kable(hpv_marg))

neg_hpv_pos_cyt <- c(3,4)
pos_hpv_pos_cyt <- c(7,8)
pos_pos_hpv_pos_cyt <- c(11,12)
hpv_marg <- matrix(0,3,3)
hpv_marg[1,1] <- sum(est_tran[neg_hpv_pos_cyt,neg_hpv])
hpv_marg[1,2] <- sum(est_tran[neg_hpv_pos_cyt,pos_hpv])
hpv_marg[1,3] <- sum(est_tran[neg_hpv_pos_cyt,pos_pos_hpv])
hpv_marg[2,1] <- sum(est_tran[pos_hpv_pos_cyt,neg_hpv])
hpv_marg[2,2] <- sum(est_tran[pos_hpv_pos_cyt,pos_hpv])
hpv_marg[2,3] <- sum(est_tran[pos_hpv_pos_cyt,pos_pos_hpv])
hpv_marg[3,1] <- sum(est_tran[pos_pos_hpv_pos_cyt,neg_hpv])
hpv_marg[3,2] <- sum(est_tran[pos_pos_hpv_pos_cyt,pos_hpv])
hpv_marg[3,3] <- sum(est_tran[pos_pos_hpv_pos_cyt,pos_pos_hpv])
hpv_marg <- hpv_marg / rowSums(hpv_marg)
colnames(hpv_marg) <- c("HPV -", "HPV +", "HPV ++")
rownames(hpv_marg) <- c("HPV - Cyt Pos", "HPV + Cyt Pos", "HPV ++ Cyt Pos")
kable_styling(kable(hpv_marg))

neg_hpv_neg_hist <- c(1,3)
pos_hpv_neg_hist <- c(5,7)
pos_pos_hpv_neg_hist <- c(9,11)
hpv_marg <- matrix(0,3,3)
hpv_marg[1,1] <- sum(est_tran[neg_hpv_neg_hist,neg_hpv])
hpv_marg[1,2] <- sum(est_tran[neg_hpv_neg_hist,pos_hpv])
hpv_marg[1,3] <- sum(est_tran[neg_hpv_neg_hist,pos_pos_hpv])
hpv_marg[2,1] <- sum(est_tran[pos_hpv_neg_hist,neg_hpv])
hpv_marg[2,2] <- sum(est_tran[pos_hpv_neg_hist,pos_hpv])
hpv_marg[2,3] <- sum(est_tran[pos_hpv_neg_hist,pos_pos_hpv])
hpv_marg[3,1] <- sum(est_tran[pos_pos_hpv_neg_hist,neg_hpv])
hpv_marg[3,2] <- sum(est_tran[pos_pos_hpv_neg_hist,pos_hpv])
hpv_marg[3,3] <- sum(est_tran[pos_pos_hpv_neg_hist,pos_pos_hpv])
hpv_marg <- hpv_marg / rowSums(hpv_marg)
colnames(hpv_marg) <- c("HPV -", "HPV +", "HPV ++")
rownames(hpv_marg) <- c("HPV - Hist Neg", "HPV + Hist Neg", "HPV ++ Hist Neg")
kable_styling(kable(hpv_marg))

neg_hpv_pos_hist <- c(2,4)
pos_hpv_pos_hist <- c(6,8)
pos_pos_hpv_pos_hist <- c(10,12)
hpv_marg <- matrix(0,3,3)
hpv_marg[1,1] <- sum(est_tran[neg_hpv_pos_hist,neg_hpv])
hpv_marg[1,2] <- sum(est_tran[neg_hpv_pos_hist,pos_hpv])
hpv_marg[1,3] <- sum(est_tran[neg_hpv_pos_hist,pos_pos_hpv])
hpv_marg[2,1] <- sum(est_tran[pos_hpv_pos_hist,neg_hpv])
hpv_marg[2,2] <- sum(est_tran[pos_hpv_pos_hist,pos_hpv])
hpv_marg[2,3] <- sum(est_tran[pos_hpv_pos_hist,pos_pos_hpv])
hpv_marg[3,1] <- sum(est_tran[pos_pos_hpv_pos_hist,neg_hpv])
hpv_marg[3,2] <- sum(est_tran[pos_pos_hpv_pos_hist,pos_hpv])
hpv_marg[3,3] <- sum(est_tran[pos_pos_hpv_pos_hist,pos_pos_hpv])
hpv_marg <- hpv_marg / rowSums(hpv_marg)
colnames(hpv_marg) <- c("HPV -", "HPV +", "HPV ++")
rownames(hpv_marg) <- c("HPV - Hist Pos", "HPV + Hist Pos", "HPV ++ Hist Pos")
kable_styling(kable(hpv_marg))

neg_cyt <- c(1,2,5,6,9,10)
pos_cyt <- c(3,4,7,8,11,12)
cyt_marg <- matrix(0,2,2)
cyt_marg[1,1] <- sum(est_tran[neg_cyt,neg_cyt])
cyt_marg[1,2] <- sum(est_tran[neg_cyt,pos_cyt])
cyt_marg[2,1] <- sum(est_tran[pos_cyt,neg_cyt])
cyt_marg[2,2] <- sum(est_tran[pos_cyt,pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("CYT Neg", "CYT Pos")
rownames(cyt_marg) <- c("CYT Neg", "CYT Pos")
kable_styling(kable(cyt_marg))

neg_cyt_neg_hist <- c(1,5,9)
pos_cyt_neg_hist <- c(3,7,11)
cyt_marg <- matrix(0,2,2)
cyt_marg[1,1] <- sum(est_tran[neg_cyt_neg_hist,neg_cyt])
cyt_marg[1,2] <- sum(est_tran[neg_cyt_neg_hist,pos_cyt])
cyt_marg[2,1] <- sum(est_tran[pos_cyt_neg_hist,neg_cyt])
cyt_marg[2,2] <- sum(est_tran[pos_cyt_neg_hist,pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("CYT Neg", "CYT Pos")
rownames(cyt_marg) <- c("CYT Neg Hist Neg", "CYT Pos Hist Neg")
kable_styling(kable(cyt_marg))

neg_cyt_pos_hist <- c(2,6,10)
pos_cyt_pos_hist <- c(4,8,12)
cyt_marg <- matrix(0,2,2)
cyt_marg[1,1] <- sum(est_tran[neg_cyt_pos_hist,neg_cyt])
cyt_marg[1,2] <- sum(est_tran[neg_cyt_pos_hist,pos_cyt])
cyt_marg[2,1] <- sum(est_tran[pos_cyt_pos_hist,neg_cyt])
cyt_marg[2,2] <- sum(est_tran[pos_cyt_pos_hist,pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("CYT Neg", "CYT Pos")
rownames(cyt_marg) <- c("CYT Neg Hist Pos", "CYT Pos Hist Pos")
kable_styling(kable(cyt_marg))

neg_cyt_neg_hpv <- c(1,2)
pos_cyt_neg_hpv <- c(3,4)
cyt_marg <- matrix(0,2,2)
cyt_marg[1,1] <- sum(est_tran[neg_cyt_neg_hpv,neg_cyt])
cyt_marg[1,2] <- sum(est_tran[neg_cyt_neg_hpv,pos_cyt])
cyt_marg[2,1] <- sum(est_tran[pos_cyt_neg_hpv,neg_cyt])
cyt_marg[2,2] <- sum(est_tran[pos_cyt_neg_hpv,pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("Cyt Neg", "Cyt Pos")
rownames(cyt_marg) <- c("Cyt Neg HPV -", "Cyt Pos HPV -")
kable_styling(kable(cyt_marg))

neg_cyt_pos_hpv <- c(5,6)
pos_cyt_pos_hpv <- c(7,8)
cyt_marg <- matrix(0,2,2)
cyt_marg[1,1] <- sum(est_tran[neg_cyt_pos_hpv,neg_cyt])
cyt_marg[1,2] <- sum(est_tran[neg_cyt_pos_hpv,pos_cyt])
cyt_marg[2,1] <- sum(est_tran[pos_cyt_pos_hpv,neg_cyt])
cyt_marg[2,2] <- sum(est_tran[pos_cyt_pos_hpv,pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("Cyt Neg", "Cyt Pos")
rownames(cyt_marg) <- c("Cyt Neg HPV +", "Cyt Pos HPV +")
kable_styling(kable(cyt_marg))

neg_cyt_pos_pos_hpv <- c(9,10)
pos_cyt_pos_pos_hpv <- c(11,12)
cyt_marg <- matrix(0,2,2)
cyt_marg[1,1] <- sum(est_tran[neg_cyt_pos_pos_hpv,neg_cyt])
cyt_marg[1,2] <- sum(est_tran[neg_cyt_pos_pos_hpv,pos_cyt])
cyt_marg[2,1] <- sum(est_tran[pos_cyt_pos_pos_hpv,neg_cyt])
cyt_marg[2,2] <- sum(est_tran[pos_cyt_pos_pos_hpv,pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("Cyt Neg", "Cyt Pos")
rownames(cyt_marg) <- c("Cyt Neg HPV ++", "Cyt Pos HPV ++")
kable_styling(kable(cyt_marg))

neg_hist <- c(1,3,5,7,9,11)
pos_hist <- c(2,4,6,8,10,12)
hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_tran[neg_hist,neg_hist])
hist_marg[1,2] <- sum(est_tran[neg_hist,pos_hist])
hist_marg[2,1] <- sum(est_tran[pos_hist,neg_hist])
hist_marg[2,2] <- sum(est_tran[pos_hist,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
names <- c("Hist Neg", "Hist Pos")
colnames(hist_marg) <- names
rownames(hist_marg) <- names
kable_styling(kable(hist_marg))

neg_hist_neg_cyt <- c(1,5,9)
pos_hist_neg_cyt <- c(2,6,10)
hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_tran[neg_hist_neg_cyt,neg_hist])
hist_marg[1,2] <- sum(est_tran[neg_hist_neg_cyt,pos_hist])
hist_marg[2,1] <- sum(est_tran[pos_hist_neg_cyt,neg_hist])
hist_marg[2,2] <- sum(est_tran[pos_hist_neg_cyt,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist Neg", "Hist Pos")
rownames(hist_marg) <- c("Hist Neg Cyt Neg", "Hist Pos Cyt Neg")
kable_styling(kable(hist_marg))

neg_hist_cyt_pos <- c(3,7,11)
pos_hist_cyt_pos <- c(4,8,12)
hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_tran[neg_hist_cyt_pos,neg_hist])
hist_marg[1,2] <- sum(est_tran[neg_hist_cyt_pos,pos_hist])
hist_marg[2,1] <- sum(est_tran[pos_hist_cyt_pos,neg_hist])
hist_marg[2,2] <- sum(est_tran[pos_hist_cyt_pos,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist Neg", "Hist Pos")
rownames(hist_marg) <- c("Hist Neg Cyt Pos", "Hist Pos Cyt Pos")
kable_styling(kable(hist_marg))

neg_hist_neg_hpv <- c(1,3)
pos_hist_neg_hpv <- c(2,4)
hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_tran[neg_hist_neg_hpv,neg_hist])
hist_marg[1,2] <- sum(est_tran[neg_hist_neg_hpv,pos_hist])
hist_marg[2,1] <- sum(est_tran[pos_hist_neg_hpv,neg_hist])
hist_marg[2,2] <- sum(est_tran[pos_hist_neg_hpv,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist Neg", "Hist Pos")
rownames(hist_marg) <- c("Hist Neg HPV -", "Hist Pos HPV -")
kable_styling(kable(hist_marg))

neg_hist_pos_hpv <- c(5,7)
pos_hist_pos_hpv <- c(6,8)
hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_tran[neg_hist_pos_hpv,neg_hist])
hist_marg[1,2] <- sum(est_tran[neg_hist_pos_hpv,pos_hist])
hist_marg[2,1] <- sum(est_tran[pos_hist_pos_hpv,neg_hist])
hist_marg[2,2] <- sum(est_tran[pos_hist_pos_hpv,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist Neg", "Hist Pos")
rownames(hist_marg) <- c("Hist Neg HPV +", "Hist Pos HPV +")
kable_styling(kable(hist_marg))

neg_hist_pos_pos_hpv <- c(9,11)
pos_hist_pos_pos_hpv <- c(10,12)
hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_tran[neg_hist_pos_pos_hpv,neg_hist])
hist_marg[1,2] <- sum(est_tran[neg_hist_pos_pos_hpv,pos_hist])
hist_marg[2,1] <- sum(est_tran[pos_hist_pos_pos_hpv,neg_hist])
hist_marg[2,2] <- sum(est_tran[pos_hist_pos_pos_hpv,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist Neg", "Hist Pos")
rownames(hist_marg) <- c("Hist Neg HPV ++", "Hist Pos HPV ++")
kable_styling(kable(hist_marg))

```


```{r}
#Class
neg_cyt <- c(1,2,5,6,9,10)
pos_cyt <- c(3,4,7,8,11,12)
neg_cyt_neg_hist <- c(1,5,9)
pos_cyt_neg_hist <- c(3,7,11)
neg_cyt_pos_hist <- c(2,6,10)
pos_cyt_pos_hist <- c(4,8,12)
neg_hist <- c(1,3,5,7,9,11)
pos_hist <- c(2,4,6,8,10,12)
neg_hist_neg_cyt <- c(1,5,9)
pos_hist_neg_cyt <- c(2,6,10)
neg_hist_cyt_pos <- c(3,7,11)
pos_hist_cyt_pos <- c(4,8,12)
cyt_marg <- matrix(0,2,2)
cyt_marg[1,1] <- sum(est_class[neg_cyt,neg_cyt])
cyt_marg[1,2] <- sum(est_class[neg_cyt,pos_cyt])
cyt_marg[2,1] <- sum(est_class[pos_cyt,neg_cyt])
cyt_marg[2,2] <- sum(est_class[pos_cyt,pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("CYT Neg", "CYT Pos")
rownames(cyt_marg) <- c("CYT Neg", "CYT Pos")
kable_styling(kable(cyt_marg))


cyt_marg <- matrix(0,2,2)
cyt_marg[1,1] <- sum(est_class[neg_cyt_neg_hist,neg_cyt])
cyt_marg[1,2] <- sum(est_class[neg_cyt_neg_hist,pos_cyt])
cyt_marg[2,1] <- sum(est_class[pos_cyt_neg_hist,neg_cyt])
cyt_marg[2,2] <- sum(est_class[pos_cyt_neg_hist,pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("CYT Neg", "CYT Pos")
rownames(cyt_marg) <- c("CYT Neg Hist Neg", "CYT Pos Hist Neg")
kable_styling(kable(cyt_marg))


cyt_marg <- matrix(0,2,2)
cyt_marg[1,1] <- sum(est_class[neg_cyt_pos_hist,neg_cyt])
cyt_marg[1,2] <- sum(est_class[neg_cyt_pos_hist,pos_cyt])
cyt_marg[2,1] <- sum(est_class[pos_cyt_pos_hist,neg_cyt])
cyt_marg[2,2] <- sum(est_class[pos_cyt_pos_hist,pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("CYT Neg", "CYT Pos")
rownames(cyt_marg) <- c("CYT Neg Hist Pos", "CYT Pos Hist Pos")
kable_styling(kable(cyt_marg))


cyt_marg <- matrix(0,2,2)
cyt_marg[1,1] <- sum(est_class[neg_cyt_neg_hpv,neg_cyt])
cyt_marg[1,2] <- sum(est_class[neg_cyt_neg_hpv,pos_cyt])
cyt_marg[2,1] <- sum(est_class[pos_cyt_neg_hpv,neg_cyt])
cyt_marg[2,2] <- sum(est_class[pos_cyt_neg_hpv,pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("Cyt Neg", "Cyt Pos")
rownames(cyt_marg) <- c("Cyt Neg HPV -", "Cyt Pos HPV -")
kable_styling(kable(cyt_marg))

cyt_marg <- matrix(0,2,2)
cyt_marg[1,1] <- sum(est_class[neg_cyt_pos_hpv,neg_cyt])
cyt_marg[1,2] <- sum(est_class[neg_cyt_pos_hpv,pos_cyt])
cyt_marg[2,1] <- sum(est_class[pos_cyt_pos_hpv,neg_cyt])
cyt_marg[2,2] <- sum(est_class[pos_cyt_pos_hpv,pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("Cyt Neg", "Cyt Pos")
rownames(cyt_marg) <- c("Cyt Neg HPV +", "Cyt Pos HPV +")
kable_styling(kable(cyt_marg))

cyt_marg <- matrix(0,2,2)
cyt_marg[1,1] <- sum(est_class[neg_cyt_pos_pos_hpv,neg_cyt])
cyt_marg[1,2] <- sum(est_class[neg_cyt_pos_pos_hpv,pos_cyt])
cyt_marg[2,1] <- sum(est_class[pos_cyt_pos_pos_hpv,neg_cyt])
cyt_marg[2,2] <- sum(est_class[pos_cyt_pos_pos_hpv,pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("Cyt Neg", "Cyt Pos")
rownames(cyt_marg) <- c("Cyt Neg HPV ++", "Cyt Pos HPV ++")
kable_styling(kable(cyt_marg))

hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_class[neg_hist,neg_hist])
hist_marg[1,2] <- sum(est_class[neg_hist,pos_hist])
hist_marg[2,1] <- sum(est_class[pos_hist,neg_hist])
hist_marg[2,2] <- sum(est_class[pos_hist,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
names <- c("Hist Neg", "Hist Pos")
colnames(hist_marg) <- names
rownames(hist_marg) <- names
kable_styling(kable(hist_marg))


hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_class[neg_hist_neg_cyt,neg_hist])
hist_marg[1,2] <- sum(est_class[neg_hist_neg_cyt,pos_hist])
hist_marg[2,1] <- sum(est_class[pos_hist_neg_cyt,neg_hist])
hist_marg[2,2] <- sum(est_class[pos_hist_neg_cyt,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist Neg", "Hist Pos")
rownames(hist_marg) <- c("Hist Neg Cyt Neg", "Hist Pos Cyt Neg")
kable_styling(kable(hist_marg))


hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_class[neg_hist_cyt_pos,neg_hist])
hist_marg[1,2] <- sum(est_class[neg_hist_cyt_pos,pos_hist])
hist_marg[2,1] <- sum(est_class[pos_hist_cyt_pos,neg_hist])
hist_marg[2,2] <- sum(est_class[pos_hist_cyt_pos,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist Neg", "Hist Pos")
rownames(hist_marg) <- c("Hist Neg Cyt Pos", "Hist Pos Cyt Pos")
kable_styling(kable(hist_marg))


hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_class[neg_hist_neg_hpv,neg_hist])
hist_marg[1,2] <- sum(est_class[neg_hist_neg_hpv,pos_hist])
hist_marg[2,1] <- sum(est_class[pos_hist_neg_hpv,neg_hist])
hist_marg[2,2] <- sum(est_class[pos_hist_neg_hpv,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist Neg", "Hist Pos")
rownames(hist_marg) <- c("Hist Neg HPV -", "Hist Pos HPV -")
kable_styling(kable(hist_marg))

hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_class[neg_hist_pos_hpv,neg_hist])
hist_marg[1,2] <- sum(est_class[neg_hist_pos_hpv,pos_hist])
hist_marg[2,1] <- sum(est_class[pos_hist_pos_hpv,neg_hist])
hist_marg[2,2] <- sum(est_class[pos_hist_pos_hpv,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist Neg", "Hist Pos")
rownames(hist_marg) <- c("Hist Neg HPV +", "Hist Pos HPV +")
kable_styling(kable(hist_marg))

hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_class[neg_hist_pos_pos_hpv,neg_hist])
hist_marg[1,2] <- sum(est_class[neg_hist_pos_pos_hpv,pos_hist])
hist_marg[2,1] <- sum(est_class[pos_hist_pos_pos_hpv,neg_hist])
hist_marg[2,2] <- sum(est_class[pos_hist_pos_pos_hpv,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist Neg", "Hist Pos")
rownames(hist_marg) <- c("Hist Neg HPV ++", "Hist Pos HPV ++")
kable_styling(kable(hist_marg))

```
