---
title: "Parsing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, include = FALSE, eval = FALSE}
setwd("data/")
list_of_names <- list.files()
reps <- length(list_of_names)

init_array <- array(0,dim = c(1,3,reps))
tran_array <- array(0,dim = c(3,3,reps))
class_array <- array(0,dim = c(3,3,reps))
pi_array<- array(0,dim = c(1,1,reps))

init_true_array <- array(0,dim = c(1,3,reps))
tran_true_array <- array(0,dim = c(3,3,reps))
class_true_array <- array(0,dim = c(3,3,reps))
class_true_count_array <- array(0,dim = c(3,3,reps))
pi_true_array<- array(0,dim = c(1,1,reps))

init_list <- vector("list", length = reps)
tran_list <- vector("list", length = reps)
class_list <- vector("list", length = reps)

init_true_list <- vector("list", length = reps)
tran_true_list <- vector("list", length = reps)
class_true_list <- vector("list", length = reps)
class_true_count_list <- vector("list", length = reps)

data_obs_list <- vector("list", length = reps)

data_true_list <- vector("list", length = reps)

count <- 1

for (name in list_of_names){
  load(name)
  
  obs_prameters <- to_save[[1]]
  true_parameters <- to_save[[2]]
  datas <- to_save[[3]]
  
  init_list[[count]] <- obs_prameters[[1]]
  tran_list[[count]] <- obs_prameters[[2]]
  class_list[[count]] <- obs_prameters[[3]]
  
  init_true_list[[count]] <- true_parameters[[1]]
  tran_true_list[[count]] <- true_parameters[[2]]
  class_true_list[[count]] <- true_parameters[[3]]
  class_true_count_list[[count]] <- true_parameters[[4]]
  
  data_obs_list[[count]] <- datas[[1]]
  
  data_true_list[[count]] <- datas[[2]]
  
  pi_array[1,1,count] <- obs_prameters[[4]]
  pi_true_array[1,1,count] <- true_parameters[[5]]
  
  for (i in 1:3){
    init_array[1,i,count] <- init_list[[count]][i]
    init_true_array[1,i,count] <- init_true_list[[count]][i]
    for (j in 1:3){
      tran_array[i,j,count] <- tran_list[[count]][i,j]
      tran_true_array[i,j,count] <- tran_true_list[[count]][i,j]
      
      class_array[i,j,count] <- class_list[[count]][i,j]
      class_true_array[i,j,count] <- class_true_list[[count]][i,j]
      class_true_count_array[i,j,count] <- class_true_count_list[[count]][i,j]
    }
  }
  
  
  count <- count + 1
}


#############################################

state_visits <- numeric(3)
state_visits_true <- numeric(3)

init_med <- numeric(3)
tran_med <- matrix(0,3,3)
class_med <- matrix(0,3,3)
pi_med <- median(pi_array[1,1,])

init_true_med <- numeric(3)
tran_true_med <- matrix(0,3,3)
class_true_med <- matrix(0,3,3)
pi_true_med <- median(pi_true_array[1,1,])

init_avg <- numeric(3)
tran_avg <- matrix(0,3,3)
class_avg <- matrix(0,3,3)
pi_avg <- mean(pi_array[1,1,])

init_true_avg <- numeric(3)
tran_true_avg <- matrix(0,3,3)
class_true_avg <- matrix(0,3,3)
pi_true_avg <- mean(pi_true_array[1,1,])

class_true_count_med <- matrix(0,3,3)
class_true_count_avg <- matrix(0,3,3)


for (i in 1:3){
  init_med[i] <- median(init_array[1,i,])
  init_true_med[i] <- median(init_true_array[1,i,])
  
  init_avg[i] <- mean(init_array[1,i,])
  init_true_avg[i] <- mean(init_true_array[1,i,])
  
  for (j in 1:3){
    tran_med[i,j] <- median(tran_array[i,j,])
    tran_true_med[i,j] <- median(tran_true_array[i,j,])
    tran_avg[i,j] <- mean(tran_array[i,j,])
    tran_true_avg[i,j] <- mean(tran_true_array[i,j,])
    
    class_med[i,j] <- median(class_array[i,j,])
    class_true_med[i,j] <- median(class_true_array[i,j,])
    class_avg[i,j] <- mean(class_array[i,j,])
    class_true_avg[i,j] <- mean(class_true_array[i,j,])
    
    class_true_count_med[i,j] <- median(class_true_count_array[i,j,])
    class_true_count_avg[i,j] <- mean(class_true_count_array[i,j,])
    
  }
}
length <- 5
k <- c(0:2)

transition_true <- matrix(0L, nrow = length(k), ncol = length(k))
transition_obs <- matrix(0L, nrow = length(k), ncol = length(k))

initial_true <- numeric(3)
initial_obs <- numeric(3)

transition_obs <- transition_obs/reps
transition_true <- transition_true/reps

initial_true <- initial_true/reps
initial_obs <- initial_obs/reps
```

```{r}
state_labels <- c("First", "Second", "Third")
```

```{r, echo = FALSE, fig.width=15, fig.height=15}
ClassificationHeatmap <- function(X_tran, state_labels, adj_labels){
  library(reshape)
  library(ggplot2)
  rownames(X_tran) <- c(state_labels)
  colnames(X_tran) <- c(state_labels)
  X_tran.m <- melt(X_tran)
  X_tran.m$X1 <- factor(X_tran.m$X1, levels = rev(adj_labels))
  X_tran.m$X2 <- factor(X_tran.m$X2, levels = (adj_labels))
  ggplot(X_tran.m,aes(X2, X1)) + 
    geom_tile(aes(fill = value),color = "white") + 
    scale_fill_gradient2(low = "blue",high = "red") +
    labs(x = "New State", y = "Initial State", caption = "Observed - True") + 
    theme(axis.text.y = element_text(size = 10), axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5)) + 
    theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))) + 
    theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0))) +
    theme(plot.caption = element_text(hjust = .5))
}
```

```{r}
GenerateTable <- function(mean_mat,truth_mat, title){
  library(knitr)
  library(kableExtra)
  row_names <- c("Mean", "Truth")
  
  length_of_ind <- dim(mean_mat)[1]
  combined_mat <- matrix(0,length_of_ind*2, length_of_ind)
  
  for (i in 1:(length_of_ind * 2)){
    which_one <- i %% 2
    true_ind <- ceiling(i/2)
    if (which_one == 0){
      combined_mat[i,] <- mean_mat[true_ind,]
    } else if (which_one == 1){
      combined_mat[i,] <- truth_mat[true_ind,]
    } 
  }
  
  rownames(combined_mat) <- rep(row_names,length_of_ind)
  
  colnames(combined_mat) <- c(0:(length_of_ind -1))
  
  kable(combined_mat, caption = title) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = T) %>%
    group_rows("State 0",1,2) %>%
    group_rows("State 1",3,4) %>%
    group_rows("State 2",5,6)
    
  
    
}
```

```{r}
ClassificationHeatmap(tran_med - tran_true_med, state_labels, state_labels)
ClassificationHeatmap(class_med - class_true_med, state_labels, state_labels)
GenerateTable(tran_med, tran_true_med,"Transition (Median)")
GenerateTable(class_med, class_true_med,"Classification (Median)")
```