---
title: "Parsing Real"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, include = FALSE, eval = FALSE}
setwd("Data/Real/16/More Sat Med Var Add/")
states <- 16
list_of_names <- list.files()
reps <- length(list_of_names)
getwd()

init_init_array <- array(0,dim = c(1,states,reps))
tran_init_array <- array(0,dim = c(states,states,reps))
class_init_array <- array(0,dim = c(states,states,reps))

init_est_array <- array(0,dim = c(1,states,reps))
tran_est_array <- array(0,dim = c(states,states,reps))
class_est_array <- array(0,dim = c(states,states,reps))

likelihood_array <- numeric(reps)

init_init_list <- vector("list", length = reps)
tran_init_list <- vector("list", length = reps)
class_init_list <- vector("list", length = reps)

init_est_list <- vector("list", length = reps)
tran_est_list <- vector("list", length = reps)
class_est_list <- vector("list", length = reps)

count <- 1

for (name in list_of_names){
  load(name)
  
  init_parameters <- to_save[[1]]
  est_parameters <- to_save[[2]]
  likelihood_array[count] <- to_save[[3]]
  
  init_init_list[[count]] <- init_parameters[[1]]
  tran_init_list[[count]] <- init_parameters[[2]]
  class_init_list[[count]] <- init_parameters[[3]]
  
  init_est_list[[count]] <- est_parameters[[1]]
  tran_est_list[[count]] <- est_parameters[[2]]
  class_est_list[[count]] <- est_parameters[[3]]
  
  
  
  
  for (i in 1:states){
    init_init_array[1,i,count] <- init_init_list[[count]][i]
    init_est_array[1,i,count] <- init_est_list[[count]][i]
    
    for (j in 1:states){
      tran_init_array[i,j,count] <- tran_init_list[[count]][i,j]
      tran_est_array[i,j,count] <- tran_est_list[[count]][i,j]
      
      class_init_array[i,j,count] <- class_init_list[[count]][i,j]
      class_est_array[i,j,count] <- class_est_list[[count]][i,j]
    }
  }
  
  count <- count + 1
}


#############################################



```

```{r, echo = FALSE, fig.width=15, fig.height=15}
ClassificationHeatmap <- function(X_tran, state_labels = c(0:15), adj_labels){
  library(reshape)
  library(ggplot2)
  rownames(X_tran) <- c(state_labels)
  colnames(X_tran) <- c(state_labels)
  X_tran.m <- melt(X_tran)
  X_tran.m$X1 <- factor(X_tran.m$X1, levels = rev(adj_labels))
  X_tran.m$X2 <- factor(X_tran.m$X2, levels = (adj_labels))
  ggplot(X_tran.m,aes(X2, X1)) + 
    geom_tile(aes(fill = value),color = "white") + 
    scale_fill_gradient2(low = "blue",high = "red") +
    labs(x = "New State", y = "Initial State", caption = "Observed - True") + 
    theme(axis.text.y = element_text(size = 10), axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5)) + 
    theme(axis.text.x = element_text(angle = 0)) + 
    theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))) + 
    theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0))) +
    theme(plot.caption = element_text(hjust = .5))
}
```

```{r}
GenerateInitTable <- function(init, init_var, title){
  library(knitr)
  library(kableExtra)
  combined_mat <- rbind(init, init_var)
  rownames(combined_mat) <- c("Estimate", "Std Dev")
  colnames(combined_mat) <- c(0:(length(init) -1))
  
  kable(combined_mat, caption = title) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = T) %>%
    group_rows("State 0",1,2) 
}
```

```{r}
GenerateTable <- function(mean_mat,var_mat,title){
  library(knitr)
  library(kableExtra)
  row_names <- c("Estimate", "Std Dev")
  
  length_of_ind <- dim(mean_mat)[1]
  combined_mat <- matrix(0,length_of_ind*2, length_of_ind)
  
  for (i in 1:(length_of_ind * 2)){
    which_one <- i %% 2
    true_ind <- ceiling(i/2)
    if (which_one == 1){
      combined_mat[i,] <- mean_mat[true_ind,]
    } else if (which_one == 0){
      combined_mat[i,] <- var_mat[true_ind,]
    } 
  }
  
  rownames(combined_mat) <- rep(row_names,length_of_ind)

  colnames(combined_mat) <- c(0:(length_of_ind -1))
  
  kable(combined_mat, caption = title) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = T) %>%
    group_rows("State 0",1,2) %>%
    group_rows("State 1",3,4) %>%
    group_rows("State 2",5,6) %>%
    group_rows("State 3",7,8) %>%
    group_rows("State 4",9,10) %>%
    group_rows("State 5",11,12) %>%
    group_rows("State 6",13,14) %>%
    group_rows("State 7",15,16) %>%
    group_rows("State 8",17,18) %>%
    group_rows("State 9",19,20) %>%
    group_rows("State 10",21,22) %>%
    group_rows("State 11",23,24) %>%
    group_rows("State 12",25,26) %>%
    group_rows("State 13",27,28) %>%
    group_rows("State 14",29,30) %>%
    group_rows("State 15",31,32) 
    
  
    
}
```

```{r}

state_labels <- c(0:15)


first <- which.max(likelihood_array)

est_tran <- tran_est_array[,,first]
# est_tran[c(2,4,6,8,10,12,14,16),] <- 0



ClassificationHeatmap(est_tran, state_labels, state_labels) + ggtitle("Transition")
# ClassificationHeatmap(tran_sd, state_labels, state_labels) + ggtitle("Transition SD")

ClassificationHeatmap(class_est_array[,,first], state_labels, state_labels) + ggtitle("Classification")
# ClassificationHeatmap(class_sd, state_labels, state_labels) + ggtitle("Classification SD")

```

```{r}

GenerateInitTable(init_est_array[1,,first], init_sd, "Initial (Median")

GenerateTable(tran_est_array[,,first], tran_sd,"Transition (Median)")

GenerateTable(class_est_array[,,first], class_sd,"Classification (Median)")
```

```{r}
# hist(tran_est_array[3,4,])
# hist(tran_est_array[5,12,])
# hist(tran_est_array[7,4,])
# hist(tran_est_array[7,11,])
hist(tran_est_array[9,1,])
# hist(tran_est_array[9,4,])
# hist(tran_est_array[9,13,])
hist(tran_est_array[11,15,])
hist(tran_est_array[13,1,])
# hist(tran_est_array[13,2,])
hist(tran_est_array[13,4,])
# hist(tran_est_array[15,2,])
# hist(tran_est_array[15,3,])
```

```{r}
# hist(class_est_array[4,3,])

hist(class_est_array[6,5,])
# hist(class_est_array[6,7,])
hist(class_est_array[6,8,])

# hist(class_est_array[8,7,])
hist(class_est_array[8,8,])

hist(class_est_array[10,9,])
hist(class_est_array[10,12,])

hist(class_est_array[12,9,])
hist(class_est_array[12,11,])
hist(class_est_array[12,12,])

hist(class_est_array[16,15,])
hist(class_est_array[16,16,])
```

```{r}
init_hpv_neg <- sum(init_est_array[,,first][c(1:4)])
init_hpv_pos1 <- sum(init_est_array[,,first][c(5:8)])
init_hpv_pos2 <- sum(init_est_array[,,first][c(9:12)])
init_hpv_pos3 <- sum(init_est_array[,,first][c(13:16)])
init_hpv <- matrix(c(init_hpv_neg, init_hpv_pos1, init_hpv_pos2, init_hpv_pos3),1,4)
colnames(init_hpv) <- c("HPV -", "HPV + ", "HPV ++", "HPV +++")
kable_styling(kable(init_hpv))

init_cyt_neg <- sum(init_est_array[,,first][c(1,2,5,6,9,10,13,14)])
init_cyt_pos <- 1 - init_cyt_neg
init_cyt <- matrix(c(init_cyt_neg,init_cyt_pos),1,2)
colnames(init_cyt) <- c("Cyt Negative", "Cyt Positive")
kable_styling(kable(init_cyt))

init_copa_neg <-  sum(init_est_array[,,first][c(1,3,5,7,9,13,15)])
init_copa_pos <- 1 - init_copa_neg
init_copa <- matrix(c(init_copa_neg, init_copa_pos),1,2)
colnames(init_cancer) <- c("Copa Negative", "Copa Positive")
kable_styling(kable(init_cancer))
```