---
title: "eda states"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
lngth <- 500
state_0 <- numeric(lngth)
state_1 <- numeric(lngth)
state_2 <- numeric(lngth)
state_3 <- numeric(lngth)
state_6 <- numeric(lngth)
state_7 <- numeric(lngth)
state_8 <- numeric(lngth)
state_9 <- numeric(lngth)

state_0_0 <- numeric(lngth)
state_0_1 <- numeric(lngth)
state_1_0 <- numeric(lngth)
state_1_1 <- numeric(lngth)

state__00 <- numeric(lngth)
state__01 <- numeric(lngth)
state__10 <- numeric(lngth)
state__11 <- numeric(lngth)
state__20 <- numeric(lngth)
state__21 <- numeric(lngth)


x <- numeric(10)
  
for (k in 1:lngth){
  data_full <- createSubData(1000, data_2429)

  state_0_val <- 0
  state_1_val <- 0
  state_2_val <- 0
  state_3_val <- 0
  state_6_val <- 0
  state_7_val <- 0
  state_8_val <- 0
  state_9_val <- 0
  
  state_0_0_val <- 0
  state_0_1_val <- 0
  state_1_0_val <- 0
  state_1_1_val <- 0
  
  
  
  state__00_val <- 0
  state__01_val <- 0
  state__10_val <- 0
  state__11_val <- 0
  state__20_val <- 0
  state__21_val <- 0
  
  for (i in 1:dim(data_full)[1]){
    for (j in 2:dim(data_full)[2]){
      
      if (is.na(data_full[i,j,2])){
        if (!is.na(data_full[i,j,1])){
          if (data_full[i,j,1] == 0){state_0_val <- state_0_val + 1}
          else if (data_full[i,j,1] == 1){state_1_val <- state_1_val + 1}
          else if (data_full[i,j,1] == 2){state_2_val <- state_2_val + 1}
          else if (data_full[i,j,1] == 3){state_3_val <- state_3_val + 1}   
          else if (data_full[i,j,1] == 6){state_6_val <- state_6_val + 1}
          else if (data_full[i,j,1] == 7){state_7_val <- state_7_val + 1}
          else if (data_full[i,j,1] == 8){state_8_val <- state_8_val + 1}
          else if (data_full[i,j,1] == 9){state_9_val <- state_9_val + 1}
        }
      }

      
      if (!is.na(data_full[i,j,1]) & !is.na(data_full[i,j,2]) & !is.na(data_full[i,j,3])){
        if (is.na(data_full[i,j,4])){
          if (data_full[i,j,1] == 0 & data_full[i,j,2] == 2 & data_full[i,j,3] == 4 ){state_0_0_val <- state_0_0_val + 1}
          else if (data_full[i,j,1] == 1 & data_full[i,j,2] == 3 & data_full[i,j,3] == 5 ){state_0_0_val <- state_0_1_val + 1}
          
          else if (data_full[i,j,1] == 6 & data_full[i,j,2] == 8 & data_full[i,j,3] == 10){state_1_0_val <- state_1_0_val + 1}
          else if (data_full[i,j,1] == 7 & data_full[i,j,2] == 9 & data_full[i,j,3] == 11 ){state_1_1_val <- state_1_1_val + 1}
        }
      }
      
      if (!is.na(data_full[i,j,1]) & !is.na(data_full[i,j,2])){
        if (is.na(data_full[i,j,3])){
          if (data_full[i,j,1] == 0 & data_full[i,j,2] == 6) {state__00_val <- state__00_val + 1}
          if (data_full[i,j,1] == 1 & data_full[i,j,2] == 7) {state__01_val <- state__01_val + 1}
          if (data_full[i,j,1] == 2 & data_full[i,j,2] == 8) {state__10_val <- state__10_val + 1}
          if (data_full[i,j,1] == 3 & data_full[i,j,2] == 9) {state__11_val <- state__11_val + 1}
          if (data_full[i,j,1] == 4 & data_full[i,j,2] == 10){state__20_val <- state__20_val + 1}
          if (data_full[i,j,1] == 5 & data_full[i,j,2] == 11){state__21_val <- state__21_val + 1}
        }
      }
      
    }
  }

  state_0[k] <- state_0_val
  state_1[k] <- state_1_val
  state_2[k] <- state_2_val
  state_3[k] <- state_3_val
  state_6[k] <- state_6_val
  state_7[k] <- state_7_val
  state_8[k] <- state_8_val
  state_9[k] <- state_9_val
  
  state_0_0[k] <- state_0_0_val
  state_0_1[k] <- state_0_1_val
  state_1_0[k] <- state_1_0_val
  state_1_1[k] <- state_1_1_val
  
  state__00[k] <- state__00_val
  state__01[k] <- state__01_val
  state__10[k] <- state__10_val
  state__11[k] <- state__11_val
  state__20[k] <- state__20_val
  state__21[k] <- state__21_val

}
```

```{r}
par(mfrow=c(1,2))
hist(state_0)
hist(state_1)

hist(state_2)
hist(state_3)

hist(state_6)
hist(state_7)

hist(state_8)
hist(state_9)

hist(state_0_0)
hist(state_0_1)
hist(state_1_0)
hist(state_1_1)

hist(state__00)
hist(state__01)
hist(state__10)
hist(state__11)
hist(state__20)
hist(state__21)
```

