---
title: "EM Algorithm Simulated"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
numOfStates <- function(data){
  return(c(min(data, na.rm = TRUE):max(data, na.rm = TRUE)))
}
```

```{r}
#Generates n by t binary matrix
#0 corresponds to HPV negative and 1 to positive
#Different probabilities for incidence (p_01) and recurrence (p_11)
#manually change 
generateHPV <- function(n,t){
  walk <- matrix(0L, nrow = n, ncol = t)
  p_01 <- 0.1
  p_11 <- 0.9
  
  for (i in 1:n){
    walk[i,1] <- rbinom(1,1,.1)
  }
  
  for (i in 1:n){
    for (j in 2:t){
      if (walk[i,j-1] == 0){
        p_current <- p_01
      } else {
        p_current <- p_11
      }
      walk[i,j] <- rbinom(1,1,p_current)
    }
  }
  return(walk)
}
```

```{r}
#Generates n by t Pap smear data matrix
#6 stages (Normal to HSIL+)
#p_i is given the ith state probability of transitioning to a different state
#p_initial is initial dist
generatePap <- function(n,t){
  pap <- matrix(0L, nrow = n, ncol = t)
  p_0 <- c(0.8,0.15,0.05)
  p_1 <- c(0.3,0.6,0.1)
  p_2 <- c(0.1,0.4,0.5)
 
  p_initial <- c(0.6,0.3,0.1)
  
  for (i in 1:n){
    pap[i,1] <- which(rmultinom(1,1,p_initial) == 1) - 1
  }
  
  for (i in 1:n){
    for (j in 2:t){
      if (pap[i,j-1] == 0){
        p_current <- p_0
      } else if (pap[i,j-1] == 1){
        p_current <- p_1
      } else if (pap[i,j-1] == 2){
        p_current <- p_2
      } 
      pap[i,j] <- which(rmultinom(1,1,p_current) == 1) - 1
    }
  }
  return(pap)
}
```

```{r}
generateCopa <- function(n,t){
  walk <- matrix(0L, nrow = n, ncol = t)
  p_01 <- 0.01
  p_11 <- 1
  
  for (i in 1:n){
    walk[i,1] <- rbinom(1,1,.01)
  }
  
  for (i in 1:n){
    for (j in 2:t){
      if (walk[i,j-1] == 0){
        p_current <- p_01
      } else {
        p_current <- p_11
      }
      walk[i,j] <- rbinom(1,1,p_current)
    }
  }
  return(walk)
}
```

```{r}
generateAll <- function(n,t){
  all_three <- matrix(0L, nrow = n, ncol = t)
  p_0 <- c(0.8,0.00,0.04,0.00,0.00,0.00,0.14,0.00,0.03,0.00,0.00,0.00)
  p_1 <- c(0.00,0.06,0.00,0.07,0.00,0.40,0.00,0.08,0.00,0.27,0.00,0.12)
  p_2 <- c(0.53,0.00,0.11,0.00,0.00,0.00,0.04,0.00,0.3,0.01,0.00,0.00)
  p_3 <- c(0.00,0.00,0.00,0.16,0.00,0.01,0.00,0.16,0.00,0.57,0.00,0.10)
  p_4 <- c(0.40,0.00,0.19,0.00,0.15,0.00,0.07,0.00,0.09,0.03,0.04,0.01)
  p_5 <- c(0.00,0.00,0.00,0.08,0.00,0.44,0.00,0.09,0.00,0.27,0.00,0.12)
  p_6 <- c(0.33,0.00,0.01,0.00,0.00,0.00,0.31,0.01,0.29,0.02,0.01,0.01)
  p_7 <- c(0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.24,0.00,0.48,0.00,0.27)
  p_8 <- c(0.23,0.00,0.05,0.00,0.00,0.00,0.26,0.00,0.35,0.02,0.07,0.01)
  p_9 <- c(0.00,0.01,0.00,0.02,0.00,0.00,0.00,0.15,0.00,0.55,0.00,0.27)
  p_10 <- c(0.26,0.00,0.1,0.01,0.00,0.00,0.15,0.01,0.31,0.05,0.06,0.04)
  p_11 <- c(0.00,0.00,0.00,0.02,0.00,0.02,0.00,0.13,0.00,0.38,0.00,0.45)
  p_initial <- c(0.65,0.00,0.08,0.00,0.00,0.00,0.19,0.00,0.08,0.00,0.00,0.00)
  
  for (i in 1:n){
    all_three[i,1] <- which(rmultinom(1,1,p_initial) == 1) - 1
  }
  
  for (i in 1:n){
    for (j in 2:t){
      if (all_three[i,j-1] == 0){
        p_current <- p_0
      } else if (all_three[i,j-1] == 1){
        p_current <- p_1
      } else if (all_three[i,j-1] == 2){
        p_current <- p_2
      } else if (all_three[i,j-1] == 3){
        p_current <- p_3
      } else if (all_three[i,j-1] == 4){
        p_current <- p_4
      } else if (all_three[i,j-1] == 5){
        p_current <- p_5
      } else if (all_three[i,j-1] == 6){
        p_current <- p_6
      } else if (all_three[i,j-1] == 7){
        p_current <- p_7
      } else if (all_three[i,j-1] == 8){
        p_current <- p_8
      } else if (all_three[i,j-1] == 9){
        p_current <- p_9
      } else if (all_three[i,j-1] == 10){
        p_current <- p_10
      } else if (all_three[i,j-1] == 11){
        p_current <- p_11
      } 
      all_three[i,j] <- which(rmultinom(1,1,p_current) == 1) - 1
    }
  }
  
  HPV <- matrix(0L, nrow = n, ncol = t)
  Pap <- matrix(0L, nrow = n, ncol = t)
  Copa <- matrix(0L, nrow = n, ncol = t)
  for (i in 1:dim(all_three)[1]){
    for (j in 1:dim(all_three)[2]){
      HPV[i,j] <- all_three[i,j] %/% 6
      Pap[i,j] <- (all_three[i,j] %% 6) %/% 2
      Copa[i,j] <- all_three[i,j] %% 2
    }
  }
  return(list(HPV,Pap,Copa))
}
```

```{r}
Breakdown <- function(data){
  HPV <- matrix(0L, dim(data)[1],dim(data)[2])
  Pap <- matrix(0L, dim(data)[1],dim(data)[2])
  Copa <- matrix(0L, dim(data)[1],dim(data)[2])
  for (i in 1:dim(all_three)[1]){
    for (j in 1:dim(all_three)[2]){
      HPV[i,j] <- all_three[i,j] %/% 6
      Pap[i,j] <- (all_three[i,j] %% 6) %/% 2
      Copa[i,j] <- all_three[i,j] %% 2
    }
  }
  return(list(HPV,Pap,Copa))
}
```

```{r}
#Given HPV data and probability of misclassification creates altered data matrix
generateHPVX <- function(HPV, class_matrix){
  p_0 <- class_matrix[1,]
  p_1 <- class_matrix[2,]
  
  for (i in 1:dim(HPV)[1]){
    for (j in 1:dim(HPV)[2]) {
      if (HPV[i,j] == 0) {HPV[i,j] = sample(c(0,1),1,prob=p_0)}
      else {HPV[i,j] = sample(c(0,1),1,prob=p_1)}
    }
  }
  return(HPV)
}
```

```{r}
#Given Pap data and probability of misclassification creates altered data matrix
#Also hand specifies probability of specific misclassifications
#Prob 0 along diag as we are already assuming a misclassification event 
generatePapX <- function(Pap, class_matrix, p_misclass){
  p_0 <- class_matrix[1,]
  p_1 <- class_matrix[2,]
  p_2 <- class_matrix[3,]
  
  for (i in 1:dim(Pap)[1]){
    for (j in 1:dim(Pap)[2]) {
      if (Pap[i,j] == 0) {Pap[i,j] = sample(c(0,1,2),1,prob = p_0)}
      else if (Pap[i,j] == 1) {Pap[i,j] = sample(c(0,1,2),1,prob = p_1)}
      else if (Pap[i,j] == 2) {Pap[i,j] = sample(c(0,1,2),1,prob = p_2)}
    }
  }
  return(Pap)
}
```

```{r}
#Given Copa data and probability of misclassification creates altered data matrix
#Also hand specifies probability of specific misclassifications
#Prob 0 along diag as we are already assuming a misclassification event 
generateCopaX <- function(Copa, class_matrix ){
  p_0 <- class_matrix[1,]
  p_1 <- class_matrix[2,]
  
  for (i in 1:dim(Copa)[1]){
    for (j in 1:dim(Copa)[2]) {
      if (Copa[i,j] == 0) {Copa[i,j] = sample(c(0,1),1,prob = p_0)}
      else if (Copa[i,j] == 1) {Copa[i,j] = sample(c(0,1),1,prob = p_1)}
    }
  }
  return(Copa)
}
```

```{r}
BigCombine <- function(HPV,Pap,Copa){
  HPV_class <- matrix(c(.95,.05,.05,.95),2,2)
  Pap_class <- matrix(c(.9,.05,.05,.05,.9,.05,.05,.05,.9),3,3)
  Copa_class <- matrix(c(.99,0,.01,1),2,2)
  class_matrix <- FullClassificationMatrix(HPV_class,Pap_class,Copa_class)
  
  
  HPVX <- generateHPVX(HPV,HPV_class)
  PapX <- generatePapX(Pap,Pap_class)
  CopaX <- generateCopaX(Copa,Copa_class)
  
  true_data_full <- Combiner(HPV,Pap,Copa)
  obs_data_full <- Combiner(HPVX,PapX,CopaX)
  true_misclass <- CalcTrueMisclass(obs_data_full,true_data_full)
  
  for (i in 1:dim(CopaX)[1]){
    for (j in 1:dim(CopaX)[2]){
      if (!is.na(CopaX[i,j]) & CopaX[i,j] == 1){
        
        if (j < dim(CopaX)[2]){
          CopaX[i,(j+1):dim(CopaX)[2]] <- NaN
          PapX[i,(j+1):dim(CopaX)[2]] <- NaN
          HPVX[i,(j+1):dim(CopaX)[2]] <- NaN
          
          
          
        }
      }
    }
  }
  
  for (i in 1:dim(HPV)[1]){
    for (j in 1:dim(HPV)[2]){
      
      if (rbinom(1,1,0)){
        CopaX[i,j] <- NaN
      }
      if (rbinom(1,1,0)){
        PapX[i,j] <- NaN
      }
      if (rbinom(1,1,0)){
        HPVX[i,j] <- NaN
      }
      if (rbinom(1,1,0)){
        HPVX[i,j] <- NaN
        PapX[i,j] <- NaN
        CopaX[i,j] <- NaN
      }
    }
  }
  
  true_data_full <- Combiner(HPV,Pap,Copa)
  obs_data_full <- Combiner(HPVX,PapX,CopaX)
  return(list(true_data_full,obs_data_full, true_misclass))
}
```

```{r}
CombinerHelper <- function(HPV,Pap,Copa,k1,k2,k3,dimen){
  state_space = rep(NaN,dimen)
  if (is.na(HPV)){HPV_miss <- 1}
  else {HPV_miss <- 0}
  
  if (is.na(Pap)){Pap_miss <- 1}
  else {Pap_miss <- 0}
  
  if (is.na(Copa)){Copa_miss <- 1}
  else {Copa_miss <- 0}
  
  if (HPV_miss == 1 & Pap_miss == 0 & Copa_miss == 0){
    base_val <- Pap*length(k3) + Copa
    for (i in 1:length(k1)){
      state_space[i] <- base_val + (length(k2) * length(k3) * k1[i])
    }
  }
  
  else if (HPV_miss == 0 & Pap_miss == 1 & Copa_miss == 0){
    base_val <- HPV*length(k2)*length(k3) + Copa
    for (i in 1:length(k2)){
      state_space[i] <- base_val + (length(k3) * k2[i])
    }
  }
  
  else if (HPV_miss == 0 & Pap_miss == 0 & Copa_miss == 1){
    base_val <- HPV*length(k2)*length(k3) + Pap*length(k3)
    for (i in 1:length(k3)){
      state_space[i] <- base_val + (k3[i])
    }
  }
  
  else if (HPV_miss == 1 & Pap_miss == 1 & Copa_miss == 0){
    base_val <- Copa
    for (i in 1:length(k1)){
      for (j in 1:length(k2)){
        state_space[((i-1)*length(k2) + j)] <- base_val + (length(k2) * length(k3) * k1[i]) + (length(k3) * k2[j])
      }
    }
  }
  
  else if (HPV_miss == 1 & Pap_miss == 0 & Copa_miss == 1){
    base_val <- Pap * length(k3)
    for (i in 1:length(k1)){
      for (j in 1:length(k3)){
        state_space[((i-1)*length(k3) + j)] <- base_val + (length(k2) * length(k3) * k1[i]) + (k3[j])
      }
    }
  }
  
  else if (HPV_miss == 0 & Pap_miss == 1 & Copa_miss == 1){
    base_val <- HPV * length(k2) * length(k3)
    for (i in 1:length(k2)){
      for (j in 1:length(k3)){
        state_space[((i-1)*length(k3) + j)] <- base_val + (length(k3) * k2[i]) + (k3[j])
      }
    }
  }
  
  #No missing
  else {
    state_space[1] <- (HPV * length(k2) * length(k3)) + (Pap * length(k3)) + Copa
  }
  
  return(state_space)
}
```


```{r}
GetMarginalProb <- function(data_matrix, type){
  HPV <-  matrix(0L, nrow = 2, ncol = 2)
  HPV[1,1] <- sum(data_matrix[1:6,1:6])
  HPV[1,2] <- sum(data_matrix[1:6,7:12])
  HPV[2,2] <- sum(data_matrix[7:12,7:12])
  HPV[2,1] <- sum(data_matrix[7:12,1:6])
  
  Pap <-  matrix(0L, nrow = 3, ncol = 3)
  Pap[1,1] <- sum(data_matrix[c(1,2,7,8),c(1,2,7,8)])
  Pap[1,2] <- sum(data_matrix[c(1,2,7,8),c(3,4,9,10)])
  Pap[1,3] <- sum(data_matrix[c(1,2,7,8),c(5,6,11,12)])
  
  Pap[2,1] <- sum(data_matrix[c(3,4,9,10),c(1,2,7,8)])
  Pap[2,2] <- sum(data_matrix[c(3,4,9,10),c(3,4,9,10)])
  Pap[2,3] <- sum(data_matrix[c(3,4,9,10),c(5,6,11,12)])
  
  Pap[3,1] <- sum(data_matrix[c(5,6,11,12),c(1,2,7,8)])
  Pap[3,2] <- sum(data_matrix[c(5,6,11,12),c(3,4,9,10)])
  Pap[3,3] <- sum(data_matrix[c(5,6,11,12),c(5,6,11,12)])
  
  Copa <-  matrix(0L, nrow = 2, ncol = 2)
  Copa[1,1] <- sum(data_matrix[c(1,3,5,7,9,11),c(1,3,5,7,9,11)])
  Copa[1,2] <- sum(data_matrix[c(1,3,5,7,9,11),c(2,4,6,8,10,12)])
  Copa[2,2] <- sum(data_matrix[c(2,4,6,8,10,12),c(2,4,6,8,10,12)])
  Copa[2,1] <- sum(data_matrix[c(2,4,6,8,10,12),c(1,3,5,7,9,11)])
  
  if (type == 1){
    return(Normalize(HPV))
  } else if (type == 2){
    return(Normalize(Pap))
  } else {
    return(Normalize(Copa))
  }

}
```

```{r}
CalcTrueMisclass <- function(data,true_data){
  misclass_mat <- matrix(0,12,12)
  for (i in 1:dim(data)[1]){
    for (j in 1:dim(data)[2]){
      if (!is.na(data[i,j,1]) & is.na(data[i,j,2])){
        misclass_mat[true_data[i,j,1]+1,data[i,j,1]+1] <- misclass_mat[true_data[i,j,1]+1,data[i,j,1]+1] + 1
      } 
    }
  }
  return(Normalize(misclass_mat))
}
```

```{r}
library(sas7bdat)
library(powerplus)
library(dplyr)


all_three <- generateAll(2000,5)
HPV <- all_three[[1]]
Pap <- all_three[[2]]
Copa <- all_three[[3]]

full_data <- BigCombine(HPV,Pap,Copa)
true_data_full <- full_data[1][[1]]
data_full <- full_data[2][[1]]

true_misclass <- full_data[3][[1]]
true_tran <- createTransitionFull(true_data_full)
true_init <- InitialProbFull(true_data_full)

Copa_freq <- array(0,c(2,3,2))
Pap_freq <- array(0,c(2,2,3))
HPV_freq <- array(0,c(3,2,2))
PapCopa_freq <- array(0,c(1,2,6))
HPVCopa_freq <- array(0,c(1,3,4))
HPVPap_freq <- array(0,c(1,2,6))
for (i in 1:dim(data_full)[1]){
  for (j in 1:dim(data_full)[2]){
    if (!is.na(data_full[i,j,1]) & is.na(data_full[i,j,2])){
      
      HPV_val <- data_full[i,j,1] %/% 6
      Pap_val <- (data_full[i,j,1] %% 6) %/% 2
      Copa_val <- data_full[i,j,1] %% 2

      Copa_freq[HPV_val+1,Pap_val+1,Copa_val+1] <- Copa_freq[HPV_val+1,Pap_val+1,Copa_val+1] + 1
      Pap_freq[HPV_val+1,Copa_val+1,Pap_val+1] <- Pap_freq[HPV_val+1,Copa_val+1,Pap_val+1] + 1
      HPV_freq[Pap_val+1,Copa_val+1,HPV_val+1] <- HPV_freq[Pap_val+1,Copa_val+1,HPV_val+1] + 1
      
      PapCopa_freq[1,HPV_val+1,(2*Pap_val + Copa_val + 1)] <- PapCopa_freq[1,HPV_val+1,(2*Pap_val + Copa_val + 1)] + 1
      HPVCopa_freq[1,Pap_val+1,(2*HPV_val + Copa_val + 1)] <- HPVCopa_freq[1,Pap_val+1,(2*HPV_val + Copa_val + 1)] + 1
      HPVPap_freq[1,Copa_val+1,(3*HPV_val + Pap_val + 1)]  <- HPVPap_freq[1,Copa_val+1,(3*HPV_val + Pap_val + 1)] + 1
    }
  }
}

Copa_freq <- Normalize2(Copa_freq)
Pap_freq <- Normalize2(Pap_freq)
HPV_freq <- Normalize2(HPV_freq)

PapCopa_freq <- Normalize2(PapCopa_freq)
HPVCopa_freq <- Normalize2(HPVCopa_freq)
HPVPap_freq <- Normalize2(HPVPap_freq)





tran_full <- createTransitionFull(data_full)
init_full <- InitialProbFull(data_full)

HPV_class <- matrix(c(.99,.01,.01,.99),2,2)
Pap_class <- matrix(c(.99,.01,.01,.01,.99,.01,.01,.01,.99),3,3)
Copa_class <- matrix(c(.99,.01,.000000001,.999999999),2,2)

class_full <- FullClassificationMatrix(HPV_class,Pap_class,Copa_class)

init_full <- CalcYi(data_full,1,init_full,tran_full,class_full)
tran_full <- CalcTransition(data_full,init_full,tran_full,class_full)
old_likelihood <- CalcLikelihood(data_full,init_full,tran_full,class_full)

init_full <- CalcYi(data_full,1,init_full,tran_full,class_full)
tran_full <- CalcTransition(data_full,init_full,tran_full,class_full)
likelihood <- CalcLikelihood(data_full,init_full,tran_full,class_full)

print(likelihood - old_likelihood)

while (abs(likelihood - old_likelihood) > .001){

  old_likelihood <- likelihood
  init_full <- CalcYi(data_full,1,init_full,tran_full,class_full)
  tran_full <- CalcTransition(data_full,init_full,tran_full,class_full)
  likelihood <- CalcLikelihood(data_full,init_full,tran_full,class_full)
  print(likelihood - old_likelihood)

}

####################################


HPV_class <- matrix(c(.8,.2,.2,.8),2,2)
Pap_class <- matrix(c(.8,.1,.1,.1,.8,.1,.1,.1,.8),3,3)
Copa_class <- matrix(c(.9,0,.1,1),2,2)

class_full <- FullClassificationMatrix(HPV_class,Pap_class,Copa_class)


init_full <- CalcYi(data_full,1,init_full,tran_full,class_full)
tran_full <- CalcTransition(data_full,init_full,tran_full,class_full)
class_full <- CalcClassification(data_full,init_full,tran_full,class_full)
old_likelihood <- CalcLikelihood(data_full,init_full,tran_full,class_full)

init_full <- CalcYi(data_full,1,init_full,tran_full,class_full)
tran_full <- CalcTransition(data_full,init_full,tran_full,class_full)
class_full <- CalcClassification(data_full,init_full,tran_full,class_full)
likelihood <- CalcLikelihood(data_full,init_full,tran_full,class_full)

print(likelihood - old_likelihood)

while (abs(likelihood - old_likelihood) > .0001){


  old_likelihood <- likelihood
  init_full <- CalcYi(data_full,1,init_full,tran_full,class_full)
  tran_full <- CalcTransition(data_full,init_full,tran_full,class_full)
  class_full <- CalcClassification(data_full,init_full,tran_full,class_full)
  likelihood <- CalcLikelihood(data_full,init_full,tran_full,class_full)
  print(likelihood - old_likelihood)
}
```


```{r}
freq <- numeric(12)
for (i in 0:11){
  freq[i+1] <- sum(data_full == i,na.rm=TRUE)
}
barplot(freq)
resid <- round(class_full,3) - round(true_misclass,3)

```
