---
title: "EM Pattern"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
numOfStates <- function(data,type){
  if (missing(type)){
    return(c(min(data, na.rm = TRUE):max(data, na.rm = TRUE)))
  }
  else if (type == 1){
    return (c(0:1))
  } else if (type == 2){
    return(c(0:2))
  } else if (type == 3){
    return (c(0:1))
  }
  
}
```

```{r}
#Generates n by t binary matrix
#0 corresponds to HPV negative and 1 to positive
#Different probabilities for incidence (p_01) and recurrence (p_11)
#manually change 
generateHPV <- function(n,t){
  walk <- matrix(0L, nrow = n, ncol = t)
  p_01 <- 0.1
  p_11 <- 0.9
  
  for (i in 1:n){
    walk[i,1] <- rbinom(1,1,.1)
  }
  
  for (i in 1:n){
    for (j in 2:t){
      if (walk[i,j-1] == 0){
        p_current <- p_01
      } else {
        p_current <- p_11
      }
      walk[i,j] <- rbinom(1,1,p_current)
    }
  }
  return(walk)
}
```

```{r}
#Generates n by t Pap smear data matrix
#6 stages (Normal to HSIL+)
#p_i is given the ith state probability of transitioning to a different state
#p_initial is initial dist
generatePap <- function(n,t){
  pap <- matrix(0L, nrow = n, ncol = t)
  p_0 <- c(0.8,0.15,0.05)
  p_1 <- c(0.3,0.6,0.1)
  p_2 <- c(0.1,0.4,0.5)
 
  p_initial <- c(0.6,0.3,0.1)
  
  for (i in 1:n){
    pap[i,1] <- which(rmultinom(1,1,p_initial) == 1) - 1
  }
  
  for (i in 1:n){
    for (j in 2:t){
      if (pap[i,j-1] == 0){
        p_current <- p_0
      } else if (pap[i,j-1] == 1){
        p_current <- p_1
      } else if (pap[i,j-1] == 2){
        p_current <- p_2
      } 
      pap[i,j] <- which(rmultinom(1,1,p_current) == 1) - 1
    }
  }
  return(pap)
}
```

```{r}
generateCopa <- function(n,t){
  walk <- matrix(0L, nrow = n, ncol = t)
  p_01 <- 0.01
  p_11 <- 1
  
  for (i in 1:n){
    walk[i,1] <- rbinom(1,1,.01)
  }
  
  for (i in 1:n){
    for (j in 2:t){
      if (walk[i,j-1] == 0){
        p_current <- p_01
      } else {
        p_current <- p_11
      }
      walk[i,j] <- rbinom(1,1,p_current)
    }
  }
  return(walk)
}
```

```{r}
generateAll <- function(n,t){
  all_three <- matrix(0L, nrow = n, ncol = t)
  p_0 <- c(0.8,0.00,0.04,0.00,0.00,0.00,0.14,0.00,0.03,0.00,0.00,0.00)
  p_1 <- c(0.00,0.06,0.00,0.07,0.00,0.40,0.00,0.08,0.00,0.27,0.00,0.12)
  p_2 <- c(0.53,0.00,0.11,0.00,0.00,0.00,0.04,0.00,0.3,0.01,0.00,0.00)
  p_3 <- c(0.00,0.00,0.00,0.16,0.00,0.01,0.00,0.16,0.00,0.57,0.00,0.10)
  p_4 <- c(0.40,0.00,0.19,0.00,0.15,0.00,0.07,0.00,0.09,0.03,0.04,0.01)
  p_5 <- c(0.00,0.00,0.00,0.08,0.00,0.44,0.00,0.09,0.00,0.27,0.00,0.12)
  p_6 <- c(0.33,0.00,0.01,0.00,0.00,0.00,0.31,0.01,0.29,0.02,0.01,0.01)
  p_7 <- c(0.00,0.00,0.00,0.01,0.00,0.00,0.00,0.24,0.00,0.48,0.00,0.27)
  p_8 <- c(0.23,0.00,0.05,0.00,0.00,0.00,0.26,0.00,0.35,0.02,0.07,0.01)
  p_9 <- c(0.00,0.01,0.00,0.02,0.00,0.00,0.00,0.15,0.00,0.55,0.00,0.27)
  p_10 <- c(0.26,0.00,0.1,0.01,0.00,0.00,0.15,0.01,0.31,0.05,0.06,0.04)
  p_11 <- c(0.00,0.00,0.00,0.02,0.00,0.02,0.00,0.13,0.00,0.38,0.00,0.45)
  p_initial <- c(0.65,0.00,0.08,0.00,0.00,0.00,0.19,0.00,0.08,0.00,0.00,0.00)
  
  for (i in 1:n){
    all_three[i,1] <- which(rmultinom(1,1,p_initial) == 1) - 1
  }
  
  for (i in 1:n){
    for (j in 2:t){
      if (all_three[i,j-1] == 0){
        p_current <- p_0
      } else if (all_three[i,j-1] == 1){
        p_current <- p_1
      } else if (all_three[i,j-1] == 2){
        p_current <- p_2
      } else if (all_three[i,j-1] == 3){
        p_current <- p_3
      } else if (all_three[i,j-1] == 4){
        p_current <- p_4
      } else if (all_three[i,j-1] == 5){
        p_current <- p_5
      } else if (all_three[i,j-1] == 6){
        p_current <- p_6
      } else if (all_three[i,j-1] == 7){
        p_current <- p_7
      } else if (all_three[i,j-1] == 8){
        p_current <- p_8
      } else if (all_three[i,j-1] == 9){
        p_current <- p_9
      } else if (all_three[i,j-1] == 10){
        p_current <- p_10
      } else if (all_three[i,j-1] == 11){
        p_current <- p_11
      } 
      all_three[i,j] <- which(rmultinom(1,1,p_current) == 1) - 1
    }
  }
  
  HPV <- matrix(0L, nrow = n, ncol = t)
  Pap <- matrix(0L, nrow = n, ncol = t)
  Copa <- matrix(0L, nrow = n, ncol = t)
  for (i in 1:dim(all_three)[1]){
    for (j in 1:dim(all_three)[2]){
      HPV[i,j] <- all_three[i,j] %/% 6
      Pap[i,j] <- (all_three[i,j] %% 6) %/% 2
      Copa[i,j] <- all_three[i,j] %% 2
    }
  }
  return(list(HPV,Pap,Copa))
}
```

```{r}
Breakdown <- function(data){
  HPV <- matrix(0L, dim(data)[1],dim(data)[2])
  Pap <- matrix(0L, dim(data)[1],dim(data)[2])
  Copa <- matrix(0L, dim(data)[1],dim(data)[2])
  for (i in 1:dim(all_three)[1]){
    for (j in 1:dim(all_three)[2]){
      HPV[i,j] <- all_three[i,j] %/% 6
      Pap[i,j] <- (all_three[i,j] %% 6) %/% 2
      Copa[i,j] <- all_three[i,j] %% 2
    }
  }
  return(list(HPV,Pap,Copa))
}
```

```{r}
#Given HPV data and probability of misclassification creates altered data matrix
generateHPVX <- function(HPV, class_matrix){
  p_0 <- class_matrix[1,]
  p_1 <- class_matrix[2,]
  
  for (i in 1:dim(HPV)[1]){
    for (j in 1:dim(HPV)[2]) {
      if (HPV[i,j] == 0) {HPV[i,j] = sample(c(0,1),1,prob=p_0)}
      else {HPV[i,j] = sample(c(0,1),1,prob=p_1)}
    }
  }
  return(HPV)
}
```

```{r}
#Given Pap data and probability of misclassification creates altered data matrix
#Also hand specifies probability of specific misclassifications
#Prob 0 along diag as we are already assuming a misclassification event 
generatePapX <- function(Pap, class_matrix, p_misclass){
  p_0 <- class_matrix[1,]
  p_1 <- class_matrix[2,]
  p_2 <- class_matrix[3,]
  
  for (i in 1:dim(Pap)[1]){
    for (j in 1:dim(Pap)[2]) {
      if (Pap[i,j] == 0) {Pap[i,j] = sample(c(0,1,2),1,prob = p_0)}
      else if (Pap[i,j] == 1) {Pap[i,j] = sample(c(0,1,2),1,prob = p_1)}
      else if (Pap[i,j] == 2) {Pap[i,j] = sample(c(0,1,2),1,prob = p_2)}
    }
  }
  return(Pap)
}
```

```{r}
#Given Copa data and probability of misclassification creates altered data matrix
#Also hand specifies probability of specific misclassifications
#Prob 0 along diag as we are already assuming a misclassification event 
generateCopaX <- function(Copa, class_matrix ){
  p_0 <- class_matrix[1,]
  p_1 <- class_matrix[2,]
  
  for (i in 1:dim(Copa)[1]){
    for (j in 1:dim(Copa)[2]) {
      if (Copa[i,j] == 0) {Copa[i,j] = sample(c(0,1),1,prob = p_0)}
      else if (Copa[i,j] == 1) {Copa[i,j] = sample(c(0,1),1,prob = p_1)}
    }
  }
  return(Copa)
}
```

```{r}
BigCombine <- function(HPV,Pap,Copa){
  HPV_class <- matrix(c(.95,.05,.05,.95),2,2)
  Pap_class <- matrix(c(.9,.05,.05,.05,.9,.05,.05,.05,.9),3,3)
  Copa_class <- matrix(c(.99,0,.01,1),2,2)
  class_matrix <- FullClassificationMatrix(HPV_class,Pap_class,Copa_class)
  
  
  HPVX <- generateHPVX(HPV,HPV_class)
  PapX <- generatePapX(Pap,Pap_class)
  CopaX <- generateCopaX(Copa,Copa_class)
  
  
  for (i in 1:dim(CopaX)[1]){
    for (j in 1:dim(CopaX)[2]){
      if (!is.na(CopaX[i,j]) & CopaX[i,j] == 1){
        
        if (j < dim(CopaX)[2]){
          CopaX[i,(j+1):dim(CopaX)[2]] <- NaN
          PapX[i,(j+1):dim(CopaX)[2]] <- NaN
          HPVX[i,(j+1):dim(CopaX)[2]] <- NaN
          
          
          
        }
      }
    }
  }
  
  for (i in 1:dim(HPV)[1]){
    for (j in 1:dim(HPV)[2]){
      
      if (rbinom(1,1,0)){
        CopaX[i,j] <- NaN
      }
      if (rbinom(1,1,0)){
        PapX[i,j] <- NaN
      }
      if (rbinom(1,1,0)){
        HPVX[i,j] <- NaN
      }
      if (rbinom(1,1,0)){
        HPVX[i,j] <- NaN
        PapX[i,j] <- NaN
        CopaX[i,j] <- NaN
      }
    }
  }
  
  return(list(list(HPV,Pap,Copa),list(HPVX,PapX,CopaX)))
}
```

```{r}
#takes in 2x2, 6x6, 5x5 classification matrix and outputs a 60 x 60 full classification matrix 
FullClassificationMatrix <- function(HPV,Pap,Copa){
  l1 <- dim(HPV)[1]
  l2 <- dim(Pap)[1]
  l3 <- dim(Copa)[1]
  row_index <- 0
  col_index <- 0
  
  full_matrix <- matrix(0L, nrow = l1*l2*l3, ncol = l1*l2*l3)
  
  for (i in 1:dim(HPV)[1]){
    for (j in 1:dim(Pap)[1]){
      for (k in 1:dim(Copa)[1]){
        for (i2 in 1:dim(HPV)[2]){
          for (j2 in 1:dim(Pap)[2]){
            for (k2 in 1:dim(Copa)[2]){
              row_index <- ((i-1)*l2*l3) + ((j-1)*l3) + k
              col_index <- ((i2-1)*l2*l3) + ((j2-1)*l3) + k2
              
              full_matrix[row_index,col_index] <-full_matrix[row_index,col_index] + (HPV[i,i2] * Pap[j,j2] * Copa[k,k2])
            }
          }
        }
      }
    }
  }
  return(full_matrix)
}
```

```{r}
GetPatterns <- function(HPVX,PapX,CopaX){
  library(plyr)
  options(scipen = 999)
  vals <- rep(NaN,dim(HPVX)[1])
  for (i in 1:dim(HPVX)[1]){
    val <- ""
    for(j in 1:dim(HPVX)[2]){
  
      if (is.na(HPVX[i,j])){
        HPVX_val <- 2
      } else {
        HPVX_val <- HPVX[i,j] 
      }
      
      if (is.na(PapX[i,j])){
        PapX_val <- 3
      } else {
        PapX_val <- PapX[i,j] 
      }
      
      if (is.na(CopaX[i,j])){
        CopaX_val <- 2
      } else {
        CopaX_val <- CopaX[i,j] 
      }
      triplet <- paste0(HPVX_val,PapX_val,CopaX_val)
      val <- paste0(val, triplet)
    }
    
    vals[i] <- val
  }
  return(vals)
}
```

```{r}
ReduceStateSpace <- function(data){
  for (i in 1:dim(data)[1]){
    for (j in 13:17){
      if (!is.na(data[i,j])){
        if (data[i,j] == 2) {data[i,j] <- 1}
        if (data[i,j] > 2) {data[i,j] <- 2}
      }
    } 
    for (j in 18:22){
      if (!is.na(data[i,j])){
        if (data[i,j] < 2) {data[i,j] <- 0}
        if (data[i,j] > 1) {data[i,j] <- 1}
      }
    }
  }
  return(data)
}
```

```{r}
createSubData <- function(rows, data_2429, all){
  library(dplyr)
  if (missing(all)){
    # data <- vector("list", length = 2)
    # data <- split(data_2429,data_2429$GL_MED_BMI>25)
    # data_2429 <- data[[2]]
    data_2429_altered <- sample_n(data_2429,rows)
  } else {
    data_2429_altered <- data_2429
  }

  data_2429_altered <- ReduceStateSpace(data_2429_altered)
  
  
  HPV <- data_2429_altered[,8:12]
  Pap <- data_2429_altered[,13:17]
  Copa <- data_2429_altered[,18:22]
  
  for (i in 1:dim(Copa)[1]){
    for (j in 1:dim(Copa)[2]){
      if (!is.na(Copa[i,j]) & Copa[i,j] == 1){
        
        if (j < dim(Copa)[2]){
          Copa[i,(j+1):dim(Copa)[2]] <- NaN
          Pap[i,(j+1):dim(Copa)[2]] <- NaN
          HPV[i,(j+1):dim(Copa)[2]] <- NaN
          
        }
      }
    }
  }
  
  return(list(HPV,Pap,Copa))
}
```

```{r}
CombinerHelper <- function(HPV,Pap,Copa,k1,k2,k3,dimen){
  state_space = rep(NaN,dimen)
  if (is.na(HPV)){HPV_miss <- 1}
  else {HPV_miss <- 0}
  
  if (is.na(Pap)){Pap_miss <- 1}
  else {Pap_miss <- 0}
  
  if (is.na(Copa)){Copa_miss <- 1}
  else {Copa_miss <- 0}
  
  if (HPV_miss == 1 & Pap_miss == 0 & Copa_miss == 0){
    base_val <- Pap*length(k3) + Copa
    for (i in 1:length(k1)){
      state_space[i] <- base_val + (length(k2) * length(k3) * k1[i])
    }
  }
  
  else if (HPV_miss == 0 & Pap_miss == 1 & Copa_miss == 0){
    base_val <- HPV*length(k2)*length(k3) + Copa
    for (i in 1:length(k2)){
      state_space[i] <- base_val + (length(k3) * k2[i])
    }
  }
  
  else if (HPV_miss == 0 & Pap_miss == 0 & Copa_miss == 1){
    if(HPV == 0  & Pap == 0){
      state_space[1] <- 0
    } else if(HPV == 0 & Pap == 1){
      state_space[1] <- 2
    } else {
      base_val <- HPV*length(k2)*length(k3) + Pap*length(k3)
      for (i in 1:length(k3)){
        state_space[i] <- base_val + (k3[i])
      }
    }
  }
  
  else if (HPV_miss == 1 & Pap_miss == 1 & Copa_miss == 0){
    base_val <- Copa
    for (i in 1:length(k1)){
      for (j in 1:length(k2)){
        state_space[((i-1)*length(k2) + j)] <- base_val + (length(k2) * length(k3) * k1[i]) + (length(k3) * k2[j])
      }
    }
  }
  
  else if (HPV_miss == 1 & Pap_miss == 0 & Copa_miss == 1){
    base_val <- Pap * length(k3)
    for (i in 1:length(k1)){
      for (j in 1:length(k3)){
        state_space[((i-1)*length(k3) + j)] <- base_val + (length(k2) * length(k3) * k1[i]) + (k3[j])
      }
    }
  }
  
  else if (HPV_miss == 0 & Pap_miss == 1 & Copa_miss == 1){
    base_val <- HPV * length(k2) * length(k3)
    for (i in 1:length(k2)){
      for (j in 1:length(k3)){
        state_space[((i-1)*length(k3) + j)] <- base_val + (length(k3) * k2[i]) + (k3[j])
      }
    }
  }
  
  #No missing
  else {
    state_space[1] <- (HPV * length(k2) * length(k3)) + (Pap * length(k3)) + Copa
  }
  
  return(state_space)
}
```

```{r}
Combiner <- function(HPV,Pap,Copa){
  l1 <- length(numOfStates(HPV,1))[[1]]
  k1 <- numOfStates(HPV,1)
  l2 <- length(numOfStates(Pap,2))
  k2 <- numOfStates(Pap,2)
  l3 <- length(numOfStates(Copa, 3))
  k3 <- numOfStates(Copa, 3)
  dimen <- max(l1*l2,l1*l3,l2,l3)
  full_matrix <- array(0,c(dim(HPV)[1],dim(HPV)[2],dimen))
  
  
  for (i in 1:dim(HPV)[1]){
    for (j in 1:dim(HPV)[2]){
      
      if (!is.na(HPV)[i,j] | !is.na(Pap)[i,j] | !is.na(Copa)[i,j]){
        state_space <- CombinerHelper(HPV[i,j],Pap[i,j],Copa[i,j],k1,k2,k3,dimen)
      } else {
        state_space <- rep(NaN,dimen)
      }
      
      for (k in 1:length(state_space)){
        full_matrix[i,j,k] <- state_space[k]
      }
      
    }
  }
  return(full_matrix)
}
```

```{r}
Pattern2Data <- function(unique_patterns){
  time_length <- 5
  n <- dim(unique_patterns)[1]
  data_array <- array(0, dim=c(n,time_length,6))
  freq_vec <- numeric(n)
  for (i in 1:n){
    freq_vec[i] <- unique_patterns$Freq[[i]]
    pattern <- unique_patterns$all_patterns[[i]]
    HPV_mat <- matrix(0, ncol=time_length,nrow=1)
    Pap_mat <- matrix(0, ncol=time_length,nrow=1)
    Copa_mat <- matrix(0, ncol=time_length,nrow=1)
    
    for (time in 1:time_length){
      visit <- substr(pattern, 3*time -2, 3*time)
      HPV_val <- substr(visit,1,1)
      Pap_val <- substr(visit,2,2)
      Copa_val <- substr(visit,3,3)
      
      if (HPV_val == 2){
        HPV_val <- NaN
      }
      if (Pap_val == 3){
        Pap_val <- NaN
      }
      if (Copa_val == 2){
        Copa_val <- NaN
      }
      HPV_mat[1,time] <- as.integer(HPV_val)
      Pap_mat[1,time] <- as.integer(Pap_val)
      Copa_mat[1,time] <- as.integer(Copa_val)
    }
    num_visit <- Combiner(HPV_mat,Pap_mat,Copa_mat)
    data_array[i,,] <- num_visit
  }
  return(list(data_array, freq_vec))
}

```

```{r}
n <- 1000
all_three <- generateAll(n,5)
all_six <- BigCombine(all_three[[1]],all_three[[2]],all_three[[3]])

HPVX <- all_six[[2]][[1]]
PapX <- all_six[[2]][[2]]
CopaX <- all_six[[2]][[3]]

```

```{r}
library(sas7bdat)
#data_2429 <- read.sas7bdat("wom_2529.sas7bdat")
all_three <- createSubData(500,data_2429)
HPV <- as.matrix(all_three[[1]])
Pap <- as.matrix(all_three[[2]])
Copa <- as.matrix(all_three[[3]])
big_data <- Combiner(HPV, Pap, Copa)

all_patterns <- as.data.frame(GetPatterns(HPV,Pap,Copa))
unique_patterns <- as.data.frame(table(all_patterns))

pattern_list <- Pattern2Data(unique_patterns)
pattern_data <- pattern_list[[1]]
freq_vec <- pattern_list[[2]]
```


