---
title: "Parsing Class"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Normalize <- function(data){
  for (i in 1:dim(data)[1]){
    if (sum(data[i,]) != 0){
      data[i,] <- data[i,]/sum(data[i,])
    }
  }
  return(data)
}
```

```{r}
StackedBar <-function(y, type){
  library(ggplot2)
  library(reshape)
  colnames(y) <- c(0:11)
  rownames(y) <- c(0:11)
  if (type == 1){
    for (i in 1:dim(y)[1]){
      if (i %% 2 == 0){
        y[i,] <- 0
      }
    }
  }
  y <- t(y)
  y <- as.data.frame(y)
  y$ID <- rownames(y)
  y.melt <- melt(y, id.var = 'ID')
  y.melt <- within(y.melt, ID <- factor(ID, 
      c('11','10','9','8','7','6','5','4','3','2','1','0'), 
      ordered = TRUE))
  ggplot(y.melt, aes(x = variable, y = value, fill = ID)) +
      geom_bar(stat = 'identity') +
      #coord_flip() + 
      xlab(ifelse(type == 1,"Initial State","True State")) +
      ylab(ifelse(type == 1,"Transition Probabilities","Classification Probabilities")) +
      theme(legend.title=element_blank())
}
```

```{r}
GetMarginalProb <- function(data_matrix, type){
  HPV <-  matrix(0L, nrow = 2, ncol = 2)
  HPV[1,1] <- sum(data_matrix[1:6,1:6])
  HPV[1,2] <- sum(data_matrix[1:6,7:12])
  HPV[2,2] <- sum(data_matrix[7:12,7:12])
  HPV[2,1] <- sum(data_matrix[7:12,1:6])
  
  Pap <-  matrix(0L, nrow = 3, ncol = 3)
  Pap[1,1] <- sum(data_matrix[c(1,2,7,8),c(1,2,7,8)])
  Pap[1,2] <- sum(data_matrix[c(1,2,7,8),c(3,4,9,10)])
  Pap[1,3] <- sum(data_matrix[c(1,2,7,8),c(5,6,11,12)])
  
  Pap[2,1] <- sum(data_matrix[c(3,4,9,10),c(1,2,7,8)])
  Pap[2,2] <- sum(data_matrix[c(3,4,9,10),c(3,4,9,10)])
  Pap[2,3] <- sum(data_matrix[c(3,4,9,10),c(5,6,11,12)])
  
  Pap[3,1] <- sum(data_matrix[c(5,6,11,12),c(1,2,7,8)])
  Pap[3,2] <- sum(data_matrix[c(5,6,11,12),c(3,4,9,10)])
  Pap[3,3] <- sum(data_matrix[c(5,6,11,12),c(5,6,11,12)])
  
  Copa <-  matrix(0L, nrow = 2, ncol = 2)
  Copa[1,1] <- sum(data_matrix[c(1,3,5,7,9,11),c(1,3,5,7,9,11)])
  Copa[1,2] <- sum(data_matrix[c(1,3,5,7,9,11),c(2,4,6,8,10,12)])
  Copa[2,2] <- sum(data_matrix[c(2,4,6,8,10,12),c(2,4,6,8,10,12)])
  Copa[2,1] <- sum(data_matrix[c(2,4,6,8,10,12),c(1,3,5,7,9,11)])
  
  if (type == 1){
    return(Normalize(HPV))
  } else if (type == 2){
    return(Normalize(Pap))
  } else {
    return(Normalize(Copa))
  }

}
```


```{r}
GetMarginalProb2 <- function(data_matrix, type){
  HPV <-  matrix(0L, nrow = 2, ncol = 2)
  HPV[1,1] <- sum(data_matrix[c(1,3,5),c(1,3,5)])
  HPV[1,2] <- sum(data_matrix[c(1,3,5),c(7,9,11)])
  HPV[2,2] <- sum(data_matrix[c(7,9,11),c(7,9,11)])
  HPV[2,1] <- sum(data_matrix[c(7,9,11),c(1,3,5)])
  
  Pap <-  matrix(0L, nrow = 3, ncol = 3)
  Pap[1,1] <- sum(data_matrix[c(1,7),c(1,7)])
  Pap[1,2] <- sum(data_matrix[c(1,7),c(3,9)])
  Pap[1,3] <- sum(data_matrix[c(1,7),c(5,11)])
  
  Pap[2,1] <- sum(data_matrix[c(3,9),c(1,2,7,8)])
  Pap[2,2] <- sum(data_matrix[c(3,9),c(3,4,9,10)])
  Pap[2,3] <- sum(data_matrix[c(3,9),c(5,11)])
  
  Pap[3,1] <- sum(data_matrix[c(5,11),c(1,7)])
  Pap[3,2] <- sum(data_matrix[c(5,11),c(3,9)])
  Pap[3,3] <- sum(data_matrix[c(5,11),c(5,11)])
  
  Copa <-  matrix(0L, nrow = 2, ncol = 2)
  Copa[1,1] <- sum(data_matrix[c(1,3,5,7,9,11),c(1,3,5,7,9,11)])
  Copa[1,2] <- sum(data_matrix[c(1,3,5,7,9,11),c(2,4,6,8,10,12)])
  Copa[2,2] <- sum(data_matrix[c(2,4,6,8,10,12),c(2,4,6,8,10,12)])
  Copa[2,1] <- sum(data_matrix[c(2,4,6,8,10,12),c(1,3,5,7,9,11)])
  
  if (type == 1){
    return(Normalize(HPV))
  } else if (type == 2){
    return(Normalize(Pap))
  } else {
    return(Normalize(Copa))
  }

}
```

```{r}
#takes in 2x2, 6x6, 5x5 classification matrix and outputs a 60 x 60 full classification matrix 
FullClassificationMatrix <- function(HPV,Pap,Copa){
  l1 <- dim(HPV)[1]
  l2 <- dim(Pap)[1]
  l3 <- dim(Copa)[1]
  row_index <- 0
  col_index <- 0
  
  full_matrix <- matrix(0L, nrow = l1*l2*l3, ncol = l1*l2*l3)
  
  for (i in 1:dim(HPV)[1]){
    for (j in 1:dim(Pap)[1]){
      for (k in 1:dim(Copa)[1]){
        for (i2 in 1:dim(HPV)[2]){
          for (j2 in 1:dim(Pap)[2]){
            for (k2 in 1:dim(Copa)[2]){
              row_index <- ((i-1)*l2*l3) + ((j-1)*l3) + k
              col_index <- ((i2-1)*l2*l3) + ((j2-1)*l3) + k2
              
              full_matrix[row_index,col_index] <-full_matrix[row_index,col_index] + (HPV[i,i2] * Pap[j,j2] * Copa[k,k2])
            }
          }
        }
      }
    }
  }
  return(full_matrix)
}
```

```{r}
setwd("absorbing/better class/class only /")
list_of_names <- list.files()
reps <- length(list_of_names)

class_list <- vector("list", length = reps)
true_class_list <- vector("list", length = reps)


count <- 1
for (name in list_of_names){
  load(name)
  class_list[[count]] <- to_save[[1]]
  true_class_list[[count]] <- to_save[[2]]
  count <- count+1
}
```

```{r}
class_avg <- matrix(0,12,12)
true_class_avg <- matrix(0,12,12)
to_sub <- 0

for (i in 1:reps){
  class_avg <- class_avg + class_list[[i]]
  true_class_avg <- true_class_avg + true_class_list[[i]]
}

reps <- reps - to_sub

class_avg <- Normalize(class_avg/reps)
true_class_avg <- Normalize(true_class_avg/reps)
```

```{r}
HPV_class <- matrix(c(.95,.05,.05,.95),2,2)
Pap_class <- matrix(c(.9,.05,.05,.05,.9,.05,.05,.05,.9),3,3)
Copa_class <- matrix(c(.95,0,.05,1),2,2)
class_matrix <- FullClassificationMatrix(HPV_class,Pap_class,Copa_class)


# round(class_avg,3) 
# round(class_matrix,3)
# round(true_class_avg,3)
# 
# round(class_avg,3)  - round(true_class_avg,3)

StackedBar(class_avg,2)
StackedBar(class_matrix,2)
StackedBar(true_class_avg,2)

```