---
title: "parsing observed"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Normalize <- function(data){
  for (i in 1:dim(data)[1]){
    if (sum(data[i,]) != 0){
      data[i,] <- data[i,]/sum(data[i,])
    }
  }
  return(data)
}
```

```{r}
StackedBar <-function(y, type){
  library(ggplot2)
  library(reshape)
  colnames(y) <- c(0:11)
  rownames(y) <- c(0:11)
  if (type == 1){
    for (i in 1:dim(y)[1]){
      if (i %% 2 == 0){
        y[i,] <- 0
      }
    }
  }
  y <- t(y)
  y <- as.data.frame(y)
  y$ID <- rownames(y)
  y.melt <- melt(y, id.var = 'ID')
  y.melt <- within(y.melt, ID <- factor(ID, 
      c('11','10','9','8','7','6','5','4','3','2','1','0'), 
      ordered = TRUE))
  ggplot(y.melt, aes(x = variable, y = value, fill = ID)) +
      geom_bar(stat = 'identity') +
      #coord_flip() + 
      xlab(ifelse(type == 1,"Initial State","True State")) +
      ylab(ifelse(type == 1,"Transition Probabilities","Classification Probabilities")) +
      theme(legend.title=element_blank())
}
```

```{r}
GetMarginalProb <- function(data_matrix, type){
  HPV <-  matrix(0L, nrow = 2, ncol = 2)
  HPV[1,1] <- sum(data_matrix[1:6,1:6])
  HPV[1,2] <- sum(data_matrix[1:6,7:12])
  HPV[2,2] <- sum(data_matrix[7:12,7:12])
  HPV[2,1] <- sum(data_matrix[7:12,1:6])
  
  Pap <-  matrix(0L, nrow = 3, ncol = 3)
  Pap[1,1] <- sum(data_matrix[c(1,2,7,8),c(1,2,7,8)])
  Pap[1,2] <- sum(data_matrix[c(1,2,7,8),c(3,4,9,10)])
  Pap[1,3] <- sum(data_matrix[c(1,2,7,8),c(5,6,11,12)])
  
  Pap[2,1] <- sum(data_matrix[c(3,4,9,10),c(1,2,7,8)])
  Pap[2,2] <- sum(data_matrix[c(3,4,9,10),c(3,4,9,10)])
  Pap[2,3] <- sum(data_matrix[c(3,4,9,10),c(5,6,11,12)])
  
  Pap[3,1] <- sum(data_matrix[c(5,6,11,12),c(1,2,7,8)])
  Pap[3,2] <- sum(data_matrix[c(5,6,11,12),c(3,4,9,10)])
  Pap[3,3] <- sum(data_matrix[c(5,6,11,12),c(5,6,11,12)])
  
  Copa <-  matrix(0L, nrow = 2, ncol = 2)
  Copa[1,1] <- sum(data_matrix[c(1,3,5,7,9,11),c(1,3,5,7,9,11)])
  Copa[1,2] <- sum(data_matrix[c(1,3,5,7,9,11),c(2,4,6,8,10,12)])
  Copa[2,2] <- sum(data_matrix[c(2,4,6,8,10,12),c(2,4,6,8,10,12)])
  Copa[2,1] <- sum(data_matrix[c(2,4,6,8,10,12),c(1,3,5,7,9,11)])
  
  if (type == 1){
    return(Normalize(HPV))
  } else if (type == 2){
    return(Normalize(Pap))
  } else {
    return(Normalize(Copa))
  }

}
```


```{r}
GetMarginalProb2 <- function(data_matrix, type){
  HPV <-  matrix(0L, nrow = 2, ncol = 2)
  HPV[1,1] <- sum(data_matrix[c(1,3,5),c(1,3,5)])
  HPV[1,2] <- sum(data_matrix[c(1,3,5),c(7,9,11)])
  HPV[2,2] <- sum(data_matrix[c(7,9,11),c(7,9,11)])
  HPV[2,1] <- sum(data_matrix[c(7,9,11),c(1,3,5)])
  
  Pap <-  matrix(0L, nrow = 3, ncol = 3)
  Pap[1,1] <- sum(data_matrix[c(1,7),c(1,7)])
  Pap[1,2] <- sum(data_matrix[c(1,7),c(3,9)])
  Pap[1,3] <- sum(data_matrix[c(1,7),c(5,11)])
  
  Pap[2,1] <- sum(data_matrix[c(3,9),c(1,2,7,8)])
  Pap[2,2] <- sum(data_matrix[c(3,9),c(3,4,9,10)])
  Pap[2,3] <- sum(data_matrix[c(3,9),c(5,11)])
  
  Pap[3,1] <- sum(data_matrix[c(5,11),c(1,7)])
  Pap[3,2] <- sum(data_matrix[c(5,11),c(3,9)])
  Pap[3,3] <- sum(data_matrix[c(5,11),c(5,11)])
  
  Copa <-  matrix(0L, nrow = 2, ncol = 2)
  Copa[1,1] <- sum(data_matrix[c(1,3,5,7,9,11),c(1,3,5,7,9,11)])
  Copa[1,2] <- sum(data_matrix[c(1,3,5,7,9,11),c(2,4,6,8,10,12)])
  Copa[2,2] <- sum(data_matrix[c(2,4,6,8,10,12),c(2,4,6,8,10,12)])
  Copa[2,1] <- sum(data_matrix[c(2,4,6,8,10,12),c(1,3,5,7,9,11)])
  
  if (type == 1){
    return(Normalize(HPV))
  } else if (type == 2){
    return(Normalize(Pap))
  } else {
    return(Normalize(Copa))
  }

}
```

```{r}
setwd("absorbing/better class/observed/")
list_of_names <- list.files()
reps <- length(list_of_names)

init_list <- vector("list", length = reps)
tran_list <- vector("list", length = reps)


count <- 1
for (name in list_of_names){
  load(name)
  init_list[[count]] <- to_save[[1]]
  tran_list[[count]] <- to_save[[2]]
  count <- count+1
}
```

```{r}
init_avg <- numeric(12)
tran_avg <- matrix(0,12,12)
to_sub <- 0
for (i in 1:reps){

  init_avg <- init_avg + init_list[[i]]
  tran_avg <- tran_avg + tran_list[[i]]


}
reps <- reps - to_sub

init_avg <- init_avg/reps
tran_avg <- Normalize(tran_avg/reps)
```

```{r}
round(init_avg,3)
print("")
print("")
colnames(tran_avg) <- c(0:11)
rownames(tran_avg) <- c(0:11)
round(tran_avg,3)
```

```{r}
HPV_mat <- GetMarginalProb(tran_avg,1)
Pap_mat <- GetMarginalProb(tran_avg,2)
Hist_mat <- GetMarginalProb(tran_avg,3)

colnames(HPV_mat) <- c(0:1)
rownames(HPV_mat) <- c(0:1)
colnames(Hist_mat) <- c(0:1)
rownames(Hist_mat) <- c(0:1)
colnames(Pap_mat) <- c(0:2)
rownames(Pap_mat) <- c(0:2)
print("HPV")
round(HPV_mat,3)
print("")
print("Cytology")
round(Pap_mat,3)
print("")
print("Histology")
round(Hist_mat,3)



StackedBar(tran_avg,1)
```

```{r}
GetMarginalProb(tran_avg,1) - GetMarginalProb(tran_old,1)
GetMarginalProb(tran_avg,2) - GetMarginalProb(tran_old,2)
GetMarginalProb(tran_avg,3) - GetMarginalProb(tran_old,3)

StackedBar(tran_avg)
StackedBar(tran_old)
```

```{r}
StackedBar(tran_avg,1)
StackedBar(tran_avg_obs,1)
```