---
title: "18 Marginal"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
total_latent <- numeric(18)

total_latent <- total_latent + (est_init * 3488)
total_latent <- total_latent + ((est_init * 3488) %*% est_tran)
total_latent <- total_latent + ((est_init * 3488) %*% est_tran %*% est_tran)
total_latent <- total_latent + ((est_init * 3488) %*% est_tran %*% est_tran %*% est_tran)
total_latent <- total_latent + ((est_init * 3488) %*% est_tran %*% est_tran %*% est_tran %*% est_tran)
total_latent <- total_latent[1,] * (1 - est_pi)
total_latent[1] <- total_latent[1] + (3488 * 5 * est_pi)

freq_init <- est_init * 3488 * (1 - est_pi)
freq_init[1] <- freq_init[1] + (3488 * est_pi)
freq_tran <- est_tran
freq_class <- est_class


for (i in 1:18){
  freq_tran[i,] <- freq_tran[i,] * total_latent[i]
  freq_class[i,] <- freq_class[i,] * total_latent[i]
}
```

```{r}
library(kableExtra)

init_mat <- freq_init

init_hpv_neg <- sum(init_mat[c(1:6)]) / sum(init_mat)
init_hpv_pos1 <- sum(init_mat[c(7:12)]) / sum(init_mat)
init_hpv_pos2 <- sum(init_mat[c(13:18)]) / sum(init_mat)
init_hpv <- matrix(c(init_hpv_neg, init_hpv_pos1, init_hpv_pos2),1,3)
colnames(init_hpv) <- c("HPV -", "HPV + ", "HPV ++")
kable_styling(kable(init_hpv))

init_cyt_neg <- sum(init_mat[c(1,2,7,8,13,14)]) / sum(init_mat)
init_cyt_pos <- sum(init_mat[c(3,4,9,10,15,16)]) / sum(init_mat)
init_cyt_pos_pos <- sum(init_mat[c(5,6,11,12,17,18)]) / sum(init_mat)
init_cyt <- matrix(c(init_cyt_neg,init_cyt_pos, init_cyt_pos_pos),1,3)
colnames(init_cyt) <- c("Cyt -", "Cyt +", "Cyt ++")
kable_styling(kable(init_cyt))

init_copa_neg <-  sum(init_mat[c(1,3,5,7,9,11,13,15,17)]) / sum(init_mat)
init_copa_pos <- sum(init_mat[c(2,4,6,8,10,12,14,16,18)]) / sum(init_mat)
init_copa <- matrix(c(init_copa_neg, init_copa_pos),1,2)
colnames(init_copa) <- c("Copa -", "Copa +")
kable_styling(kable(init_copa))
```

```{r}
est_mat <- freq_class
neg_hpv <- c(1,2,3,4,5,6)
pos_hpv <- c(7,8,9,10,11,12)
pos_pos_hpv <- c(13,14,15,16,17,18)

hpv_marg <- matrix(0,3,3)
hpv_marg[1,1] <- sum(est_mat[neg_hpv,neg_hpv])
hpv_marg[1,2] <- sum(est_mat[neg_hpv,pos_hpv])
hpv_marg[1,3] <- sum(est_mat[neg_hpv,pos_pos_hpv])
hpv_marg[2,1] <- sum(est_mat[pos_hpv,neg_hpv])
hpv_marg[2,2] <- sum(est_mat[pos_hpv,pos_hpv])
hpv_marg[2,3] <- sum(est_mat[pos_hpv,pos_pos_hpv])
hpv_marg[3,1] <- sum(est_mat[pos_pos_hpv,neg_hpv])
hpv_marg[3,2] <- sum(est_mat[pos_pos_hpv,pos_hpv])
hpv_marg[3,3] <- sum(est_mat[pos_pos_hpv,pos_pos_hpv])
hpv_marg <- hpv_marg / rowSums(hpv_marg)
colnames(hpv_marg) <- c("HPV -", "HPV +", "HPV ++")
rownames(hpv_marg) <- c("HPV -", "HPV +", "HPV ++")
kable_styling(kable(hpv_marg))

neg_hpv_neg_cyt <- c(1,2)
pos_hpv_neg_cyt <- c(7,8)
pos_pos_hpv_neg_cyt <- c(13,14)
hpv_marg <- matrix(0,3,3)
hpv_marg[1,1] <- sum(est_mat[neg_hpv_neg_cyt,neg_hpv])
hpv_marg[1,2] <- sum(est_mat[neg_hpv_neg_cyt,pos_hpv])
hpv_marg[1,3] <- sum(est_mat[neg_hpv_neg_cyt,pos_pos_hpv])
hpv_marg[2,1] <- sum(est_mat[pos_hpv_neg_cyt,neg_hpv])
hpv_marg[2,2] <- sum(est_mat[pos_hpv_neg_cyt,pos_hpv])
hpv_marg[2,3] <- sum(est_mat[pos_hpv_neg_cyt,pos_pos_hpv])
hpv_marg[3,1] <- sum(est_mat[pos_pos_hpv_neg_cyt,neg_hpv])
hpv_marg[3,2] <- sum(est_mat[pos_pos_hpv_neg_cyt,pos_hpv])
hpv_marg[3,3] <- sum(est_mat[pos_pos_hpv_neg_cyt,pos_pos_hpv])
hpv_marg <- hpv_marg / rowSums(hpv_marg)
colnames(hpv_marg) <- c("HPV -", "HPV +", "HPV ++")
rownames(hpv_marg) <- c("HPV - Cyt -", "HPV + Cyt -", "HPV ++ Cyt -")
kable_styling(kable(hpv_marg))

neg_hpv_pos_cyt <- c(3,4)
pos_hpv_pos_cyt <- c(9,10)
pos_pos_hpv_pos_cyt <- c(15,16)
hpv_marg <- matrix(0,3,3)
hpv_marg[1,1] <- sum(est_mat[neg_hpv_pos_cyt,neg_hpv])
hpv_marg[1,2] <- sum(est_mat[neg_hpv_pos_cyt,pos_hpv])
hpv_marg[1,3] <- sum(est_mat[neg_hpv_pos_cyt,pos_pos_hpv])
hpv_marg[2,1] <- sum(est_mat[pos_hpv_pos_cyt,neg_hpv])
hpv_marg[2,2] <- sum(est_mat[pos_hpv_pos_cyt,pos_hpv])
hpv_marg[2,3] <- sum(est_mat[pos_hpv_pos_cyt,pos_pos_hpv])
hpv_marg[3,1] <- sum(est_mat[pos_pos_hpv_pos_cyt,neg_hpv])
hpv_marg[3,2] <- sum(est_mat[pos_pos_hpv_pos_cyt,pos_hpv])
hpv_marg[3,3] <- sum(est_mat[pos_pos_hpv_pos_cyt,pos_pos_hpv])
hpv_marg <- hpv_marg / rowSums(hpv_marg)
colnames(hpv_marg) <- c("HPV -", "HPV +", "HPV ++")
rownames(hpv_marg) <- c("HPV - Cyt +", "HPV + Cyt +", "HPV ++ Cyt +")
kable_styling(kable(hpv_marg))

neg_hpv_pos_pos_cyt <- c(5,6)
pos_hpv_pos_pos_cyt <- c(11,12)
pos_pos_hpv_pos_pos_cyt <- c(17,18)
hpv_marg <- matrix(0,3,3)
hpv_marg[1,1] <- sum(est_mat[neg_hpv_pos_pos_cyt,neg_hpv])
hpv_marg[1,2] <- sum(est_mat[neg_hpv_pos_pos_cyt,pos_hpv])
hpv_marg[1,3] <- sum(est_mat[neg_hpv_pos_pos_cyt,pos_pos_hpv])
hpv_marg[2,1] <- sum(est_mat[pos_hpv_pos_pos_cyt,neg_hpv])
hpv_marg[2,2] <- sum(est_mat[pos_hpv_pos_pos_cyt,pos_hpv])
hpv_marg[2,3] <- sum(est_mat[pos_hpv_pos_pos_cyt,pos_pos_hpv])
hpv_marg[3,1] <- sum(est_mat[pos_pos_hpv_pos_pos_cyt,neg_hpv])
hpv_marg[3,2] <- sum(est_mat[pos_pos_hpv_pos_pos_cyt,pos_hpv])
hpv_marg[3,3] <- sum(est_mat[pos_pos_hpv_pos_pos_cyt,pos_pos_hpv])
hpv_marg <- hpv_marg / rowSums(hpv_marg)
colnames(hpv_marg) <- c("HPV -", "HPV +", "HPV ++")
rownames(hpv_marg) <- c("HPV - Cyt ++", "HPV + Cyt ++", "HPV ++ Cyt ++")
kable_styling(kable(hpv_marg))
# 
neg_hpv_neg_hist <- c(1,3,5)
pos_hpv_neg_hist <- c(7,9,11)
pos_pos_hpv_neg_hist <- c(13,15,17)
hpv_marg <- matrix(0,3,3)
hpv_marg[1,1] <- sum(est_mat[neg_hpv_neg_hist,neg_hpv])
hpv_marg[1,2] <- sum(est_mat[neg_hpv_neg_hist,pos_hpv])
hpv_marg[1,3] <- sum(est_mat[neg_hpv_neg_hist,pos_pos_hpv])
hpv_marg[2,1] <- sum(est_mat[pos_hpv_neg_hist,neg_hpv])
hpv_marg[2,2] <- sum(est_mat[pos_hpv_neg_hist,pos_hpv])
hpv_marg[2,3] <- sum(est_mat[pos_hpv_neg_hist,pos_pos_hpv])
hpv_marg[3,1] <- sum(est_mat[pos_pos_hpv_neg_hist,neg_hpv])
hpv_marg[3,2] <- sum(est_mat[pos_pos_hpv_neg_hist,pos_hpv])
hpv_marg[3,3] <- sum(est_mat[pos_pos_hpv_neg_hist,pos_pos_hpv])
hpv_marg <- hpv_marg / rowSums(hpv_marg)
colnames(hpv_marg) <- c("HPV -", "HPV +", "HPV ++")
rownames(hpv_marg) <- c("HPV - Hist -", "HPV + Hist -", "HPV ++ Hist -")
kable_styling(kable(hpv_marg))
# 
neg_hpv_pos_hist <- c(2,4,6)
pos_hpv_pos_hist <- c(8,10,12)
pos_pos_hpv_pos_hist <- c(14,16,18)
hpv_marg <- matrix(0,3,3)
hpv_marg[1,1] <- sum(est_mat[neg_hpv_pos_hist,neg_hpv])
hpv_marg[1,2] <- sum(est_mat[neg_hpv_pos_hist,pos_hpv])
hpv_marg[1,3] <- sum(est_mat[neg_hpv_pos_hist,pos_pos_hpv])
hpv_marg[2,1] <- sum(est_mat[pos_hpv_pos_hist,neg_hpv])
hpv_marg[2,2] <- sum(est_mat[pos_hpv_pos_hist,pos_hpv])
hpv_marg[2,3] <- sum(est_mat[pos_hpv_pos_hist,pos_pos_hpv])
hpv_marg[3,1] <- sum(est_mat[pos_pos_hpv_pos_hist,neg_hpv])
hpv_marg[3,2] <- sum(est_mat[pos_pos_hpv_pos_hist,pos_hpv])
hpv_marg[3,3] <- sum(est_mat[pos_pos_hpv_pos_hist,pos_pos_hpv])
hpv_marg <- hpv_marg / rowSums(hpv_marg)
colnames(hpv_marg) <- c("HPV -", "HPV +", "HPV ++")
rownames(hpv_marg) <- c("HPV - Hist +", "HPV + Hist +", "HPV ++ Hist +")
kable_styling(kable(hpv_marg))

```

```{r}
neg_cyt <- c(1,2,7,8,13,14)
pos_cyt <- c(3,4,9,10,15,16)
pos_pos_cyt <- c(5,6,11,12,17,18)


cyt_marg <- matrix(0,3,3)
cyt_marg[1,1] <- sum(est_mat[neg_cyt,neg_cyt])
cyt_marg[1,2] <- sum(est_mat[neg_cyt,pos_cyt])
cyt_marg[1,3] <- sum(est_mat[neg_cyt,pos_pos_cyt])
cyt_marg[2,1] <- sum(est_mat[pos_cyt,neg_cyt])
cyt_marg[2,2] <- sum(est_mat[pos_cyt,pos_cyt])
cyt_marg[2,3] <- sum(est_mat[pos_cyt,pos_pos_cyt])
cyt_marg[3,1] <- sum(est_mat[pos_pos_cyt,neg_cyt])
cyt_marg[3,2] <- sum(est_mat[pos_pos_cyt,pos_cyt])
cyt_marg[3,3] <- sum(est_mat[pos_pos_cyt,pos_pos_cyt])

cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("CYT -", "CYT +", "CYT + +")
rownames(cyt_marg) <- c("CYT -", "CYT +", "CYT + +")
kable_styling(kable(cyt_marg))

neg_cyt_neg_hist <- c(1,7,13)
pos_cyt_neg_hist <- c(3,9,15)
pos_pos_cyt_neg_hist <- c(5,11,17)
cyt_marg <- matrix(0,3,3)
cyt_marg[1,1] <- sum(est_mat[neg_cyt_neg_hist,neg_cyt])
cyt_marg[1,2] <- sum(est_mat[neg_cyt_neg_hist,pos_cyt])
cyt_marg[1,3] <- sum(est_mat[neg_cyt_neg_hist,pos_pos_cyt])
cyt_marg[2,1] <- sum(est_mat[pos_cyt_neg_hist,neg_cyt])
cyt_marg[2,2] <- sum(est_mat[pos_cyt_neg_hist,pos_cyt])
cyt_marg[2,3] <- sum(est_mat[pos_cyt_neg_hist,pos_pos_cyt])
cyt_marg[3,1] <- sum(est_mat[pos_pos_cyt_neg_hist,neg_cyt])
cyt_marg[3,2] <- sum(est_mat[pos_pos_cyt_neg_hist,pos_cyt])
cyt_marg[3,3] <- sum(est_mat[pos_pos_cyt_neg_hist,pos_pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("CYT -", "CYT +", "CYT ++")
rownames(cyt_marg) <- c("CYT - Hist -", "CYT + Hist -", "CYT ++ Hist -")
kable_styling(kable(cyt_marg))
# 
neg_cyt_pos_hist <- c(2,8,14)
pos_cyt_pos_hist <- c(4,10,16)
pos_pos_cyt_pos_hist <- c(6,12,18)
cyt_marg <- matrix(0,3,3)
cyt_marg[1,1] <- sum(est_mat[neg_cyt_pos_hist,neg_cyt])
cyt_marg[1,2] <- sum(est_mat[neg_cyt_pos_hist,pos_cyt])
cyt_marg[1,3] <- sum(est_mat[neg_cyt_pos_hist,pos_pos_cyt])
cyt_marg[2,1] <- sum(est_mat[pos_cyt_pos_hist,neg_cyt])
cyt_marg[2,3] <- sum(est_mat[pos_cyt_pos_hist,pos_cyt])
cyt_marg[2,2] <- sum(est_mat[pos_cyt_pos_hist,pos_pos_cyt])
cyt_marg[3,1] <- sum(est_mat[pos_pos_cyt_pos_hist,neg_cyt])
cyt_marg[3,2] <- sum(est_mat[pos_pos_cyt_pos_hist,pos_cyt])
cyt_marg[3,3] <- sum(est_mat[pos_pos_cyt_pos_hist,pos_pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("CYT -", "CYT +", "CYT ++")
rownames(cyt_marg) <- c("CYT - Hist +", "CYT + Hist +", "CYT ++ Hist +")
kable_styling(kable(cyt_marg))
# 
neg_cyt_neg_hpv <- c(1,2)
pos_cyt_neg_hpv <- c(3,4)
pos_pos_cyt_neg_hpv <- c(5,6)
cyt_marg <- matrix(0,3,3)
cyt_marg[1,1] <- sum(est_mat[neg_cyt_neg_hpv,neg_cyt])
cyt_marg[1,2] <- sum(est_mat[neg_cyt_neg_hpv,pos_cyt])
cyt_marg[1,3] <- sum(est_mat[neg_cyt_neg_hpv,pos_pos_cyt])
cyt_marg[2,1] <- sum(est_mat[pos_cyt_neg_hpv,neg_cyt])
cyt_marg[2,2] <- sum(est_mat[pos_cyt_neg_hpv,pos_cyt])
cyt_marg[2,3] <- sum(est_mat[pos_cyt_neg_hpv,pos_pos_cyt])
cyt_marg[3,1] <- sum(est_mat[pos_pos_cyt_neg_hpv,neg_cyt])
cyt_marg[3,2] <- sum(est_mat[pos_pos_cyt_neg_hpv,pos_cyt])
cyt_marg[3,3] <- sum(est_mat[pos_pos_cyt_neg_hpv,pos_pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("Cyt -", "Cyt +", "Cyt ++")
rownames(cyt_marg) <- c("Cyt - HPV -", "Cyt + HPV -", "Cyt ++ HPV -")
kable_styling(kable(cyt_marg))

neg_cyt_pos_hpv <- c(7,8)
pos_cyt_pos_hpv <- c(9,10)
pos_pos_cyt_pos_hpv <- c(11,12)
cyt_marg <- matrix(0,3,3)
cyt_marg[1,1] <- sum(est_mat[neg_cyt_pos_hpv,neg_cyt])
cyt_marg[1,2] <- sum(est_mat[neg_cyt_pos_hpv,pos_cyt])
cyt_marg[1,3] <- sum(est_mat[neg_cyt_pos_hpv,pos_pos_cyt])
cyt_marg[2,1] <- sum(est_mat[pos_cyt_pos_hpv,neg_cyt])
cyt_marg[2,2] <- sum(est_mat[pos_cyt_pos_hpv,pos_cyt])
cyt_marg[2,3] <- sum(est_mat[pos_cyt_pos_hpv,pos_pos_cyt])
cyt_marg[3,1] <- sum(est_mat[pos_pos_cyt_pos_hpv,neg_cyt])
cyt_marg[3,2] <- sum(est_mat[pos_pos_cyt_pos_hpv,pos_cyt])
cyt_marg[3,3] <- sum(est_mat[pos_pos_cyt_pos_hpv,pos_pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("Cyt -", "Cyt +", "Cyt ++")
rownames(cyt_marg) <- c("Cyt - HPV +", "Cyt + HPV +", "Cyt ++ HPV +")
kable_styling(kable(cyt_marg))

neg_cyt_pos_pos_hpv <- c(13,14)
pos_cyt_pos_pos_hpv <- c(15,16)
pos_pos_cyt_pos_pos_hpv <- c(17,18)
cyt_marg <- matrix(0,3,3)
cyt_marg[1,1] <- sum(est_mat[neg_cyt_pos_pos_hpv,neg_cyt])
cyt_marg[1,2] <- sum(est_mat[neg_cyt_pos_pos_hpv,pos_cyt])
cyt_marg[1,3] <- sum(est_mat[neg_cyt_pos_pos_hpv,pos_pos_cyt])
cyt_marg[2,1] <- sum(est_mat[pos_cyt_pos_pos_hpv,neg_cyt])
cyt_marg[2,2] <- sum(est_mat[pos_cyt_pos_pos_hpv,pos_cyt])
cyt_marg[2,3] <- sum(est_mat[pos_cyt_pos_pos_hpv,pos_pos_cyt])
cyt_marg[3,1] <- sum(est_mat[pos_pos_cyt_pos_pos_hpv,neg_cyt])
cyt_marg[3,2] <- sum(est_mat[pos_pos_cyt_pos_pos_hpv,pos_cyt])
cyt_marg[3,3] <- sum(est_mat[pos_pos_cyt_pos_pos_hpv,pos_pos_cyt])
cyt_marg <- cyt_marg / rowSums(cyt_marg)
colnames(cyt_marg) <- c("Cyt -", "Cyt +", "Cyt ++")
rownames(cyt_marg) <- c("Cyt - HPV ++", "Cyt + HPV ++", "Cyt ++ HPV ++")
kable_styling(kable(cyt_marg))


```

```{r}
neg_hist <- c(1,3,5,7,9,11,13,15,17)
pos_hist <- c(2,4,6,8,10,12,14,16,18)

hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_mat[neg_hist,neg_hist])
hist_marg[1,2] <- sum(est_mat[neg_hist,pos_hist])
hist_marg[2,1] <- sum(est_mat[pos_hist,neg_hist])
hist_marg[2,2] <- sum(est_mat[pos_hist,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
names <- c("Hist Neg", "Hist Pos")
colnames(hist_marg) <- names
rownames(hist_marg) <- names
kable_styling(kable(hist_marg))

neg_hist_neg_cyt <- c(1,7,13)
pos_hist_neg_cyt <- c(2,8,14)
hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_mat[neg_hist_neg_cyt,neg_hist])
hist_marg[1,2] <- sum(est_mat[neg_hist_neg_cyt,pos_hist])
hist_marg[2,1] <- sum(est_mat[pos_hist_neg_cyt,neg_hist])
hist_marg[2,2] <- sum(est_mat[pos_hist_neg_cyt,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist -", "Hist +")
rownames(hist_marg) <- c("Hist - Cyt -", "Hist + Cyt -")
kable_styling(kable(hist_marg))
# 
neg_hist_cyt_pos <- c(3,9,15)
pos_hist_cyt_pos <- c(4,10,16)
hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_mat[neg_hist_cyt_pos,neg_hist])
hist_marg[1,2] <- sum(est_mat[neg_hist_cyt_pos,pos_hist])
hist_marg[2,1] <- sum(est_mat[pos_hist_cyt_pos,neg_hist])
hist_marg[2,2] <- sum(est_mat[pos_hist_cyt_pos,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist -", "Hist +")
rownames(hist_marg) <- c("Hist - Cyt +", "Hist + Cyt +")
kable_styling(kable(hist_marg))
# 
neg_hist_cyt_pos_pos <- c(5,11,17)
pos_hist_cyt_pos_pos <- c(6,12,18)
hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_mat[neg_hist_cyt_pos_pos,neg_hist])
hist_marg[1,2] <- sum(est_mat[neg_hist_cyt_pos_pos,pos_hist])
hist_marg[2,1] <- sum(est_mat[pos_hist_cyt_pos_pos,neg_hist])
hist_marg[2,2] <- sum(est_mat[pos_hist_cyt_pos_pos,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist -", "Hist +")
rownames(hist_marg) <- c("Hist - Cyt ++", "Hist + Cyt ++")
kable_styling(kable(hist_marg))
# 
neg_hist_neg_hpv <- c(1,3,5)
pos_hist_neg_hpv <- c(2,4,6)
hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_mat[neg_hist_neg_hpv,neg_hist])
hist_marg[1,2] <- sum(est_mat[neg_hist_neg_hpv,pos_hist])
hist_marg[2,1] <- sum(est_mat[pos_hist_neg_hpv,neg_hist])
hist_marg[2,2] <- sum(est_mat[pos_hist_neg_hpv,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist -", "Hist +")
rownames(hist_marg) <- c("Hist - HPV -", "Hist + HPV -")
kable_styling(kable(hist_marg))
# 
neg_hist_pos_hpv <- c(7,9,11)
pos_hist_pos_hpv <- c(8,10,12)
hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_mat[neg_hist_pos_hpv,neg_hist])
hist_marg[1,2] <- sum(est_mat[neg_hist_pos_hpv,pos_hist])
hist_marg[2,1] <- sum(est_mat[pos_hist_pos_hpv,neg_hist])
hist_marg[2,2] <- sum(est_mat[pos_hist_pos_hpv,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist -", "Hist +")
rownames(hist_marg) <- c("Hist - HPV +", "Hist + HPV +")
kable_styling(kable(hist_marg))
# 
neg_hist_pos_pos_hpv <- c(13,15,17)
pos_hist_pos_pos_hpv <- c(14,16,18)
hist_marg <- matrix(0,2,2)
hist_marg[1,1] <- sum(est_mat[neg_hist_pos_pos_hpv,neg_hist])
hist_marg[1,2] <- sum(est_mat[neg_hist_pos_pos_hpv,pos_hist])
hist_marg[2,1] <- sum(est_mat[pos_hist_pos_pos_hpv,neg_hist])
hist_marg[2,2] <- sum(est_mat[pos_hist_pos_pos_hpv,pos_hist])
hist_marg <- hist_marg / rowSums(hist_marg)
colnames(hist_marg) <- c("Hist -", "Hist +")
rownames(hist_marg) <- c("Hist - HPV ++", "Hist + HPV ++")
kable_styling(kable(hist_marg))

```
