---
title: "ALTS EM"
output: html_document
---

```{r}
library(parallel)
library(foreach)
library(tictoc)
library(doParallel)


ClassHC <- function(){
  class_hc <- matrix(0,18,18)
  for (i in 1:18){
    if ((i-1) %% 2 == 0){
      class_hc[i,i] <- .95
      if ((((i-1) %% 6) %/% 2) == 0){
        class_hc[i,i+2] <- (1 - class_hc[i,i])/2
        class_hc[i,i+4] <- (1 - class_hc[i,i])/2
      }  else if ((((i-1) %% 6) %/% 2) == 1){
        class_hc[i,i-2] <- (1 - class_hc[i,i])/2
        class_hc[i,i+2] <- (1 - class_hc[i,i])/2
      } else if ((((i-1) %% 6) %/% 2) == 2){
        class_hc[i,i-2] <- (1 - class_hc[i,i])/2
        class_hc[i,i-4] <- (1 - class_hc[i,i])/2
      }
    }else {
      class_hc[i,i] <- .95
      if ((((i-1) %% 6) %/% 2) == 0){
        class_hc[i,i-1] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i+1] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i+2] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i+3] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i+4] <- (1 - class_hc[i,i]) / 5
      } else if ((((i-1) %% 6) %/% 2) == 1){
        class_hc[i,i-3] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i-2] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i-1] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i+1] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i+2] <- (1 - class_hc[i,i]) / 5
      } else if ((((i-1) %% 6) %/% 2) == 2){
        class_hc[i,i-5] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i-4] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i-3] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i-2] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i-1] <- (1 - class_hc[i,i]) / 5
      }
    }
  }
  return(class_hc)
}
```

```{r}
IntroduceNoise <- function(parameter, epsilon){
  if (is.vector(parameter)){
    for (i in 1:length(parameter)){
      new_val <- runif(1,parameter[i] - epsilon, parameter[i] + epsilon)
      if (new_val < .01){new_val <- .01}
      else if (new_val > 1){new_val <- 1}
      parameter[i] <- new_val
    }
  } else {
    for (i in 1:dim(parameter)[1]){
      for (j in 1:dim(parameter)[2]){
        if (parameter[i,j] != 0 & parameter[i,j] != 1){
          new_val <- runif(1,parameter[i,j] - epsilon, parameter[i,j] + epsilon)
          if (new_val < .01){new_val <- .01}
          else if (new_val > 1){new_val <- 1}
          parameter[i,j] <- new_val
        }
      }
    }
    
  }
  
  return(parameter)
}
```

```{r}
all_patterns <- GetPatterns(ALTS)
unique_patterns <- as.data.frame(table(all_patterns), stringsAsFactors = F)
ALTS_pattern_list <- Pattern2Data(unique_patterns)

ALTS_pattern <- ALTS_pattern_list[[1]]
freq_vec <- ALTS_pattern_list[[2]]
```

```{r}
init_count <- InitialProb(ALTS_pattern,freq_vec)
init <- init_count/(sum(init_count))
init <- IntroduceNoise(init,.00) 
init <- init/sum(init)

stayer_vec <- PiProb(ALTS_pattern,freq_vec)

tran_count <- TransitionProb(ALTS_pattern,freq_vec,stayer_vec)
tran <- Normalize(tran_count)
tran <- IntroduceNoise(tran,.00)
tran <- Normalize(tran)
tran <- ReduceHist(tran)

class_og <- ClassHC()
class <- class_og
class <- IntroduceNoise(class,.00)
class <- Normalize(class)

# pi_0_og <- runif(1,(stayer_vec %*% freq_vec / sum(freq_vec))[[1]],.3)
pi_0_og <- .06
pi_0 <- pi_0_og


```

```{r}
setwd("..")
# load("parameters.rda")

# init <- IntroduceNoise(to_save[[2]][[1]],.075)
# tran <- IntroduceNoise(to_save[[2]][[2]],.075)
# class <- IntroduceNoise(to_save[[2]][[3]],.075)
# pi_0 <- IntroduceNoise(to_save[[2]][[4]],.07)

class_og <- class
pi_0_og <- pi_0
init_og <- init
tran_og <- tran
```


```{r}
cl <- makeCluster(2)
clusterExport(cl, c("numOfStates", "Classification"))
clusterExport(cl, c("ForwardLinear", "BackwardLinear", "ProdClass"))

tic()
forw <- parApply(cl,ALTS_pattern,1,ForwardLinear, time = 5, init,tran,class)
backw <- parApply(cl,ALTS_pattern,1,FUN = BackwardLinear, time = 1, tran, class)
likelihoodsMover <- unlist(parLapply(cl,forw, CalcLikelihoodMover))
likelihoodsStayers <- parApply(cl,ALTS_pattern,1,FUN = CalcLikelihoodStayer, class, pi_0)
likelihoods <- likelihoodsStayers + ((1 - pi_0) * likelihoodsMover)
old_likelihood <- (log(likelihoods) %*% freq_vec)[1]

init_new <- CalcInitialLin(ALTS_pattern,freq_vec,pi_0,forw,backw,likelihoods)
tran_new <- CalcTransitionLin(ALTS_pattern,tran,class,freq_vec,pi_0,forw,backw,likelihoods)
class_new <- CalcClassificationLin(ALTS_pattern,class,freq_vec,forw,backw,likelihoods,pi_0)
pi_0_new <- CalcStayerLin(ALTS_pattern,init,tran,class,freq_vec,pi_0,likelihoods)

init <- init_new
tran <- tran_new
class <- class_new
pi_0 <- pi_0_new

forw <- parApply(cl,ALTS_pattern,1,ForwardLinear, time = 5, init,tran,class)
backw <- parApply(cl,ALTS_pattern,1,FUN = BackwardLinear, time = 1, tran, class)
likelihoodsMover <- unlist(parLapply(cl,forw, CalcLikelihoodMover))
likelihoodsStayers <- parApply(cl,ALTS_pattern,1,FUN = CalcLikelihoodStayer, class, pi_0)
likelihoods <- likelihoodsStayers + ((1 - pi_0) * likelihoodsMover)
new_likelihood <- (log(likelihoods) %*% freq_vec)[1]

print(new_likelihood - old_likelihood)

while (-(new_likelihood - old_likelihood)/old_likelihood > .000000000001){
  
  old_likelihood <- new_likelihood
  
  init_new <- CalcInitialLin(ALTS_pattern,freq_vec,pi_0,forw,backw,likelihoods)
  tran_new <- CalcTransitionLin(ALTS_pattern,tran,class,freq_vec,pi_0,forw,backw,likelihoods)
  class_new <- CalcClassificationLin(ALTS_pattern,class,freq_vec,forw,backw,likelihoods,pi_0)
  pi_0_new <- CalcStayerLin(ALTS_pattern,init,tran,class,freq_vec,pi_0,likelihoods)
  
  init <- init_new
  tran <- tran_new
  class <- class_new
  pi_0 <- pi_0_new
  
  forw <- parApply(cl,ALTS_pattern,1,ForwardLinear, time = 5, init,tran,class)
  backw <- parApply(cl,ALTS_pattern,1,FUN = BackwardLinear, time = 1, tran, class)
  likelihoodsMover <- unlist(parLapply(cl,forw, CalcLikelihoodMover))
  likelihoodsStayers <- parApply(cl,ALTS_pattern,1,FUN = CalcLikelihoodStayer, class, pi_0)
  likelihoods <- likelihoodsStayers + ((1 - pi_0) * likelihoodsMover)
  new_likelihood <- (log(likelihoods) %*% freq_vec)[1]
  
  print(new_likelihood - old_likelihood)
}

toc()

stopCluster(cl)
```


```{r}
tic()
backw <- apply(ALTS_pattern,1,FUN = BackwardLinear, time = 1, tran, class)
toc()
```
