---
title: "ALTS EM"
output: html_document
---

```{r}
library(parallel)
library(foreach)
library(tictoc)
library(doParallel)


ClassHC <- function(){
  class_hc <- matrix(0,18,18)
  for (i in 1:18){
    if ((i-1) %% 2 == 0){
      class_hc[i,i] <- .95
      if ((((i-1) %% 6) %/% 2) == 0){
        class_hc[i,i+2] <- (1 - class_hc[i,i])/2
        class_hc[i,i+4] <- (1 - class_hc[i,i])/2
      }  else if ((((i-1) %% 6) %/% 2) == 1){
        class_hc[i,i-2] <- (1 - class_hc[i,i])/2
        class_hc[i,i+2] <- (1 - class_hc[i,i])/2
      } else if ((((i-1) %% 6) %/% 2) == 2){
        class_hc[i,i-2] <- (1 - class_hc[i,i])/2
        class_hc[i,i-4] <- (1 - class_hc[i,i])/2
      }
    }else {
      class_hc[i,i] <- .95
      if ((((i-1) %% 6) %/% 2) == 0){
        class_hc[i,i-1] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i+1] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i+2] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i+3] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i+4] <- (1 - class_hc[i,i]) / 5
      } else if ((((i-1) %% 6) %/% 2) == 1){
        class_hc[i,i-3] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i-2] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i-1] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i+1] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i+2] <- (1 - class_hc[i,i]) / 5
      } else if ((((i-1) %% 6) %/% 2) == 2){
        class_hc[i,i-5] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i-4] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i-3] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i-2] <- (1 - class_hc[i,i]) / 5
        class_hc[i,i-1] <- (1 - class_hc[i,i]) / 5
      }
    }
  }
  return(class_hc)
}
```

```{r}
IntroduceNoise <- function(parameter, epsilon){
  if (is.vector(parameter)){
    for (i in 1:length(parameter)){
      new_val <- runif(1,parameter[i] - epsilon, parameter[i] + epsilon)
      if (new_val < .01){new_val <- .01}
      else if (new_val > 1){new_val <- 1}
      parameter[i] <- new_val
    }
  } else {
    for (i in 1:dim(parameter)[1]){
      for (j in 1:dim(parameter)[2]){
        if (parameter[i,j] != 0 & parameter[i,j] != 1){
          new_val <- runif(1,parameter[i,j] - epsilon, parameter[i,j] + epsilon)
          if (new_val < .01){new_val <- .01}
          else if (new_val > 1){new_val <- 1}
          parameter[i,j] <- new_val
        }
      }
    }
    
  }
  
  return(parameter)
}
```

```{r}
all_patterns <- GetPatterns(ALTS)
unique_patterns <- as.data.frame(table(all_patterns), stringsAsFactors = F)
ALTS_pattern_list <- Pattern2Data(unique_patterns)

ALTS_pattern <- ALTS_pattern_list[[1]]
freq_vec <- ALTS_pattern_list[[2]]
```

```{r}
init_count <- InitialProb(ALTS_pattern,freq_vec)
init <- init_count/(sum(init_count))
init <- IntroduceNoise(init,.00) 
init <- init/sum(init)

stayer_vec <- PiProb(ALTS_pattern,freq_vec)

tran_count <- TransitionProb(ALTS_pattern,freq_vec,stayer_vec)
tran <- Normalize(tran_count)
tran <- IntroduceNoise(tran,.00)
tran <- Normalize(tran)
tran <- ReduceHist(tran)

class_og <- ClassHC()
class <- class_og
class <- IntroduceNoise(class,.00)
class <- Normalize(class)

# pi_0_og <- runif(1,(stayer_vec %*% freq_vec / sum(freq_vec))[[1]],.3)
pi_0_og <- .06
pi_0 <- pi_0_og


```

```{r}
setwd("..")
# load("parameters.rda")

# init <- IntroduceNoise(to_save[[2]][[1]],.075)
# tran <- IntroduceNoise(to_save[[2]][[2]],.075)
# class <- IntroduceNoise(to_save[[2]][[3]],.075)
# pi_0 <- IntroduceNoise(to_save[[2]][[4]],.07)

class_og <- class
pi_0_og <- pi_0
init_og <- init
tran_og <- tran
```

```{r}
library(parallel)
library(foreach)
library(tictoc)
library(doParallel)
tic()
no_cores <- 4
cl <- makeCluster(no_cores)

clusterExport(cl, c("numOfStates", "GetAllPossibilitiesForw", "Classification"))
clusterExport(cl, c("GetAllPossibilitiesBackw"))
clusterExport(cl, c("ForwardIterFull", "BackwardIterFull", "CalcProdInd"))

forw <- parApply(cl, ALTS_pattern,1,ForwardIterFull, time = 5, init,tran,class)
backw <- parApply(cl, ALTS_pattern,1,FUN = BackwardIterFull, time = 1, tran, class)
likelihoods <- parApply(cl, ALTS_pattern,1,FUN = CalcIndLikelihood, init, tran, class,pi_0)


old_likelihood <- (log(likelihoods) %*% freq_vec)[1]

init_new <- CalcInitialPattern(ALTS_pattern,freq_vec,pi_0,forw,backw,likelihoods)
tran_new <- CalcTransitionPattern(ALTS_pattern,tran,class,freq_vec,pi_0, forw, backw, likelihoods)
class_new <- CalcClassificationPattern(ALTS_pattern,class,freq_vec, forw, backw, likelihoods,pi_0)
# class_new <- CalcClassificationPatternNoStayer(ALTS_pattern,class,freq_vec, forw, backw, likelihoods)
pi_0_new <- CalcStayer(ALTS_pattern,init,tran,class,freq_vec,pi_0)


init <- init_new
tran <- tran_new
class <- class_new
pi_0 <- pi_0_new


likelihoods_new <- parApply(cl, ALTS_pattern,1,FUN = CalcIndLikelihood, init, tran, class,pi_0)

new_likelihood <- (log(likelihoods_new) %*% freq_vec)[1]
print(new_likelihood - old_likelihood)

while ((new_likelihood - old_likelihood) > .001){
  forw <- parApply(cl, ALTS_pattern,1,ForwardIterFull, time = 5, init,tran,class)
  backw <- parApply(cl, ALTS_pattern,1,FUN = BackwardIterFull, time = 1, tran, class)
  likelihoods <- likelihoods_new

  old_likelihood <- new_likelihood

  init_new <- CalcInitialPattern(ALTS_pattern,freq_vec,pi_0,forw,backw,likelihoods)
  tran_new <- CalcTransitionPattern(ALTS_pattern,tran,class,freq_vec,pi_0, forw, backw, likelihoods)
  class_new <- CalcClassificationPattern(ALTS_pattern,class,freq_vec, forw, backw, likelihoods,pi_0)
  # class_new <- CalcClassificationPatternNoStayer(ALTS_pattern,class,freq_vec, forw, backw, likelihoods)
  pi_0_new <- CalcStayer(ALTS_pattern,init,tran,class,freq_vec,pi_0)


  init <- init_new
  tran <- tran_new
  class <- class_new
  pi_0 <- pi_0_new

  likelihoods_new <- parApply(cl, ALTS_pattern,1,FUN = CalcIndLikelihood, init, tran, class,pi_0)

  new_likelihood <- (log(likelihoods_new) %*% freq_vec)[1]
  print(new_likelihood - old_likelihood)
}


stopCluster(cl)

```







```{r}
CalcTransitionPatternAltered <- function(data, tran,class,freq_vec, pi_0, forw, backw, likelihoods, first_val, second_val){
  
  first_x_ind <- 1
  first_y_ind <- 2
  second_x_ind <- 1
  second_y_ind <- 4
  # forw <- apply(data,1,ForwardIterFull, time = 4, init,tran,class)
  # backw <- apply(data,1,FUN = BackwardIterFull, time = 2, tran, class)
  # likelihoods <- apply(data,1,FUN = CalcIndLikelihood, init, tran, class,pi_0)
  
  k <- numOfStates(data)
  tran_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
  possible_initial_states <- c(1,3,5,7,9,11,13,15,17)
  possible_initial_states_copa <- c(2,4,6,8,10,12,14,16,18)
  
  for (ind in 1:dim(data)[1]){
    forward <- forw[[ind]]
    backward <- backw[[ind]]
    denom <- likelihoods[[ind]]
    for (time in 2:dim(data)[2]){
      tran_matrix_current <- matrix(0L, nrow = length(k), ncol = length(k))
      possible_x <- unique(GetAllPossibilitiesBackw(data[ind,,], time)[1,])
      
      if (time != 5){current_backw_length <- dim(GetAllPossibilitiesBackw(data[ind,,],time+1))[2]} 
      else {current_backw_length <- 1}
      
      current_forw_length <- dim(GetAllPossibilitiesForw(data[ind,,],time-1))[2]
      
      
      forward_sum <- numeric(length(k))
      backward_sum <- numeric(length(k))
      
      
      for (u in 1:current_forw_length){
        forward_sum <- forward_sum + forward[[u]][[time-1]]
      }
      
      
      if (time == dim(data)[2]){
        backward_sum <- rep(1, length(k))
      } else {
        for (v in 1:current_backw_length){
          backward_sum <- backward_sum + backward[[v]][[time]]
        }
      }
      
      for(gX in possible_x){ 
        
        for (initial_state in possible_initial_states){
          if (initial_state < 6){possible_new_states <- c(1:12)}
          else {possible_new_states <- c(1:6,13:18)}
          
          for(new_state in possible_new_states){
            
            num <- forward_sum[[initial_state]] * backward_sum[[new_state]] * tran[initial_state,new_state] * Classification(gX,new_state-1,class) * (1 - pi_0)
            if(denom != 0){
              tran_matrix_current[initial_state,new_state] <- tran_matrix_current[initial_state,new_state] + (num/denom)
            } 
          }
        }
        
        for (initial_state in possible_initial_states_copa){
          if (initial_state < 7){possible_new_states <- c(2,4,6,8,10,12)}
          else {possible_new_states <- c(2,4,6,14,16,18)}
          
          for(new_state in possible_new_states){
            
            num <- forward_sum[[initial_state]] * backward_sum[[new_state]] * tran[initial_state,new_state] * Classification(gX,new_state-1,class) * (1 - pi_0)
            if(denom != 0){
              tran_matrix_current[initial_state,new_state] <- tran_matrix_current[initial_state,new_state] + (num/denom)
            } 
          }
        }
        
        
      }
      tran_matrix <- tran_matrix + ((tran_matrix_current) * freq_vec[ind])
    }
  }
  
  tran_matrix <- Normalize(tran_matrix)
  tran_matrix[first_x_ind,first_y_ind] <- 0
  tran_matrix[second_x_ind,second_y_ind] <- 0
  tran_matrix <- Normalize(tran_matrix)
  
  almost_one <- 1 - (first_val + second_val)
  tran_matrix[first_x_ind,] <- tran_matrix[first_x_ind,] * almost_one
  tran_matrix[first_x_ind,first_y_ind] <- first_val
  tran_matrix[second_x_ind,second_y_ind] <- second_val
  return(Normalize(tran_matrix))
}

```

```{r}
CalcInitialPatternAltered <- function(data,freq_vec, pi_0, forw, backw, likelihoods, first_val, second_val, third_val){
  first_ind <- 2
  second_ind <- 7
  third_ind <- 9
  k <- numOfStates(data)
  prob_list <- numeric(length(k))
  
  # forw <- apply(data,1,ForwardIterFull, time = 1, init,tran,class)
  # backw <- apply(data,1,FUN = BackwardIterFull, time = 1, tran, class)
  # likelihoods <- apply(data,1,FUN = CalcIndLikelihood, init, tran, class,pi_0)
  
 
  
  for (i in 1:dim(data)[1]){
    forward <- forw[[i]]
    backward <- backw[[i]]
    ind_likelihood <- likelihoods[[i]]
    
    forward_sum <- numeric(length(k))
    backward_sum <- numeric(length(k))
    
    forw_length <- dim(GetAllPossibilitiesForw(data[i,,],1))[2]
    
    for (k in 1:forw_length){
     forward_sum <- forward_sum + forward[[k]][[1]] 
    }
    for (k in 1:length(backward)){
     backward_sum <- backward_sum + backward[[k]][[1]] 
    }
    
    mover <- forward_sum * backward_sum * (1 - pi_0) / ind_likelihood
    prob_list <- prob_list + (mover * freq_vec[i])
  }
  init <- prob_list/sum(prob_list)
  
  init[first_ind] <- 0
  init[second_ind] <- 0
  init[third_ind] <- 0
  init <- init/sum(init)
  
  almost_one <- 1 - (first_val + second_val + third_val)
  init <- init * almost_one
  init[first_ind] <- first_val
  init[second_ind] <- second_val
  init[third_ind] <- third_val
  
  return(init)
} 
```

```{r}
CalcClassificationPatternNoStayerAltered <- function(data,class, freq_vec, forw, backw, likelihoods, true_ind, obs_ind, adj_val){
  k <- numOfStates(data)
  num_matrix_full <- matrix(0L, nrow = length(k), ncol = length(k))
  # forw <- apply(data,1,ForwardIterFull, time = 5, init,tran,class)
  # backw <- apply(data,1,FUN = BackwardIterFull, time = 1, tran, class)
  # likelihoods <- apply(data,1,FUN = CalcIndLikelihood, init, tran, class,pi_0)
  for (ind in 1:dim(data)[1]){
    
    forward <- forw[[ind]]
    backward <- backw[[ind]]
    
    for(time in 1:dim(data)[2]){
      num_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
      
      if (time != dim(data)[2]){current_backw_length <- dim(GetAllPossibilitiesBackw(data[ind,,],time+1))[2]} 
      else {current_backw_length <- 1}
      current_forw_length <- dim(GetAllPossibilitiesForw(data[ind,,],time))[2]
      individual_likelihood <- likelihoods[[ind]]
      
      beggining_forw <- GetAllPossibilitiesForw(data[ind,,],time)
      if (time != dim(data)[2]){
        ending_backw <- GetAllPossibilitiesBackw(data[ind,,],(time+1))
      }
      x_vals <- unique(beggining_forw[time,])
      
      backward_sum <- numeric(length(numOfStates()))
      for (v in 1:current_backw_length){
        backward_sum <- backward_sum + backward[[v]][[time]]
      }
      for (u in 1:current_forw_length){
        x_val <- beggining_forw[time,u]
        if (!is.na(x_val)){
          mover <- (forward[[u]][[time]]*backward_sum / individual_likelihood)
          
          for (y_state in 1:length(k)){   
            num_matrix[y_state,x_val + 1] <- num_matrix[y_state, x_val+1] + mover[y_state]
          }
        }
      }
      
      
      #Normalization for partial
      if (sum(num_matrix) != 0){
        num_matrix <- num_matrix/sum(num_matrix)
      }
      num_matrix_full <- num_matrix_full + (num_matrix * freq_vec[ind])
      
    }
  }
  
  class <- Normalize(num_matrix_full)
  
  
  new_val <- (1 - class[true_ind,obs_ind])/(1 - adj_val) * adj_val
  class[true_ind, obs_ind] <- new_val
  class <- Normalize(class)
  return(class)
}
```       


