---
title: "EDA 18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
StateCalculator <- function(val1, val2, val3){
  if (!is.na(val1) & !is.na(val2) & !is.na(val3)){
    return(c(6 * val1 + 2 * val2 + val3))
  } else if (!is.na(val1) & !is.na(val2) & is.na(val3)){
    if(val1 == 0 & val2 == 0){
      return(0)
    }
    return(c(6 * val1 + 2 * val2, 6 * val1 + 2 * val2 + 1))
  } else if (!is.na(val1) & is.na(val2) & !is.na(val3)){
    return(c(6 * val1 + val3, 6 * val1 + 2 + val3, 6 * val1 + 4 + val3))
  } else if (is.na(val1) & !is.na(val2) & !is.na(val3)){
    return(c(2 * val2 + val3, 6 + 2 * val2 + val3, 12 + 2 * val2 + val3))
  } else if (!is.na(val1) & is.na(val2) & is.na(val3)){
    return(c(6 * val1, 6 * val1 + 1, 6 * val1 + 2, 6 * val1 + 3, 6 * val1 + 4, 6 * val1 + 5))
  }else if (is.na(val1) & !is.na(val2) & is.na(val3)){
    return(c(2 * val2, 2 * val2 + 1, 2 * val2 + 6, 2 * val2 + 7, 2 * val2 + 12, 2 * val2 + 13))
  }else if (is.na(val1) & is.na(val2) & !is.na(val3)){
    return(c(val3, val3 + 2, val3 + 4, val3 + 6, val3 + 8, val3 + 10, val3 + 12, val3 + 14, val3 + 16))
  } else {
    return(NA)
  }
}

```

```{r}

copa_pos <- numeric(9)
copa_pos1 <- numeric(9)
copa_pos2 <- numeric(9)
copa_pos3 <- numeric(9)
copa_pos4 <- numeric(9)
copa_pos5 <- numeric(9)

copa_neg <- numeric(9)

for (i in 1:dim(copa)[1]){
  for (j in 1:dim(copa)[2]){
    if (!is.na(copa[i,j])){
      if (copa[i,j] == 1){
        if (!is.na(hpv_pers[i,j,2])){
          vals <- c(StateCalculator(hpv_pers[i,j,1], cyt[i,j], copa[i,j]), StateCalculator(hpv_pers[i,j,2], cyt[i,j], copa[i,j]))
        } else {
          vals <- StateCalculator(hpv_pers[i,j,1], cyt[i,j], copa[i,j])
        }
        
        for (val in vals){
          copa_pos[(val%/% 2 + 1)] <- copa_pos[(val%/% 2 + 1)] + (1 / length(vals))
          
          if (j == 1){
            copa_pos1[(val%/% 2 + 1)] <- copa_pos1[(val%/% 2 + 1)] + (1 / length(vals))
          } else if (j == 2){
            copa_pos2[(val%/% 2 + 1)] <- copa_pos2[(val%/% 2 + 1)] + (1 / length(vals))
          } else if (j == 3){
            copa_pos3[(val%/% 2 + 1)] <- copa_pos3[(val%/% 2 + 1)] + (1 / length(vals))
          } else if (j == 4){
            copa_pos4[(val%/% 2 + 1)] <- copa_pos4[(val%/% 2 + 1)] + (1 / length(vals))
          } else if (j == 5){
            copa_pos5[(val%/% 2 + 1)] <- copa_pos5[(val%/% 2 + 1)] + (1 / length(vals))
          }
          
        }
      } else {
        if (!is.na(hpv_pers[i,j,2])){
          vals <- c(StateCalculator(hpv_pers[i,j,1], cyt[i,j], copa[i,j]), StateCalculator(hpv_pers[i,j,2], cyt[i,j], copa[i,j]))
        } else {
          vals <- StateCalculator(hpv_pers[i,j,1], cyt[i,j], copa[i,j])
        }
        
        for (val in vals){
          copa_neg[(val%/% 2 + 1)] <- copa_neg[(val%/% 2 + 1)] + (1 / length(vals))
        }
      }
    }
  }
}

library(ggplot2)
library(reshape2)

copa_num <- colSums(copa,na.rm = T)
total_copa_num <- colSums(!is.na(copa))
copa_prop <- colSums(copa,na.rm = T) / colSums(!is.na(copa))

copa_df <- data.frame("Positive" = copa_num, "Negative" = total_copa_num - copa_num, "time" = c(1:5))
copa_df <- melt(copa_df, id.var = "time")
copa_df$prop <- round(copa_prop,3)  / (1/2000)

copa_df_total <- data.frame("states" = seq(1,17,2), "Positive" = copa_pos, "Negative" = copa_neg)
copa_df_total <- melt(copa_df_total, id.vars = "states")
copa_df_total$prop <- (copa_pos / (copa_pos + copa_neg)) * 1250

copa_df_states <- data.frame("states" = seq(1,17,2), "Fifth" = copa_pos5, "Fourth" = copa_pos4, "Third" = copa_pos3, "Second" = copa_pos2, "First" = copa_pos1)
copa_df_states <- melt(copa_df_states, id.var = "states")

copa_df_time <- data.frame("time" = c(rep(1,9),rep(2,9),rep(3,9),rep(4,9),rep(5,9)), "states" =   rep(c("1","3","5","7","9","11","13","15","17"),5))
copa_df_time$value <- c(copa_pos1/sum(copa_pos1),copa_pos2/sum(copa_pos2),copa_pos3/sum(copa_pos3),copa_pos4/sum(copa_pos4),copa_pos5/sum(copa_pos5))
copa_df_time$states <- factor(copa_df_time$states, levels = c("1","3","5","7","9","11","13","15","17"))


ggplot(copa_df,aes(x = time, y = value, fill = variable)) + geom_bar(stat = "identity", position = "dodge") + 
  geom_line(aes(x = time, y = prop)) +
  labs(fill ="Colpo Results") + 
  scale_y_continuous(sec.axis = sec_axis(~ . * (1/2000), name = "Proportion of Positive")) +
  labs(title = "Observed Colpo Results Per Time", x = "Time", y = "Number of Colpo Tests") + 
  theme_minimal()

ggplot(copa_df_total, aes(x = states, y = value, fill = variable)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  scale_x_continuous(breaks=seq(1,17,2), labels = c("HPV -\n Cyt -","HPV -\n Cyt +","HPV -\n Cyt ++","HPV +\n Cyt -","HPV +\n Cyt +","HPV +\n Cyt ++","HPV ++\n Cyt -","HPV ++\n Cyt +","HPV ++\n Cyt ++")) +
  labs(fill = "Observed Colpo Results", y = "Number of Colpos", x = "State", title = "Observed Colpos Results Per State") + 
  geom_line(aes(x = states, y = prop)) + 
  scale_y_continuous(sec.axis = sec_axis(~ . * (1/1250), name = "Proportion of Positive")) +
  theme_minimal()

ggplot(copa_df_states, aes(x = states, y = value, fill = variable)) + 
  geom_bar(stat = "identity", position = "fill") + 
  scale_x_continuous(breaks=seq(1,17,2), labels = c("HPV -\n Cyt -","HPV -\n Cyt +","HPV -\n Cyt ++","HPV +\n Cyt -","HPV +\n Cyt +","HPV +\n Cyt ++","HPV ++\n Cyt -","HPV ++\n Cyt +","HPV ++\n Cyt ++")) + 
  labs(fill ="Timepoint", x = "States", y = "Percentage", title = "Percentage of Colpo Positive Per State by Time") + 
  theme_minimal()

ggplot(copa_df_time, aes(x = time, y = value, fill = states)) + 
  labs(fill ="States", x = "Time", y = "Percentage", title = "Percentage of Colpo Positive Observed Per Time by State") + 
  geom_bar(stat = "identity", position = "fill") + 
  theme_minimal()
```