---
title: "ALTS EM"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
StateCalculator <- function(val1, val2, val3){
  if (!is.na(val1) & !is.na(val2) & !is.na(val3)){
    return(c(6 * val1 + 2 * val2 + val3))
  } else if (!is.na(val1) & !is.na(val2) & is.na(val3)){
    # if(val1 == 0 & val2 == 0){
    #   return(0)
    # }
    return(c(6 * val1 + 2 * val2, 6 * val1 + 2 * val2 + 1))
  } else if (!is.na(val1) & is.na(val2) & !is.na(val3)){
    return(c(6 * val1 + val3, 6 * val1 + 2 + val3, 6 * val1 + 4 + val3))
  } else if (is.na(val1) & !is.na(val2) & !is.na(val3)){
    return(c(2 * val2 + val3, 6 + 2 * val2 + val3, 12 + 2 * val2 + val3))
  } else if (!is.na(val1) & is.na(val2) & is.na(val3)){
    return(c(6 * val1, 6 * val1 + 1, 6 * val1 + 2, 6 * val1 + 3, 6 * val1 + 4, 6 * val1 + 5))
  }else if (is.na(val1) & !is.na(val2) & is.na(val3)){
    return(c(2 * val2, 2 * val2 + 1, 2 * val2 + 6, 2 * val2 + 7, 2 * val2 + 12, 2 * val2 + 13))
  }else if (is.na(val1) & is.na(val2) & !is.na(val3)){
    return(c(val3, val3 + 2, val3 + 4, val3 + 6, val3 + 8, val3 + 10, val3 + 12, val3 + 14, val3 + 16))
  } else {
    return(NA)
  }
}

```

```{r}
Normalize <- function(data){
  for (i in 1:dim(data)[1]){
    if (sum(data[i,],na.rm = TRUE) != 0){
      data[i,] <- data[i,]/sum(data[i,])
    }
  }
  return(data)
}
```

```{r}
Classification <- function(x_val,y_val,class){
  if (is.na(x_val[1])){
    return(1)
  } else {
    rs <- 0
    for (val in x_val){
      if (is.na(val)){
        return(rs)
      } else {
        rs <- rs + class[[y_val + 1,val + 1]]
      }
    }
  }
  return(rs)
}
```

```{r}
numOfStates <- function(data,type){
  if (missing(type)){
    return(c(0:17))
  }
}
```

```{r}
GetPatterns <- function(states){
  library(plyr)
  options(scipen = 999)
  vals <- rep(NaN,dim(states)[1])
  for (i in 1:dim(states)[1]){
    val <- ""
    for(j in 1:dim(states)[2]){
      for(k in 1:dim(states)[3]){
        if (!is.na(states[i,j,k])){
          states_val <- states[i,j,k] 
          } else {
            states_val <- NA
          }
          val <- paste0(val, states_val,",")
        }
      }
    val <- substr(val, 1, nchar(val)-1)
    vals[i] <- val
  }
  return(vals)
}
```

```{r}
Pattern2Data <- function(unique_patterns){
  time_length <- 5
  n <- length(unique_patterns[[1]])
  partial_len <- 12
  freq_vec <- numeric(n)
  state_array <- array(0, dim = c(n,time_length,partial_len))
  for (i in 1:n){
    freq_vec[i] <- unique_patterns$Freq[[i]]
    pattern <- unique_patterns$all_patterns[[i]]

    pattern <- strsplit(pattern, split = ",")[[1]]
    for (time in 1:time_length){
      state_array[i,time,] <- suppressWarnings(as.integer(pattern[(((time-1)*partial_len)+1):(time*partial_len)]))
    }
  }

  return(list(state_array, freq_vec))
}

```

```{r}
InitialProbTrue <- function(data, stayer_vec){
  init <- numeric(length(numOfStates(data)))
  for (i in 1:dim(data)[1]){
    if (stayer_vec[i] == 0 & !is.na(data[i,1])){
      init[data[i,1]+1] <- init[data[i,1]+1] + 1
    }
  }
  return(init)
}
```

```{r}
InitialProb <- function(data, freq_vec, stayer_vec = rep(0,length(freq_vec))){
  init <- numeric(length(numOfStates(data)))
  for (i in 1:dim(data)[1]){
    if (stayer_vec[i] == 0){
      num_of_parts <- sum(!is.na(data[i,1,]))
      if (!is.na(data[i,1,1])){
        for (j in data[i,1,]){
          if (!is.na(j)){
            init[j+1] <- init[j+1] + freq_vec[i]/num_of_parts
          }
          
        }
      }
    }
  }
  return(init)
}
```

```{r}
PiProb <- function(data, freq_vec){
  stayer_vec <- numeric(length(freq_vec))
  
  for (i in 1:dim(data)[1]){
    to_add <- 1
    for (j in 1:dim(data)[2]){
      if (!(0 %in% data[i,j,])){
        to_add <- 0
      }
    }
    stayer_vec[i] <- to_add
  }
  return(stayer_vec)
}
```

```{r}
ReduceHist <- function(tran){
  for (i in 1:dim(tran)[1]){
    for (j in 1:dim(tran)[2]){
      if (i %% 2 == 1 & j %% 2 == 0){
        if (i < 7){
          tran[i,j] <- tran[i,j] / 1000
        } else if (i < 13){
          tran[i,j] <- tran[i,j] / 100
        } else {
          tran[i,j] <- tran[i,j] / 10
        }
        
        if (j < 7){
          tran[i,j] <- tran[i,j] / 1000
        } else if (j < 13) {
          tran[i,j] <- tran[i,j] / 100
        } else {
          tran[i,j] <- tran[i,j] / 10
        }
        
      }
    }
  }
  return(Normalize(tran))
}

```

```{r}
TransitionProb <- function(data, freq_vec, stayer_vec = rep(0,length(freq_vec))){
  k <- length(numOfStates(data))
  tran <- matrix(0,k,k)
  for (i in 1:dim(data)[1]){
    if (stayer_vec[i] == 0){
      for (j in 2:dim(data)[2]){
        if (!is.na(data[i,j-1,1]) & !is.na(data[i,j,1])){
          num_of_parts <- sum(!is.na(data[i,j-1,])) * sum(!is.na(data[i,j,]))
          for (k1 in data[i,j-1,]){
            for (k2 in data[i,j,]){
              if (!is.na(k1) & !is.na(k2)){
                tran[k1+1,k2+1] <- tran[k1+1,k2+1] + freq_vec[i]/num_of_parts
              }
              
            }
          }
        }
      }
    }
  }
  for (i in 1:dim(tran)[1]){
    if (i %% 2 == 0){
      for (j in 1:dim(tran)[2]){
        if (j %% 2 == 1){
          tran[i,j] <- 0
        }
      }
    }
  }
  
  tran[1:6,13:18] <- 0
  tran[7:18,7:12] <- 0
  return(tran)
}
```

```{r}
TransitionProbTrue <- function(data,stayer_vec){
  k <- length(numOfStates(data))
  tran <- matrix(0,k,k)
  for (i in 1:dim(data)[1]){
    if (stayer_vec[i] == 0){
      for (j in 2:dim(data)[2]){
        if (!is.na(data[i,j-1]) & !is.na(data[i,j])){
          tran[data[i,j-1]+1,data[i,j]+1] <- tran[data[i,j-1]+1,data[i,j]+1] + 1
        }
      }
    }
  }
  return(tran)
}
```

```{r}
ForwardLinear <- function(data,time,init,tran,class){
  k <- numOfStates()
  
  alpha_matrix<-vector("list",time)
  alpha_i <- numeric(length(k))
  num_of_part_vec <- numeric(dim(data)[1])
  
  for (i in 1:time){
    num_of_part_vec[i] <- sum(!is.na(data[i,]))
    if (num_of_part_vec[i] == 0){num_of_part_vec[i] = 1}
    alpha_matrix[[i]] <- vector("list",num_of_part_vec[i])
    for (j in 1:num_of_part_vec[i]){
      alpha_matrix[[i]][[j]] <- alpha_i
    }
  }
  
  partial_vals <- data[1,][!is.na(data[1,])]
  for (i in 1:num_of_part_vec[1]){
    for (j in 1:length(k)){
      alpha_matrix[[1]][[i]][j] <- init[j] * Classification(partial_vals[i],k[j],class)
    }
  }
    
  if (time > 1){
    for (i in 2:time){
      partial_vals <- data[i,][!is.na(data[i,])]
      
      if (num_of_part_vec[i - 1] == 1){
        old_alpha <- alpha_matrix[[i-1]][[1]]
      } else {
        old_alpha <- numeric(length(k))
        for (j in 1:num_of_part_vec[i-1]){
          old_alpha <- old_alpha + alpha_matrix[[i-1]][[j]]
        }
      }
      
      for (j in 1:num_of_part_vec[i]){
        for (l in 1:length(k)){
          alpha_matrix[[i]][[j]][l] <- (old_alpha %*% tran[,l]) *  Classification(partial_vals[j],k[l],class)
        }
      }
    }
  }
  
  return(alpha_matrix)
}
```

```{r}
BackwardLinear <- function(data,time,tran,class){
  k <- numOfStates()
  
  beta_i <- numeric(length(k))
  misclass_vector <- numeric(length(k))
  beta_matrix<-vector("list",dim(data)[1])
  
  
  for (i in 1:(dim(data)[1] - 1)){
    beta_matrix[[i]] <- beta_i
  }
  
  for (i in 1:length(k)){
    beta_matrix[[dim(data)[1]]][i] <- 1
  }
  
  if (time != dim(data)[1]) {
    for (i in (dim(data)[1]-1):time){
      partial_vals <- data[i+1,][!is.na(data[i+1,])]
  
      new_beta <- beta_matrix[[i+1]]
        
      for (l in 1:length(k)){
        misclass_vector[l] <- Classification(partial_vals,k[l],class)
      }
      
      for (j in 1:length(k)){
        beta_matrix[[i]][j] <- sum(new_beta * tran[j,] * misclass_vector)
      }
        
    }
  }
    
  
  return(beta_matrix)
}
```

```{r}
# BackwardLinear <- function(data,time,tran,class){
#   k <- numOfStates()
#   
#   beta_i <- numeric(length(k))
#   misclass_vector <- numeric(length(k))
#   beta_matrix<-vector("list",dim(data)[1])
#   num_of_part_vec <- numeric(dim(data)[1])
#   
#   
#   for (i in 1:dim(data)[1]){
#     num_of_part_vec[i] <- sum(!is.na(data[i,]))
#     if (num_of_part_vec[i] == 0){num_of_part_vec[i] = 1}
#   }
#   
#   
#   for (i in 1:(dim(data)[1] - 1)){
#     beta_matrix[[i]] <- vector("list",num_of_part_vec[i + 1])
#     for (j in 1:num_of_part_vec[i + 1]){
#       beta_matrix[[i]][[j]] <- beta_i
#     }
#   }
#   
#   beta_matrix[[dim(data)[1]]] <- vector("list",1)
#   for (i in 1:length(k)){
#     beta_matrix[[dim(data)[1]]][[1]][i] <- 1
#   }
#   
#   if (time != dim(data)[1]) {
#     for (i in (dim(data)[1]-1):time){
#       partial_vals <- data[i+1,][!is.na(data[i+1,])]
#   
#       new_beta <- numeric(length(k))
#       for (m in 1:length(beta_matrix[[i+1]])){
#         new_beta <- new_beta + beta_matrix[[i+1]][[m]]
#       }
#       
#       
#       for (m in 1:num_of_part_vec[i+1]){
#         
#         for (l in 1:length(k)){
#           misclass_vector[l] <- Classification(partial_vals[m],k[l],class)
#         }
#         
#         for (j in 1:length(k)){
#           beta_matrix[[i]][[m]][j] <- sum(new_beta * tran[j,] * misclass_vector)
#         }
#         
#       }
#     }
#   }
#     
#   
#   return(beta_matrix)
# }
```

```{r}
ProdClass <- function(data,class){
  return(Classification(data[1,],0,class) * Classification(data[2,],0,class)* Classification(data[3,],0,class)* Classification(data[4,],0,class)* Classification(data[5,],0,class))
}
```

```{r}
CalcLikelihoodMover <- function(forw){
  
  rs <- 0 
  for (i in 1:length(forw[[5]])){
    rs <- rs + forw[[5]][[i]]
  }
  
  return(sum(rs)[[1]])
}


```

```{r}
CalcLikelihoodStayer <- function(data, class, pi){
  return((pi * ProdClass(data,class)))
}
```

```{r}
CalcStayerLin <- function(data,init,tran,class,freq_vec,pi_0, likelihoods){
  
  CalcStayerHelper <- function(data,likelihood){
    return((pi_0 * ProdClass(data,class) / likelihood))
  }
  
  
  pi_vec <- numeric(dim(data)[1])
  for (i in 1:dim(data)[1]){
    pi_vec[i] <- CalcStayerHelper(data[i,,], likelihoods[i])
  }
  pi_0 <- (pi_vec %*% freq_vec)/sum(freq_vec)
  return(pi_0[1])
}
```

```{r}
CalcInitialLin <- function(data,freq_vec, pi_0, forw, backw, likelihoods){
  k <- numOfStates(data)
  prob_list <- numeric(length(k))
  
  for (i in 1:dim(data)[1]){
    
    ind_likelihood <- likelihoods[[i]]
    forw_sum <- numeric(length(k))
    backw_sum <- numeric(length(k))
    
    for (j in 1:length(forw[[i]][[1]])){
      forw_sum <- forw_sum + forw[[i]][[1]][[j]]
    }
    
    backw_sum <- backw[[i]][[1]]
  
    mover <- forw_sum * backw_sum * (1 - pi_0) / ind_likelihood
    prob_list <- prob_list + (mover * freq_vec[i])
  }
  return(prob_list/sum(prob_list))
} 
```

```{r}
CalcTransitionLin <- function(data, tran,class,freq_vec, pi_0, forw, backw, likelihoods){
  
  k <- numOfStates(data)
  tran_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
  possible_initial_states <- c(1,3,5,7,9,11,13,15,17)
  possible_initial_states_copa <- c(2,4,6,8,10,12,14,16,18)
  
  for (ind in 1:dim(data)[1]){
    forward <- forw[[ind]]
    backward <- backw[[ind]]
    denom <- likelihoods[[ind]]
    for (time in 2:dim(data)[2]){
      
      
      forw_sum <- numeric(length(k))
      
      for (i in 1:length(forward[[time-1]])){
        forw_sum <- forw_sum + forward[[time-1]][[i]]
      }

      backw_sum <- backward[[time]]
          
      
      tran_matrix_current <- matrix(0L, nrow = length(k), ncol = length(k))
        
      for (initial_state in possible_initial_states){
        if (initial_state < 6){possible_new_states <- c(1:12)}
        else {possible_new_states <- c(1:6,13:18)}
        
        for(new_state in possible_new_states){
          
          num <- forw_sum[[initial_state]] * backw_sum[[new_state]] * tran[initial_state,new_state] * Classification(data[ind,time,],new_state-1,class) * (1 - pi_0)
          if(denom != 0){
            tran_matrix_current[initial_state,new_state] <- tran_matrix_current[initial_state,new_state] + (num/denom)
          } 
        }
      }
      
      for (initial_state in possible_initial_states_copa){
        if (initial_state < 7){possible_new_states <- c(2,4,6,8,10,12)}
        else {possible_new_states <- c(2,4,6,14,16,18)}
        
        for(new_state in possible_new_states){
          
          num <- forw_sum[[initial_state]] * backw_sum[[new_state]] * tran[initial_state,new_state] * Classification(data[ind,time,],new_state-1,class) * (1 - pi_0)
          if(denom != 0){
            tran_matrix_current[initial_state,new_state] <- tran_matrix_current[initial_state,new_state] + (num/denom)
          } 
        }
      }
        
      tran_matrix <- tran_matrix + ((tran_matrix_current) * freq_vec[ind])
    }
  }
  return(Normalize(tran_matrix))
}
```

```{r}
CalcClassificationLin <- function(data,class, freq_vec, forw, backw, likelihoods, pi_0){
  k <- numOfStates(data)
  num_matrix_full <- matrix(0L, nrow = length(k), ncol = length(k))
  for (ind in 1:dim(data)[1]){
    
    forward <- forw[[ind]]
    backward <- backw[[ind]]
    individual_likelihood <- likelihoods[[ind]]
    
    for(time in 1:dim(data)[2]){
      num_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
      backward_sum <- backward[[time]]
      
      
      x_vals <- data[ind,time,][!is.na(data[ind,time,])]
      
      for (u in 1:length(forward[[time]])){
        x_val <- x_vals[u]
        if (!is.na(x_val)){
          
        
          chain <- data[ind,,]
          chain[time,] <- NA
          chain[time,1] <- x_val
          
          mover <- (forward[[time]][[u]]*backward_sum * (1 - pi_0) / individual_likelihood)
          
          stayer <- (pi_0 * ProdClass(chain,class)) / individual_likelihood
          
          mover_stayer <- mover
          mover_stayer[1] <- mover_stayer[1] + stayer
          
          for (y_state in 1:length(k)){   
            num_matrix[y_state,x_val + 1] <- num_matrix[y_state, x_val+1] + mover_stayer[y_state]
          }
        }
      }
      
      
      #Normalization for partial
      if (sum(num_matrix) != 0){
        num_matrix <- num_matrix/sum(num_matrix)
      }
      num_matrix_full <- num_matrix_full + (num_matrix * freq_vec[ind])
      
    }
  }
  
  return(Normalize(num_matrix_full))
}
```
