---
title: "EM ALT"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
Classification <- function(x_val,y_val,class){
  if (is.na(x_val[1])){
    return(1)
  } else {
    rs <- 0
    for (val in x_val){
      if (is.na(val)){
        return(rs)
      } else {
        rs <- rs + class[[y_val + 1,val + 1]]
      }
    }
  }
  return(rs)
}
```

```{r}
ForwardLinear <- function(data,time,init,tran,class){
  k <- numOfStates()
  
  alpha_matrix<-vector("list",time)
  alpha_i <- numeric(length(k))
  num_of_part_vec <- numeric(dim(data)[1])
  
  for (i in 1:time){
    num_of_part_vec[i] <- sum(!is.na(data[i,]))
    if (num_of_part_vec[i] == 0){num_of_part_vec[i] = 1}
    alpha_matrix[[i]] <- vector("list",num_of_part_vec[i])
    for (j in 1:num_of_part_vec[i]){
      alpha_matrix[[i]][[j]] <- alpha_i
    }
  }
  
  partial_vals <- data[1,][!is.na(data[1,])]
  for (i in 1:num_of_part_vec[1]){
    for (j in 1:length(k)){
      alpha_matrix[[1]][[i]][j] <- init[j] * Classification(partial_vals[i],k[j],class)
    }
  }
    
  if (time > 1){
    for (i in 2:time){
      partial_vals <- data[i,][!is.na(data[i,])]
      
      if (num_of_part_vec[i - 1] == 1){
        old_alpha <- alpha_matrix[[i-1]][[1]]
      } else {
        old_alpha <- numeric(length(k))
        for (j in 1:num_of_part_vec[i-1]){
          old_alpha <- old_alpha + alpha_matrix[[i-1]][[j]]
        }
      }
      
      for (j in 1:num_of_part_vec[i]){
        for (l in 1:length(k)){
          alpha_matrix[[i]][[j]][l] <- (old_alpha %*% tran[,l]) *  Classification(partial_vals[j],k[l],class)
        }
      }
    }
  }
  
  return(alpha_matrix)
}
```



```{r}
BackwardLinear <- function(data,time,tran,class){
  k <- numOfStates()
  
  beta_i <- numeric(length(k))
  misclass_vector <- numeric(length(k))
  beta_matrix<-vector("list",dim(data)[1])
  num_of_part_vec <- numeric(dim(data)[1])
  
  
  for (i in 1:dim(data)[1]){
    num_of_part_vec[i] <- sum(!is.na(data[i,]))
    if (num_of_part_vec[i] == 0){num_of_part_vec[i] = 1}
  }
  
  
  for (i in 1:(dim(data)[1] - 1)){
    beta_matrix[[i]] <- vector("list",num_of_part_vec[i + 1])
    for (j in 1:num_of_part_vec[i + 1]){
      beta_matrix[[i]][[j]] <- beta_i
    }
  }
  
  beta_matrix[[dim(data)[1]]] <- vector("list",1)
  for (i in 1:length(k)){
    beta_matrix[[dim(data)[1]]][[1]][i] <- 1
  }
  
  if (time != dim(data)[1]) {
    for (i in (dim(data)[1]-1):time){
      partial_vals <- data[i+1,][!is.na(data[i+1,])]
  
      new_beta <- numeric(length(k))
      for (m in 1:length(beta_matrix[[i+1]])){
        new_beta <- new_beta + beta_matrix[[i+1]][[m]]
      }
      
      
      for (m in 1:num_of_part_vec[i+1]){
        
        for (l in 1:length(k)){
          misclass_vector[l] <- Classification(partial_vals[m],k[l],class)
        }
        
        for (j in 1:length(k)){
          beta_matrix[[i]][[m]][j] <- sum(new_beta * tran[j,] * misclass_vector)
        }
        
      }
    }
  }
    
  
  return(beta_matrix)
}
```


```{r}
CalcInitialLin <- function(data,freq_vec, pi_0, forw, backw, likelihoods){
  k <- numOfStates(data)
  prob_list <- numeric(length(k))
  
  for (i in 1:dim(data)[1]){
    
    ind_likelihood <- likelihoods[[i]]
    forw_sum <- numeric(length(k))
    backw_sum <- numeric(length(k))
    
    for (j in 1:length(forw[[i]][[1]])){
      forw_sum <- forw_sum + forw[[i]][[1]][[j]]
    }
    
    for (j in 1:length(backw[[i]][[1]])){
      backw_sum <- backw_sum + backw[[i]][[1]][[j]]
    }
  
    mover <- forw_sum * backw_sum * (1 - pi_0) / ind_likelihood
    prob_list <- prob_list + (mover * freq_vec[i])
  }
  return(prob_list/sum(prob_list))
} 
```


```{r}
CalcLikelihood <- function(data, init,tran,class,pi){
  
  t <- 2
  
  forward <- ForwardLinear(data,t,init,tran,class)
  backward <- BackwardLinear(data,t,tran,class)
  
  forw_sum <- numeric(length(numOfStates()))
  backw_sum <- numeric(length(numOfStates()))
  
  for (i in 1:length(forward[[t]])){
    forw_sum <- forw_sum + forward[[t]][[i]]
  }
  
  for (i in 1:length(backward[[t]])){
    backw_sum <- backw_sum + backward[[t]][[i]]
  }
  
  
  individual_likelihood <- (forw_sum %*% backw_sum)
  
  likelihood <- (pi * ProdClass(data,class)) + ((1 - pi) * individual_likelihood)

  return(likelihood)
}
```

```{r}
# CalcLikelihoodMover <- function(data, init,tran,class,pi){
#   
#   t <- 2
#   
#   forward <- ForwardLinear(data,t,init,tran,class)
#   backward <- BackwardLinear(data,t,tran,class)
#   
#   forw_sum <- numeric(length(numOfStates()))
#   backw_sum <- numeric(length(numOfStates()))
#   
#   for (i in 1:length(forward[[t]])){
#     forw_sum <- forw_sum + forward[[t]][[i]]
#   }
#   
#   for (i in 1:length(backward[[t]])){
#     backw_sum <- backw_sum + backward[[t]][[i]]
#   }
#   
#   
#   individual_likelihood <- (forw_sum %*% backw_sum)
# 
#   return(individual_likelihood)
# }
```




```{r}
ProdClass <- function(data,class){
  return(Classification(data[1,],0,class) * Classification(data[2,],0,class)* Classification(data[3,],0,class)* Classification(data[4,],0,class)* Classification(data[5,],0,class))
}
```

```{r}
CalcTransitionLin <- function(data, tran,class,freq_vec, pi_0, forw, backw, likelihoods){
  
  k <- numOfStates(data)
  tran_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
  possible_initial_states <- c(1,3,5,7,9,11,13,15,17)
  possible_initial_states_copa <- c(2,4,6,8,10,12,14,16,18)
  
  for (ind in 1:dim(data)[1]){
    forward <- forw[[ind]]
    backward <- backw[[ind]]
    denom <- likelihoods[[ind]]
    for (time in 2:dim(data)[2]){
      
      
      forw_sum <- numeric(length(k))
      backw_sum <- numeric(length(k))
      
      for (i in 1:length(forward[[time-1]])){
        forw_sum <- forw_sum + forward[[time-1]][[i]]
      }
      
      for (i in 1:length(backward[[time]])){
        backw_sum <- backw_sum + backward[[time]][[i]]
      }
          
      
      tran_matrix_current <- matrix(0L, nrow = length(k), ncol = length(k))
        
      for (initial_state in possible_initial_states){
        if (initial_state < 6){possible_new_states <- c(1:12)}
        else {possible_new_states <- c(1:6,13:18)}
        
        for(new_state in possible_new_states){
          
          num <- forw_sum[[initial_state]] * backw_sum[[new_state]] * tran[initial_state,new_state] * Classification(data[ind,time,],new_state-1,class) * (1 - pi_0)
          if(denom != 0){
            tran_matrix_current[initial_state,new_state] <- tran_matrix_current[initial_state,new_state] + (num/denom)
          } 
        }
      }
      
      for (initial_state in possible_initial_states_copa){
        if (initial_state < 7){possible_new_states <- c(2,4,6,8,10,12)}
        else {possible_new_states <- c(2,4,6,14,16,18)}
        
        for(new_state in possible_new_states){
          
          num <- forw_sum[[initial_state]] * backw_sum[[new_state]] * tran[initial_state,new_state] * Classification(data[ind,time,],new_state-1,class) * (1 - pi_0)
          if(denom != 0){
            tran_matrix_current[initial_state,new_state] <- tran_matrix_current[initial_state,new_state] + (num/denom)
          } 
        }
      }
        
      tran_matrix <- tran_matrix + ((tran_matrix_current) * freq_vec[ind])
    }
  }
  return(Normalize(tran_matrix))
}
```

```{r}
CalcClassificationLin <- function(data,class, freq_vec, forw, backw, likelihoods, pi_0){
  k <- numOfStates(data)
  num_matrix_full <- matrix(0L, nrow = length(k), ncol = length(k))
  for (ind in 1:dim(data)[1]){
    
    forward <- forw[[ind]]
    backward <- backw[[ind]]
    individual_likelihood <- likelihoods[[ind]]
    
    for(time in 1:dim(data)[2]){
      num_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
      backward_sum <- numeric(18)
      
      for (i in 1:length(backward[[time]])){
        backward_sum <- backward_sum + backward[[time]][[i]]
      }
      
      
      x_vals <- data[ind,time,][!is.na(data[ind,time,])]
      
      for (u in 1:length(forward[[time]])){
        x_val <- x_vals[u]
        if (!is.na(x_val)){
          
        
          chain <- data[ind,,]
          chain[time,] <- NA
          chain[time,1] <- x_val
          
          mover <- (forward[[time]][[u]]*backward_sum * (1 - pi_0) / individual_likelihood)
          
          stayer <- (pi_0 * ProdClass(chain,class)) / individual_likelihood
          
          mover_stayer <- mover
          mover_stayer[1] <- mover_stayer[1] + stayer
          
          for (y_state in 1:length(k)){   
            num_matrix[y_state,x_val + 1] <- num_matrix[y_state, x_val+1] + mover_stayer[y_state]
          }
        }
      }
      
      
      #Normalization for partial
      if (sum(num_matrix) != 0){
        num_matrix <- num_matrix/sum(num_matrix)
      }
      num_matrix_full <- num_matrix_full + (num_matrix * freq_vec[ind])
      
    }
  }
  
  return(Normalize(num_matrix_full))
}
```

```{r}
CalcStayerLin <- function(data,init,tran,class,freq_vec,pi_0, likelihoods){
  
  CalcStayerHelper <- function(data,likelihood){
    return((pi_0 * ProdClass(data,class) / likelihood))
  }
  
  
  pi_vec <- numeric(dim(data)[1])
  for (i in 1:dim(data)[1]){
    pi_vec[i] <- CalcStayerHelper(data[i,,], likelihoods[i])
  }
  pi_0 <- (pi_vec %*% freq_vec)/sum(freq_vec)
  return(pi_0[1])
}
```

```{r}
CalcLikelihoodMover <- function(forw){
  
  rs <- 0 
  for (i in 1:length(forw[[5]])){
    rs <- rs + forw[[5]][[i]]
  }
  
  return(sum(rs)[[1]])
}


```

```{r}
CalcLikelihoodStayer <- function(data, class, pi){
  return((pi * ProdClass(data,class)))
}
```


```{r}
forw <- apply(ALTS_pattern,1,ForwardIterFull, time = 5, init,tran,class)
backw <- apply(ALTS_pattern,1,FUN = BackwardIterFull, time = 1, tran, class)
likelihoods <- apply(ALTS_pattern,1,FUN = CalcIndLikelihood, init, tran, class,pi_0)
(likelihood <- (log(likelihoods) %*% freq_vec)[1])

forwALT <- apply(ALTS_pattern,1,ForwardLinear, time = 5, init,tran,class)
backwALT <- apply(ALTS_pattern,1,FUN = BackwardLinear, time = 1, tran, class)
likelihoodsMover <- unlist(lapply(forwALT, CalcLikelihoodMover))
likelihoodsStayers <- apply(ALTS_pattern,1,FUN = CalcLikelihoodStayer, class, pi_0)
likelihoodsALT <- likelihoodsStayers + ((1 - pi_0) * likelihoodsMover)
(likelihoodALT <- (log(likelihoodsALT) %*% freq_vec)[1])







```


