---
title: "ALTS EM"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
StateCalculator <- function(val1, val2, val3){
  if (!is.na(val1) & !is.na(val2) & !is.na(val3)){
    return(c(6 * val1 + 2 * val2 + val3))
  } else if (!is.na(val1) & !is.na(val2) & is.na(val3)){
    # if(val1 == 0 & val2 == 0){
    #   return(0)
    # }
    return(c(6 * val1 + 2 * val2, 6 * val1 + 2 * val2 + 1))
  } else if (!is.na(val1) & is.na(val2) & !is.na(val3)){
    return(c(6 * val1 + val3, 6 * val1 + 2 + val3, 6 * val1 + 4 + val3))
  } else if (is.na(val1) & !is.na(val2) & !is.na(val3)){
    return(c(2 * val2 + val3, 6 + 2 * val2 + val3, 12 + 2 * val2 + val3))
  } else if (!is.na(val1) & is.na(val2) & is.na(val3)){
    return(c(6 * val1, 6 * val1 + 1, 6 * val1 + 2, 6 * val1 + 3, 6 * val1 + 4, 6 * val1 + 5))
  }else if (is.na(val1) & !is.na(val2) & is.na(val3)){
    return(c(2 * val2, 2 * val2 + 1, 2 * val2 + 6, 2 * val2 + 7, 2 * val2 + 12, 2 * val2 + 13))
  }else if (is.na(val1) & is.na(val2) & !is.na(val3)){
    return(c(val3, val3 + 2, val3 + 4, val3 + 6, val3 + 8, val3 + 10, val3 + 12, val3 + 14, val3 + 16))
  } else {
    return(NA)
  }
}

```

```{r}
Normalize <- function(data){
  for (i in 1:dim(data)[1]){
    if (sum(data[i,],na.rm = TRUE) != 0){
      data[i,] <- data[i,]/sum(data[i,])
    }
  }
  return(data)
}
```

```{r}
Classification <- function(x_val,y_val,class){
  if (is.na(x_val)){
    return(1)
  }
  return(class[[y_val+1,x_val+1]])
}
```

```{r}
numOfStates <- function(data,type){
  if (missing(type)){
    return(c(0:17))
  }
}
```

```{r}
GetPatterns <- function(states){
  library(plyr)
  options(scipen = 999)
  vals <- rep(NaN,dim(states)[1])
  for (i in 1:dim(states)[1]){
    val <- ""
    for(j in 1:dim(states)[2]){
      for(k in 1:dim(states)[3]){
        if (!is.na(states[i,j,k])){
          states_val <- states[i,j,k] 
          } else {
            states_val <- NA
          }
          val <- paste0(val, states_val,",")
        }
      }
    val <- substr(val, 1, nchar(val)-1)
    vals[i] <- val
  }
  return(vals)
}
```

```{r}
Pattern2Data <- function(unique_patterns){
  time_length <- 5
  n <- length(unique_patterns[[1]])
  partial_len <- 12
  freq_vec <- numeric(n)
  state_array <- array(0, dim = c(n,time_length,partial_len))
  for (i in 1:n){
    freq_vec[i] <- unique_patterns$Freq[[i]]
    pattern <- unique_patterns$all_patterns[[i]]

    pattern <- strsplit(pattern, split = ",")[[1]]
    for (time in 1:time_length){
      state_array[i,time,] <- suppressWarnings(as.integer(pattern[(((time-1)*partial_len)+1):(time*partial_len)]))
    }
  }

  return(list(state_array, freq_vec))
}

```

```{r}
InitialProbTrue <- function(data, stayer_vec){
  init <- numeric(length(numOfStates(data)))
  for (i in 1:dim(data)[1]){
    if (stayer_vec[i] == 0 & !is.na(data[i,1])){
      init[data[i,1]+1] <- init[data[i,1]+1] + 1
    }
  }
  return(init)
}
```

```{r}
InitialProb <- function(data, freq_vec, stayer_vec = rep(0,length(freq_vec))){
  init <- numeric(length(numOfStates(data)))
  for (i in 1:dim(data)[1]){
    if (stayer_vec[i] == 0){
      num_of_parts <- sum(!is.na(data[i,1,]))
      if (!is.na(data[i,1,1])){
        for (j in data[i,1,]){
          if (!is.na(j)){
            init[j+1] <- init[j+1] + freq_vec[i]/num_of_parts
          }
          
        }
      }
    }
  }
  return(init)
}
```

```{r}
PiProb <- function(data, freq_vec){
  stayer_vec <- numeric(length(freq_vec))
  
  for (i in 1:dim(data)[1]){
    to_add <- 1
    for (j in 1:dim(data)[2]){
      if (!(0 %in% data[i,j,])){
        to_add <- 0
      }
    }
    stayer_vec[i] <- to_add
  }
  return(stayer_vec)
}
```

```{r}
ReduceHist <- function(tran){
  for (i in 1:dim(tran)[1]){
    for (j in 1:dim(tran)[2]){
      if (i %% 2 == 1 & j %% 2 == 0){
        if (i < 7){
          tran[i,j] <- tran[i,j] / 1000
        } else if (i < 13){
          tran[i,j] <- tran[i,j] / 100
        } else {
          tran[i,j] <- tran[i,j] / 10
        }
        
        if (j < 7){
          tran[i,j] <- tran[i,j] / 1000
        } else if (j < 13) {
          tran[i,j] <- tran[i,j] / 100
        } else {
          tran[i,j] <- tran[i,j] / 10
        }
        
      }
    }
  }
  return(Normalize(tran))
}

```

```{r}
TransitionProb <- function(data, freq_vec, stayer_vec = rep(0,length(freq_vec))){
  k <- length(numOfStates(data))
  tran <- matrix(0,k,k)
  for (i in 1:dim(data)[1]){
    if (stayer_vec[i] == 0){
      for (j in 2:dim(data)[2]){
        if (!is.na(data[i,j-1,1]) & !is.na(data[i,j,1])){
          num_of_parts <- sum(!is.na(data[i,j-1,])) * sum(!is.na(data[i,j,]))
          for (k1 in data[i,j-1,]){
            for (k2 in data[i,j,]){
              if (!is.na(k1) & !is.na(k2)){
                tran[k1+1,k2+1] <- tran[k1+1,k2+1] + freq_vec[i]/num_of_parts
              }
              
            }
          }
        }
      }
    }
  }
  for (i in 1:dim(tran)[1]){
    if (i %% 2 == 0){
      for (j in 1:dim(tran)[2]){
        if (j %% 2 == 1){
          tran[i,j] <- 0
        }
      }
    }
  }
  
  tran[1:6,13:18] <- 0
  tran[7:18,7:12] <- 0
  return(tran)
}
```

```{r}
TransitionProbTrue <- function(data,stayer_vec){
  k <- length(numOfStates(data))
  tran <- matrix(0,k,k)
  for (i in 1:dim(data)[1]){
    if (stayer_vec[i] == 0){
      for (j in 2:dim(data)[2]){
        if (!is.na(data[i,j-1]) & !is.na(data[i,j])){
          tran[data[i,j-1]+1,data[i,j]+1] <- tran[data[i,j-1]+1,data[i,j]+1] + 1
        }
      }
    }
  }
  return(tran)
}
```

```{r}
GetAllPossibilitiesForw <- function(data, time){
  
  for (curr_time in 1:time){
    
    if (curr_time == 1){
      possibilities <- data[1,]
      if (sum(!is.na(possibilities)) == 0){
        possibilities <- NA
      } else {
        possibilities <- possibilities[!is.na(possibilities)]
      }
      possibilities <- t(as.matrix(possibilities))
      
    } else {
      current_possibilities <- data[curr_time,]
      if (sum(!is.na(current_possibilities)) == 0){
        possibilities <- rbind(possibilities, NA)
        
      } else {
        current_possibilities <- current_possibilities[!is.na(current_possibilities)]
        running_possibilities <- c()
        current_possibilities <- rev(current_possibilities)
        for (i in 1:length(current_possibilities)){
          running_possibilities <- cbind(rbind(possibilities,current_possibilities[i]),running_possibilities)
        }
        possibilities <- running_possibilities
      }
    }
  }
  return(possibilities)

}
```

```{r}
GetAllPossibilitiesBackw <- function(data, time){
  max_time <- dim(data)[1]
  for (curr_time in time:max_time){
    if (curr_time == time){
      possibilities <- data[curr_time,]
      if (sum(!is.na(possibilities)) == 0){
        possibilities <- NA
      } else {
        possibilities <- possibilities[!is.na(possibilities)]
      }
      possibilities <- t(as.matrix(possibilities))
      
    } else {
      current_possibilities <- data[curr_time,]
      if (sum(!is.na(current_possibilities)) == 0){
        possibilities <- rbind(possibilities, NA)
        
      } else {
        current_possibilities <- current_possibilities[!is.na(current_possibilities)]
        running_possibilities <- c()
        current_possibilities <- rev(current_possibilities)
        for (i in 1:length(current_possibilities)){
          running_possibilities <- cbind(rbind(possibilities,current_possibilities[i]),running_possibilities)
        }
        possibilities <- running_possibilities
      }
    }
  }
  if (time == 4){
    possibilities <- possibilities[,order(possibilities[1,], possibilities[2,])]
  } else if (time == 3){
    possibilities <- possibilities[,order(possibilities[1,], possibilities[2,], possibilities[3,])]
  } else if (time == 2){
    possibilities <- possibilities[,order(possibilities[1,], possibilities[2,], possibilities[3,], possibilities[4,])]
  } else if (time == 1){
    possibilities <- possibilities[,order(possibilities[1,], possibilities[2,], possibilities[3,], possibilities[4,], possibilities[5,])]
  }
  return(as.matrix(possibilities))

}
```

```{r}
#JASA paper method 
ForwardIterFull <- function(data,time,init,tran,class){
  k <- numOfStates()
  all_pos_obs <- GetAllPossibilitiesForw(data,time)
  alpha_matrix_pos <- vector("list", dim(all_pos_obs)[2])
  for(pos in 1:dim(all_pos_obs)[2]){
    pos_ob <- all_pos_obs[,pos]
    
    alpha_matrix<-vector("list",time)
    alpha_i <- numeric(length(k))
    
    for (i in 1:time){
      alpha_matrix[[i]] <- alpha_i
    }
    
    
    for (i in 1:length(k)){
      if (!is.na(pos_ob[1])){
        alpha_matrix[[1]][i] <- init[i] * Classification(pos_ob[1],k[i],class)
      } else {
        alpha_matrix[[1]][i] <- init[i]
      }
    }
    
    if (time > 1){
      for (i in 2:time){
        for (j in 1:length(k)){
          if (!is.na(pos_ob[i])){
            alpha_matrix[[i]][j] <- (alpha_matrix[[i-1]] %*% tran[,j]) *  Classification(pos_ob[i],k[j],class)
          } else {
            alpha_matrix[[i]][j] <- (alpha_matrix[[i-1]] %*% tran[,j])
          }
        }
      }
    }
    
    alpha_matrix_pos[[pos]] <- alpha_matrix
    
  }
  
  return(alpha_matrix_pos)
}
```

```{r}
BackwardIterFull <- function(data,time,tran,class){
  k <- numOfStates()
  length <- dim(data)[1]
  
  #Works since Beta only uses X_t+1
  if (time == 5){
    adj_time <- time
  } else{
    adj_time <- time + 1
  }
  
  all_pos_obs <- GetAllPossibilitiesBackw(data,adj_time)
  beta_matrix_pos <- vector("list", dim(all_pos_obs)[2])
  
  
  for(pos in 1:dim(all_pos_obs)[2]){
    pos_ob <- all_pos_obs[,pos]
    #Want backward length to always be 5 as it makes future indexing easier
    #Add dummy -1 to inflate length
    pos_ob <- append(pos_ob,rep(-1,adj_time-1),0)
    
    beta_i <- numeric(length(k))
    misclass_vector <- numeric(length(k))
    beta_matrix<-vector("list",length)
    
    for (i in 1:length){
      beta_matrix[[i]] <- beta_i
    }
    
    for (i in 1:length(k)){
      beta_matrix[[length]][i] <- 1
    }
    if (time != length) {
      for (i in (length-1):time){
        if (!is.na(pos_ob[i+1])){
          for (l in 1:length(k)){
            misclass_vector[l] <- Classification(pos_ob[i+1],k[l],class)
          }
          for (j in 1:length(k)){
            beta_matrix[[i]][j] <- sum(beta_matrix[[i+1]] * tran[j,] * misclass_vector,na.rm = TRUE)
          }
        } else {
          for (j in 1:length(k)){
            if (sum(beta_matrix[[i+1]]) == length(k)){
              beta_matrix[[i]][j] <- 1
            } else {
              beta_matrix[[i]][j] <- sum(beta_matrix[[i+1]] * tran[j,]) 
            }
          }
        }
      }
    }
    
    beta_matrix_pos[[pos]] <- beta_matrix
  }
  
  return(beta_matrix_pos)
}
```

```{r}
# ForwardIterFullInd <- function(data, ind, time, init, tran, class){
#   return(ForwardIterFull(data[ind,,], time, init, tran, class))
# }
```

```{r}
# BackwardIterFullInd <- function(data, ind, time, tran, class){
#   return(BackwardIterFull(data[ind,,], time, tran, class))
# }
```

```{r}
CalcProdInd <- function(data,class){
  prod_total <- 0
  partial_data_full <- GetAllPossibilitiesForw(data,dim(data)[1])
  for (chain in 1:dim(partial_data_full)[2]){
    prod <- 1
    partial_data <- partial_data_full[,chain]
    for (j in 1:length(partial_data)){  
      if (!is.na(partial_data[j])){
        prod <- prod * Classification(partial_data[j], 0, class)
      }
    }
    prod_total <- prod_total + prod
  }
  return(prod_total)
}
``` 

```{r}
CalcProdIndAlt <- function(data,class){
  prod <- 1
  for (j in 1:length(data)){
    if (!is.na(data[j])){
      prod <- prod * Classification(data[j], 0, class)
    }
  }
  return(prod)
}
```

```{r}
CalcIndLikelihood <- function(data, init,tran,class,pi){
  
  forward <- ForwardIterFull(data,2,init,tran,class)
  backward <- BackwardIterFull(data,2,tran,class)
  

  
  forward_sum <- numeric(length(numOfStates()))
  for (u in 1:length(forward)){
    forward_sum <- forward_sum + forward[[u]][[2]]
  }
  
  backward_sum <- numeric(length(numOfStates()))
  for (v in 1:length(backward)){
    backward_sum <- backward_sum + backward[[v]][[2]]
  }
  
  
  individual_likelihood <- (forward_sum %*% backward_sum)[[1]]
  
  likelihood <- (pi * CalcProdInd(data,class)) + ((1 - pi) * individual_likelihood)
  # if (likelihood == 0){
  #   print(individual)
  # }
  return(likelihood)
}
```

```{r}
CalcStayer <- function(data,init,tran,class,freq_vec,pi_0){
  stayer_vec <- numeric(dim(data)[1])
  
  CalcStayerHelper <- function(data){
    return((pi_0 * CalcProdInd(data,class) / CalcIndLikelihood(data,init,tran,class,pi_0)))
  }
  
  pi_0 <- (apply(data,1,FUN = CalcStayerHelper) %*% freq_vec)/sum(freq_vec)
  return(pi_0[1])
}
```

```{r}
CalcInitialPattern <- function(data,freq_vec, pi_0, forw, backw, likelihoods){
  k <- numOfStates(data)
  prob_list <- numeric(length(k))
  
  # forw <- apply(data,1,ForwardIterFull, time = 1, init,tran,class)
  # backw <- apply(data,1,FUN = BackwardIterFull, time = 1, tran, class)
  # likelihoods <- apply(data,1,FUN = CalcIndLikelihood, init, tran, class,pi_0)
  
 
  
  for (i in 1:dim(data)[1]){
    forward <- forw[[i]]
    backward <- backw[[i]]
    ind_likelihood <- likelihoods[[i]]
    
    forward_sum <- numeric(length(k))
    backward_sum <- numeric(length(k))
    
    forw_length <- dim(GetAllPossibilitiesForw(data[i,,],1))[2]
    
    for (k in 1:forw_length){
     forward_sum <- forward_sum + forward[[k]][[1]] 
    }
    for (k in 1:length(backward)){
     backward_sum <- backward_sum + backward[[k]][[1]] 
    }
    
    mover <- forward_sum * backward_sum * (1 - pi_0) / ind_likelihood
    prob_list <- prob_list + (mover * freq_vec[i])
  }
  return(prob_list/sum(prob_list))
} 
```

```{r}
CalcTransitionPattern <- function(data, tran,class,freq_vec, pi_0, forw, backw, likelihoods){
  
  # forw <- apply(data,1,ForwardIterFull, time = 4, init,tran,class)
  # backw <- apply(data,1,FUN = BackwardIterFull, time = 2, tran, class)
  # likelihoods <- apply(data,1,FUN = CalcIndLikelihood, init, tran, class,pi_0)
  
  k <- numOfStates(data)
  tran_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
  possible_initial_states <- c(1,3,5,7,9,11,13,15,17)
  possible_initial_states_copa <- c(2,4,6,8,10,12,14,16,18)
  
  for (ind in 1:dim(data)[1]){
    forward <- forw[[ind]]
    backward <- backw[[ind]]
    denom <- likelihoods[[ind]]
    for (time in 2:dim(data)[2]){
      tran_matrix_current <- matrix(0L, nrow = length(k), ncol = length(k))
      possible_x <- unique(GetAllPossibilitiesBackw(data[ind,,], time)[1,])
      
      if (time != 5){current_backw_length <- dim(GetAllPossibilitiesBackw(data[ind,,],time+1))[2]} 
      else {current_backw_length <- 1}
      
      current_forw_length <- dim(GetAllPossibilitiesForw(data[ind,,],time-1))[2]
      
      
      forward_sum <- numeric(length(k))
      backward_sum <- numeric(length(k))
      
      
      for (u in 1:current_forw_length){
        forward_sum <- forward_sum + forward[[u]][[time-1]]
      }
      
      
      if (time == dim(data)[2]){
        backward_sum <- rep(1, length(k))
      } else {
        for (v in 1:current_backw_length){
          backward_sum <- backward_sum + backward[[v]][[time]]
        }
      }
      
      
      for(gX in possible_x){ 
        
        for (initial_state in possible_initial_states){
          if (initial_state < 6){possible_new_states <- c(1:12)}
          else {possible_new_states <- c(1:6,13:18)}
          
          for(new_state in possible_new_states){
            
            num <- forward_sum[[initial_state]] * backward_sum[[new_state]] * tran[initial_state,new_state] * Classification(gX,new_state-1,class) * (1 - pi_0)
            if(denom != 0){
              tran_matrix_current[initial_state,new_state] <- tran_matrix_current[initial_state,new_state] + (num/denom)
            } 
          }
        }
        
        for (initial_state in possible_initial_states_copa){
          if (initial_state < 7){possible_new_states <- c(2,4,6,8,10,12)}
          else {possible_new_states <- c(2,4,6,14,16,18)}
          
          for(new_state in possible_new_states){
            
            num <- forward_sum[[initial_state]] * backward_sum[[new_state]] * tran[initial_state,new_state] * Classification(gX,new_state-1,class) * (1 - pi_0)
            if(denom != 0){
              tran_matrix_current[initial_state,new_state] <- tran_matrix_current[initial_state,new_state] + (num/denom)
            } 
          }
        }
        
        
      }
      tran_matrix <- tran_matrix + ((tran_matrix_current) * freq_vec[ind])
    }
  }
  return(Normalize(tran_matrix))
}
```

```{r}
CalcClassificationPattern <- function(data,class, freq_vec, forw, backw, likelihoods, pi_0){
  k <- numOfStates(data)
  num_matrix_full <- matrix(0L, nrow = length(k), ncol = length(k))
  # forw <- apply(data,1,ForwardIterFull, time = 5, init,tran,class)
  # backw <- apply(data,1,FUN = BackwardIterFull, time = 1, tran, class)
  # likelihoods <- apply(data,1,FUN = CalcIndLikelihood, init, tran, class,pi_0)
  for (ind in 1:dim(data)[1]){
    
    forward <- forw[[ind]]
    backward <- backw[[ind]]
    individual_likelihood <- likelihoods[[ind]]
    
    for(time in 1:dim(data)[2]){
      num_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
      
      if (time != dim(data)[2]){current_backw_length <- dim(GetAllPossibilitiesBackw(data[ind,,],time+1))[2]} 
      else {current_backw_length <- 1}
      current_forw_length <- dim(GetAllPossibilitiesForw(data[ind,,],time))[2]

      
      
      beggining_forw <- GetAllPossibilitiesForw(data[ind,,],time)
      if (time != dim(data)[2]){
        ending_backw <- GetAllPossibilitiesBackw(data[ind,,],(time+1))
      }
      x_vals <- unique(beggining_forw[time,])
      
      for (u in 1:current_forw_length){
        x_val <- beggining_forw[time,u]
        for (v in 1:current_backw_length){
          if (!is.na(x_val)){
            
            if (time != dim(data)[2]){
              chain <- c(beggining_forw[,u], as.vector(ending_backw[,v]))
            } else {
              chain <- beggining_forw[,u]
            }
            
            mover <- (forward[[u]][[time]]*backward[[v]][[time]] * (1 - pi_0) / individual_likelihood)
            if (individual_likelihood == 0){
              print(ind)
            }
            
            stayer <- (pi_0 * CalcProdIndAlt(chain,class)) / individual_likelihood
            
            mover_stayer <- mover
            mover_stayer[1] <- mover_stayer[1] + stayer
            
            for (y_state in 1:length(k)){   
              num_matrix[y_state,x_val + 1] <- num_matrix[y_state, x_val+1] + mover_stayer[y_state]
            }
          }
        }
      }
      
      
      #Normalization for partial
      if (sum(num_matrix) != 0){
        num_matrix <- num_matrix/sum(num_matrix)
      }
      num_matrix_full <- num_matrix_full + (num_matrix * freq_vec[ind])
      
    }
  }
  
  return(Normalize(num_matrix_full))
}
```

```{r}
CalcClassificationPatternNoStayer <- function(data,class, freq_vec, forw, backw, likelihoods){
  k <- numOfStates(data)
  num_matrix_full <- matrix(0L, nrow = length(k), ncol = length(k))
  # forw <- apply(data,1,ForwardIterFull, time = 5, init,tran,class)
  # backw <- apply(data,1,FUN = BackwardIterFull, time = 1, tran, class)
  # likelihoods <- apply(data,1,FUN = CalcIndLikelihood, init, tran, class,pi_0)
  for (ind in 1:dim(data)[1]){
    
    forward <- forw[[ind]]
    backward <- backw[[ind]]
    
    for(time in 1:dim(data)[2]){
      num_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
      
      if (time != dim(data)[2]){current_backw_length <- dim(GetAllPossibilitiesBackw(data[ind,,],time+1))[2]} 
      else {current_backw_length <- 1}
      current_forw_length <- dim(GetAllPossibilitiesForw(data[ind,,],time))[2]
      individual_likelihood <- likelihoods[[ind]]
      
      beggining_forw <- GetAllPossibilitiesForw(data[ind,,],time)
      if (time != dim(data)[2]){
        ending_backw <- GetAllPossibilitiesBackw(data[ind,,],(time+1))
      }
      x_vals <- unique(beggining_forw[time,])
      
      backward_sum <- numeric(length(numOfStates()))
      for (v in 1:current_backw_length){
        backward_sum <- backward_sum + backward[[v]][[time]]
      }
      for (u in 1:current_forw_length){
        x_val <- beggining_forw[time,u]
        if (!is.na(x_val)){
          mover <- (forward[[u]][[time]]*backward_sum / individual_likelihood)
          
          for (y_state in 1:length(k)){   
            num_matrix[y_state,x_val + 1] <- num_matrix[y_state, x_val+1] + mover[y_state]
          }
        }
      }
      
      
      #Normalization for partial
      if (sum(num_matrix) != 0){
        num_matrix <- num_matrix/sum(num_matrix)
      }
      num_matrix_full <- num_matrix_full + (num_matrix * freq_vec[ind])
      
    }
  }
  
  return(Normalize(num_matrix_full))
}
```

