---
title: "Parsing"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, include = FALSE, eval = FALSE}
# setwd("Data/Sim/No Pers/")
setwd("../Paper/Data/Sim MC 18/")
states <- 18
list_of_names <- list.files()
reps <- length(list_of_names)

init_array <- array(0,dim = c(1,states,reps))
tran_array <- array(0,dim = c(states,states,reps))
class_array <- array(0,dim = c(states,states,reps))
pi_array<- array(0,dim = c(1,1,reps))

init_true_array <- array(0,dim = c(1,states,reps))
tran_true_array <- array(0,dim = c(states,states,reps))
class_true_array <- array(0,dim = c(states,states,reps))
pi_true_array<- array(0,dim = c(1,1,reps))

init_true_count_array <- array(0,dim = c(1,states,reps))
tran_true_count_array <- array(0,dim = c(states,states,reps))
class_true_count_array <- array(0,dim = c(states,states,reps))

init_list <- vector("list", length = reps)
tran_list <- vector("list", length = reps)
class_list <- vector("list", length = reps)

init_true_list <- vector("list", length = reps)
tran_true_list <- vector("list", length = reps)
class_true_list <- vector("list", length = reps)

init_true_count_list <- vector("list", length = reps)
tran_true_count_list <- vector("list", length = reps)
class_true_count_list <- vector("list", length = reps)

data_true_list <- vector("list", length = reps)
freq_vec_list <- vector("list", length = reps)

count <- 1

for (name in list_of_names){
  load(name)
  
  obs_parameters <- to_save[[1]]
  true_parameters <- to_save[[2]]
  count_parameters <- to_save[[3]]
  
  init_list[[count]] <- obs_parameters[[1]]
  tran_list[[count]] <- obs_parameters[[2]]
  class_list[[count]] <- obs_parameters[[3]]
  
  init_true_list[[count]] <- true_parameters[[1]]
  tran_true_list[[count]] <- true_parameters[[2]]
  class_true_list[[count]] <- true_parameters[[3]]
  
  init_true_count_list[[count]] <- count_parameters[[1]]
  tran_true_count_list[[count]] <- count_parameters[[2]]
  class_true_count_list[[count]] <- count_parameters[[3]]
  
  
  pi_array[1,1,count] <- obs_parameters[[4]]
  pi_true_array[1,1,count] <- true_parameters[[4]]
  
  for (i in 1:states){
    init_array[1,i,count] <- init_list[[count]][i]
    init_true_array[1,i,count] <- init_true_list[[count]][i]
    init_true_count_array[1,i,count] <- init_true_count_list[[count]][i]
    for (j in 1:states){
      tran_array[i,j,count] <- tran_list[[count]][i,j]
      tran_true_array[i,j,count] <- tran_true_list[[count]][i,j]
      
      class_array[i,j,count] <- class_list[[count]][i,j]
      class_true_array[i,j,count] <- class_true_list[[count]][i,j]
      
      tran_true_count_array[i,j,count] <- tran_true_count_list[[count]][i,j]
      class_true_count_array[i,j,count] <- class_true_count_list[[count]][i,j]
    }
  }
  
  
  count <- count + 1
}


#############################################

state_visits <- numeric(states)
state_visits_true <- numeric(states)

init_med <- numeric(states)
tran_med <- matrix(0,states,states)
class_med <- matrix(0,states,states)
pi_med <- median(pi_array[1,1,])

init_true_med <- numeric(states)
tran_true_med <- matrix(0,states,states)
class_true_med <- matrix(0,states,states)
pi_true_med <- median(pi_true_array[1,1,])

init_avg <- numeric(states)
tran_avg <- matrix(0,states,states)
class_avg <- matrix(0,states,states)
pi_avg <- mean(pi_array[1,1,])

init_true_avg <- numeric(states)
tran_true_avg <- matrix(0,states,states)
class_true_avg <- matrix(0,states,states)
pi_true_avg <- mean(pi_true_array[1,1,])

init_true_count_med <- numeric(states)
init_true_count_avg <- numeric(states)
tran_true_count_med <- matrix(0,states,states)
tran_true_count_avg <- matrix(0,states,states)
class_true_count_med <- matrix(0,states,states)
class_true_count_avg <- matrix(0,states,states)

init_sd <- numeric(states)
tran_sd <- matrix(0,states,states)
class_sd <- matrix(0,states,states)


for (i in 1:states){
  init_med[i] <- median(init_array[1,i,])
  init_true_med[i] <- median(init_true_array[1,i,])
  
  init_avg[i] <- mean(init_array[1,i,])
  init_true_avg[i] <- mean(init_true_array[1,i,])
  
  init_true_count_med[i] <- median(init_true_count_array[1,i,])
  init_true_count_avg[i] <- mean(init_true_count_array[1,i,])
  
  init_sd[i] <- sqrt(var(init_array[1,i,]))
  
  
  for (j in 1:states){
    tran_med[i,j] <- median(tran_array[i,j,])
    tran_true_med[i,j] <- median(tran_true_array[i,j,])
    tran_avg[i,j] <- mean(tran_array[i,j,])
    tran_true_avg[i,j] <- mean(tran_true_array[i,j,])
    
    class_med[i,j] <- median(class_array[i,j,])
    class_true_med[i,j] <- median(class_true_array[i,j,])
    class_avg[i,j] <- mean(class_array[i,j,])
    class_true_avg[i,j] <- mean(class_true_array[i,j,])
    
    tran_true_count_med[i,j] <- median(tran_true_count_array[i,j,])
    tran_true_count_avg[i,j] <- mean(tran_true_count_array[i,j,])
    class_true_count_med[i,j] <- median(class_true_count_array[i,j,])
    class_true_count_avg[i,j] <- mean(class_true_count_array[i,j,])
    
  
    tran_sd[i,j] <- sqrt(var(tran_array[i,j,]))
    class_sd[i,j] <- sqrt(var(class_array[i,j,]))
    
  }
}
length <- 5
k <- c(0:2)

transition_true <- matrix(0L, nrow = length(k), ncol = length(k))
transition_obs <- matrix(0L, nrow = length(k), ncol = length(k))

initial_true <- numeric(states)
initial_obs <- numeric(states)

transition_obs <- transition_obs/reps
transition_true <- transition_true/reps

initial_true <- initial_true/reps
initial_obs <- initial_obs/reps


tran_med_adj <- tran_med

class_med_adj <- class_med

for (i in 1:dim(class_true_count_med)[1]){
  for (j in 1:dim(class_true_count_med)[2]){
    
    if (class_true_count_med[i,j] < 61){
      class_med_adj[i,j] <- class_true_med[i,j]
    }
    
    if (tran_true_count_med[i,j] < 61){
      tran_med_adj[i,j] <- tran_true_med[i,j]
    }
  }
}

RiskCalculator <- function(init, tran, class, pi, latent_states){
  if (missing(latent_states)){
    p_latent <- (init + init %*% tran + init %*% tran %*% tran + init %*% tran %*% tran %*% tran + init %*% tran %*% tran %*% tran %*% tran)
    latent_states <- p_latent * 3488 
    latent_states <- latent_states
  }
  risk <- numeric(states/2)
  latent_states_colpo <- latent_states
  latent_states_colpo[seq(1,states,2)] <- 0
  obs_states <-  latent_states %*% class
  obs_states_colpo <- latent_states_colpo %*% class
  
  for (i in 1:9){
    risk[i] <-(obs_states_colpo[2*i - 1] + obs_states_colpo[2*i])/(obs_states[2*i - 1] + obs_states[2*i])
  }
  
  return(risk)
  
}

risk_mat <- matrix(0,reps,9)
risk_mat_true <- matrix(0,reps,9)

for (i in 1:reps){
  est_init <- init_array[1,,i]
  est_init_true <- init_true_array[1,,i]
  
  est_tran <- tran_array[,,i]
  est_tran_true <- tran_true_array[,,i]
  
  est_class <- class_array[,,i]
  est_class_true <- class_true_array[,,i]
  
  est_pi <- pi_array[i]
  est_pi_true <- pi_true_array[i]
  
  
  p_latent <- (est_init + est_init %*% est_tran + est_init %*% est_tran %*% est_tran + est_init %*% est_tran %*% est_tran %*% est_tran + est_init %*% est_tran %*% est_tran %*% est_tran %*% est_tran)
  latent_states <- p_latent * 3488 
  # latent_states <- latent_states - to_remove
  
  p_latent_true <- (est_init_true + est_init_true %*% est_tran_true + est_init_true %*% est_tran_true %*% est_tran_true + est_init_true %*% est_tran_true %*% est_tran_true %*% est_tran_true + est_init_true %*% est_tran_true %*% est_tran_true %*% est_tran_true %*% est_tran_true)
  latent_states_true <- p_latent_true * 3488 
  # latent_states_true <- latent_states_true - to_remove_true
  
  risk_mat[i,] <- RiskCalculator(est_init,est_tran,est_class,est_pi, latent_states)
  risk_mat_true[i,] <- RiskCalculator(est_init_true,est_tran_true,est_class_true,est_pi_true, latent_states_true)
}

risk_sd <- numeric(9)
risk_true_sd <- numeric(9)

for (i in 1:9){
  risk_sd[i] <- sqrt(var(risk_mat[,i], na.rm =T))
  risk_true_sd[i] <- sqrt(var(risk_mat_true[,i]))
}

est_risk <- RiskCalculator(init_avg,tran_avg,class_avg,pi_avg)
est_risk_true <- RiskCalculator(init_true_avg,tran_true_avg,class_true_avg,pi_true_avg)

risk_ci_lb <- est_risk - (1.96 * risk_sd)
risk_ci_ub <- est_risk + (1.96 * risk_sd)

risk_ci_lb[risk_ci_lb < 0] <- 0
risk_ci_ub[risk_ci_ub > 1] <- 1

(risk_ci_lb < est_risk_true)  & (est_risk_true < risk_ci_ub)
```

```{r, echo = FALSE, fig.width=15, fig.height=15}
ClassificationHeatmap <- function(X_tran, state_labels = c(0:18), adj_labels){
  library(reshape)
  library(ggplot2)
  rownames(X_tran) <- c(state_labels)
  colnames(X_tran) <- c(state_labels)
  X_tran.m <- melt(X_tran)
  X_tran.m$X1 <- factor(X_tran.m$X1, levels = rev(adj_labels))
  X_tran.m$X2 <- factor(X_tran.m$X2, levels = (adj_labels))
  ggplot(X_tran.m,aes(X2, X1)) + 
    geom_tile(aes(fill = value),color = "white") + 
    scale_fill_gradient2(low = "blue",high = "red") +
    labs(x = "New State", y = "Initial State", caption = "Observed - True") + 
    theme(axis.text.y = element_text(size = 10), axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5)) + 
    theme(axis.text.x = element_text(angle = 0)) + 
    theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))) + 
    theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0))) +
    theme(plot.caption = element_text(hjust = .5))
}
```

```{r}
GenerateInitTable <- function(init, init_true, init_sd, init_count, title){
  library(knitr)
  library(kableExtra)
  combined_mat <- rbind(init, init_true,init_sd, init_count)
  rownames(combined_mat) <- c("Bias", "Truth", "SD", "Count")
  colnames(combined_mat) <- c(0:(length(init) -1))
  
  kable(combined_mat, caption = title) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = T) %>%
    group_rows("State 0",1,4) 
}
```

```{r}
GenerateTable <- function(mean_mat,truth_mat,var_mat,count_mat,title){
  library(knitr)
  library(kableExtra)
  row_names <- c("Bias", "Truth", "Std Dev", "Count")
  
  length_of_ind <- dim(mean_mat)[1]
  combined_mat <- matrix(0,length_of_ind*4, length_of_ind)
  
  for (i in 1:(length_of_ind * 4)){
    which_one <- i %% 4
    true_ind <- ceiling(i/4)
    if (which_one == 1){
      combined_mat[i,] <- mean_mat[true_ind,]
    } else if (which_one == 2){
      combined_mat[i,] <- truth_mat[true_ind,]
    } else if (which_one == 0){
      combined_mat[i,] <- count_mat[true_ind,]
    } else if (which_one == 3){
      combined_mat[i,] <- var_mat[true_ind,]
    }
  }
  
  rownames(combined_mat) <- rep(row_names,length_of_ind)

  colnames(combined_mat) <- c(0:(length_of_ind -1))
  
  kable(combined_mat, caption = title) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = T) %>%
    group_rows("State 0",1,4) %>%
    group_rows("State 1",5,8) %>%
    group_rows("State 2",9,12) %>%
    group_rows("State 3",13,16) %>%
    group_rows("State 4",17,20) %>%
    group_rows("State 5",21,24) %>%
    group_rows("State 6",25,28) %>%
    group_rows("State 7",29,32) %>%
    group_rows("State 8",33,36) %>%
    group_rows("State 9",37,40) %>%
    group_rows("State 10",41,44) %>%
    group_rows("State 11",45,48) %>%
    group_rows("State 12",49,52) %>%
    group_rows("State 13",53,56) %>%
    group_rows("State 14",57,60) %>%
    group_rows("State 15",61,64) %>%
    group_rows("State 16",65,68) %>%
    group_rows("State 17",69,72) 
    
  
    
}
```

```{r}
init_ci_lb <- init_avg - (1.96 * init_sd)
init_ci_ub <- init_avg + (1.96 * init_sd)
init_ci_lb[init_ci_lb < 0] <- 0
init_ci_ub[init_ci_ub > 1] <- 1
(init_true_avg >= init_ci_lb) & (init_true_avg <= init_ci_ub)

print("")

tran_ci_lb <- tran_avg - (1.96 * tran_sd)
tran_ci_ub <- tran_avg + (1.96 * tran_sd)
tran_ci_lb[tran_ci_lb < 0] <- 0
tran_ci_ub[tran_ci_ub > 1] <- 1
(tran_true_avg >= tran_ci_lb) & (tran_true_avg <= tran_ci_ub)

print("")

class_ci_lb <- class_avg - (1.96 * class_sd)
class_ci_ub <- class_avg + (1.96 * class_sd)
class_ci_lb[class_ci_lb < 0] <- 0
class_ci_ub[class_ci_ub > 1] <- 1
(class_true_avg >= class_ci_lb) & (class_true_avg <= class_ci_ub)
```


```{r}

state_labels <- c(0:17)
pi_med
pi_true_med
sum((init_avg - init_true_avg)^2)/18
sum((tran_avg - tran_true_avg)^2)/18^2
sum((class_avg - class_true_avg)^2)/18^2
# 
# 
ClassificationHeatmap(tran_avg - tran_true_avg, state_labels, state_labels) + ggtitle("Transition Residuals (mean)")
ClassificationHeatmap(class_avg - class_true_avg, state_labels, state_labels) + ggtitle("Classification Residuals (mean)")
GenerateInitTable(init_avg - init_true_avg, init_true_avg, init_sd, init_true_count_med, "Initial (Median")
GenerateTable(tran_avg - tran_true_avg, tran_true_avg, tran_sd, tran_true_count_med,"Transition (Median)")
GenerateTable(class_avg - class_true_avg, class_true_avg, class_sd, class_true_count_med,"Classification (Median)")
```

```{r}
colpo_pos <- c(2,4,6,8,10,12,14,16,18)
tran_avg_adj <- tran_avg
tran_avg_adj[colpo_pos,] <- tran_true_avg[colpo_pos,]
ClassificationHeatmap(tran_avg_adj - tran_true_avg, state_labels, state_labels) + ggtitle("Transition Residuals (mean)")
GenerateTable(tran_avg_adj - tran_true_avg, tran_true_avg, tran_sd, tran_true_count_med,"Transition (Median)")
```

```{r}
colpo_pos <- c(2,4,6,8,10,12,14,16,18)
class_avg_adj <- class_avg
class_avg_adj[colpo_pos,] <- class_true_avg[colpo_pos,]
ClassificationHeatmap(class_avg_adj - class_true_avg, state_labels, state_labels) + ggtitle("Transition Residuals (mean)")
GenerateTable(class_avg_adj - class_true_avg, class_true_avg, class_sd, class_true_count_med,"Transition (Median)")
```

```{r}
init_counts <- as.vector(init_true_count_med)
init_bias <- abs(as.vector(init_avg - init_true_avg))
init_nz <- which(init_counts != 0)
init_counts <- init_counts[init_nz]
init_bias <- init_bias[init_nz]
plot(x = init_counts, y = init_bias)

tran_counts <- tran_true_count_med
# tran_counts[seq(2,18,2),] <- 0
tran_counts <- as.vector(tran_counts)
tran_bias <- abs(as.vector(tran_avg - tran_true_avg))
tran_nz <- which(tran_counts != 0)
tran_counts <- tran_counts[tran_nz]
tran_bias <- tran_bias[tran_nz]
plot(x = tran_counts, y = tran_bias)

class_counts <- as.vector(class_true_count_med)
class_bias <- abs(as.vector(class_avg - class_true_avg))
class_nz <- which(class_counts != 0)
class_counts <- class_counts[class_nz]
class_bias <- class_bias[class_nz]
plot(x = class_counts, y = class_bias)


total_counts <- c(init_counts, tran_counts, class_counts)
total_bias <- c(init_bias, tran_bias, class_bias)
plot(x = total_counts, y = total_bias, ylim = c(0,.55))
plot(x = total_counts_nm, y = total_bias_nm, ylim = c(0,.55))
```




```{r}

Captured <- function(bias, standard_error){
  if (bias == 0 & standard_error == 0){
    return(T)
  }
  abs_bias <- abs(bias)
  if (standard_error * 1.96 > abs_bias){return(T)}
  else {return(F)}
}

library(xtable)
new_order <- c(1,3,5,7,9,11,13,15,17,2,4,6,8,10,12,14,16,18)


big_rows <- 18
small_rows <- 4
table <- ""
sig_fig <- 3

#TRAN
true_mat <- tran_true_avg
count_mat <- tran_true_count_avg
bias_mat <- tran_avg - tran_true_avg
ESD_mat <- tran_sd

# #CLASS
# true_mat <- class_true_avg
# count_mat <- class_true_count_med
# bias_mat <- class_avg - class_true_avg
# ESD_mat <- class_sd


adj_state <- "0/0/0"

for (i in 1:big_rows){
  
  if(i == 2){adj_state <-"0/1/0" }
  else if(i == 3){adj_state <- "0/2/0"}
  else if(i == 4){adj_state <- "1/0/0"}
  else if(i == 5){adj_state <- "1/1/0"}
  else if(i == 6){adj_state <- "1/2/0"}
  else if(i == 7){adj_state <- "2/0/0"}
  else if(i == 8){adj_state <- "2/1/0"}
  else if(i == 9){adj_state <- "2/2/0"}
  else if(i == 10){adj_state <- "0/0/1"}
  else if(i == 11){adj_state <- "0/1/1"}
  else if(i == 12){adj_state <- "0/2/1"}
  else if(i == 13){adj_state <- "1/0/1"}
  else if(i == 14){adj_state <- "1/1/1"}
  else if(i == 15){adj_state <- "1/2/1"}
  else if(i == 16){adj_state <- "2/0/1"}
  else if(i == 17){adj_state <- "2/1/1"}
  else if(i == 18){adj_state <- "2/2/1"}
  
  for (j in 1:small_rows){
    
    if (j == 1){
     table <- paste(table, "\\multicolumn{1}{c|}{}", "&", "Truth", "&")
     table <- paste0(table, "\\multicolumn{1}{c|}{\\multirow{4}{*}{", adj_state, "}}")
     for (k in 1:big_rows){
       table <- paste(table, "&", round(true_mat[new_order,new_order][i,k],sig_fig))
      }
    }
    
    if (j == 2){
     table <- paste(table, "\\multicolumn{1}{c|}{}", "&", "N", "&", "\\multicolumn{1}{c|}{}")
     for (k in 1:big_rows){
       table <- paste(table, "&", ceiling(count_mat[new_order,new_order])[i,k])
      }
    }
    
    if (j == 3){
     table <- paste(table, "\\multicolumn{1}{c|}{}", "&", "Bias", "&", "\\multicolumn{1}{c|}{}")
     for (k in 1:big_rows){
       if (Captured(bias_mat[new_order,new_order][i,k],ESD_mat[new_order,new_order][i,k])){
         table <- paste(table, "&", round(bias_mat[new_order,new_order][i,k],sig_fig))
       } else {
         table <- paste0(table, " & ", round(bias_mat[new_order,new_order][i,k],sig_fig), "^*")
       }
       
      }
    }
    
    if (j == 4){
     table <- paste(table, "\\multicolumn{1}{c|}{}", "&", "CI", "&", "\\multicolumn{1}{c|}{}")
     for (k in 1:big_rows){
       
       
        lb <- (bias_mat[new_order,new_order][i,k] + true_mat[new_order,new_order][i,k]) - 1.96 * ESD_mat[new_order,new_order][i,k]
        ub <- (bias_mat[new_order,new_order][i,k] + true_mat[new_order,new_order][i,k]) + 1.96 * ESD_mat[new_order,new_order][i,k]
        if (lb < 0){lb <- 0}
        if (ub > 1){ub <- 1}
       
       
       if (true_mat[new_order,new_order][i,k] == 0){
         table <- paste(table, "& - ")
       } else {
         table <- paste0(table, "& (", round(lb,sig_fig), "-", round(ub,sig_fig), ") ")
       }
      }
    }
    
    table <- paste(table ," \\\\ ")
    if (j == 4){table <- paste(table , "\\cmidrule(l){2-21} ")}
    table <- paste(table, "\n")
  }
}

cat(table)
```