---
title: "Parsing Real"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, include = FALSE, eval = FALSE}
setwd("../Paper/Data/EM Estimates 18 Norm /")
states <- 18
list_of_names <- list.files()
reps <- length(list_of_names)
getwd()

init_init_array <- array(0,dim = c(1,states,reps))
tran_init_array <- array(0,dim = c(states,states,reps))
class_init_array <- array(0,dim = c(states,states,reps))

init_est_array <- array(0,dim = c(1,states,reps))
tran_est_array <- array(0,dim = c(states,states,reps))
class_est_array <- array(0,dim = c(states,states,reps))

likelihood_array <- numeric(reps)
pi_init_array <- numeric(reps)
pi_est_array <- numeric(reps)
time_array <- numeric(reps)

init_init_list <- vector("list", length = reps)
tran_init_list <- vector("list", length = reps)
class_init_list <- vector("list", length = reps)

init_est_list <- vector("list", length = reps)
tran_est_list <- vector("list", length = reps)
class_est_list <- vector("list", length = reps)

count <- 1

for (name in list_of_names){
  load(name)
  
  init_parameters <- to_save[[1]]
  est_parameters <- to_save[[2]]
  likelihood_array[count] <- to_save[[3]]
  # time_array[count] <- to_save[[4]] / (60 * 60 * 24)
  
  pi_init_array[count] <- init_parameters[[4]]
  pi_est_array[count] <- est_parameters[[4]]
  
  init_init_list[[count]] <- init_parameters[[1]]
  tran_init_list[[count]] <- init_parameters[[2]]
  class_init_list[[count]] <- init_parameters[[3]]
  
  init_est_list[[count]] <- est_parameters[[1]]
  tran_est_list[[count]] <- est_parameters[[2]]
  class_est_list[[count]] <- est_parameters[[3]]
  
  
  
  
  for (i in 1:states){
    init_init_array[1,i,count] <- init_init_list[[count]][i]
    init_est_array[1,i,count] <- init_est_list[[count]][i]
    
    for (j in 1:states){
      tran_init_array[i,j,count] <- tran_init_list[[count]][i,j]
      tran_est_array[i,j,count] <- tran_est_list[[count]][i,j]
      
      class_init_array[i,j,count] <- class_init_list[[count]][i,j]
      class_est_array[i,j,count] <- class_est_list[[count]][i,j]
    }
  }
  
  count <- count + 1
}


#############################################

first <- which.max(likelihood_array)

est_init <- init_est_array[1,,first]
est_tran <- tran_est_array[,,first]
est_class <- class_est_array[,,first]
est_pi <- pi_est_array[first]

#############################################

setwd("..")
setwd("Bootstrap 18 MC")
count <- 1
list_of_names <- list.files()
reps <- length(list_of_names)

init_sd <- numeric(states)
tran_sd <- matrix(0,states,states)
class_sd <- matrix(0,states,states)
pi_sd <- 0

init_est_array <- array(0,dim = c(1,states,reps))
tran_est_array <- array(0,dim = c(states,states,reps))
class_est_array <- array(0,dim = c(states,states,reps))
pi_est_array <- numeric(reps)

for (name in list_of_names){
  load(name)
  est_parameters <- to_save[[2]]

  init_est_list[[count]] <- est_parameters[[1]]
  tran_est_list[[count]] <- est_parameters[[2]]
  class_est_list[[count]] <- est_parameters[[3]]
  pi_est_array[count] <- est_parameters[[4]]

  for (i in 1:states){
    init_est_array[1,i,count] <- init_est_list[[count]][i]

    for (j in 1:states){
      tran_est_array[i,j,count] <- tran_est_list[[count]][i,j]
      class_est_array[i,j,count] <- class_est_list[[count]][i,j]
    }
  }
  count <- count + 1
}

boot_init <- numeric(states)
boot_tran <- matrix(0,states,states)
boot_class <- matrix(0,states,states)
for (i in 1:states){
  boot_init[i] <- mean(init_est_array[1,i,])
  for (j in 1:states){
    boot_tran[i,j] <- mean(tran_est_array[i,j,])
    boot_class[i,j] <- mean(class_est_array[i,j,])
  }
}

for (i in 1:reps){
  init_sd <- init_sd + (init_est_array[1,,i] - boot_init)^2
  tran_sd <- tran_sd + (tran_est_array[,,i] - boot_tran)^2
  class_sd <-class_sd + (class_est_array[,,i] - boot_class)^2
  pi_sd <- pi_sd + (pi_est_array[i] - mean(pi_est_array))^2
}

init_sd <- sqrt(init_sd / (reps - 1))
tran_sd <- sqrt(tran_sd / (reps - 1))
class_sd <- sqrt(class_sd / (reps - 1))
pi_sd <- sqrt(pi_sd / (reps - 1))
```

```{r, echo = FALSE, fig.width=15, fig.height=15}
ClassificationHeatmap <- function(X_tran, state_labels = c(0:17), adj_labels){
  library(reshape)
  library(ggplot2)
  rownames(X_tran) <- c(state_labels)
  colnames(X_tran) <- c(state_labels)
  X_tran.m <- melt(X_tran)
  X_tran.m$X1 <- factor(X_tran.m$X1, levels = rev(adj_labels))
  X_tran.m$X2 <- factor(X_tran.m$X2, levels = (adj_labels))
  ggplot(X_tran.m,aes(X2, X1)) + 
    geom_tile(aes(fill = value),color = "white") + 
    scale_fill_gradient2(low = "blue",high = "red") +
    labs(x = "New State", y = "Initial State", caption = "Observed - True") + 
    theme(axis.text.y = element_text(size = 10), axis.text.x = element_text(size = 10, angle = 90, vjust = 0.5)) + 
    theme(axis.text.x = element_text(angle = 0)) + 
    theme(axis.title.y = element_text(margin = margin(t = 0, r = 20, b = 0, l = 0))) + 
    theme(axis.title.x = element_text(margin = margin(t = 20, r = 0, b = 0, l = 0))) +
    theme(plot.caption = element_text(hjust = .5))
}
```

```{r}
GenerateInitTable <- function(init, init_var, title){
  library(knitr)
  library(kableExtra)
  combined_mat <- rbind(init, init_var)
  rownames(combined_mat) <- c("Estimate", "Std Dev")
  colnames(combined_mat) <- c(0:(length(init) -1))
  
  kable(combined_mat, caption = title) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = T) %>%
    group_rows("State 0",1,2) 
}
```

```{r}
GenerateInitTableSolo<- function(init, title){
  library(knitr)
  library(kableExtra)
  combined_mat <- rbind(init)
  rownames(combined_mat) <- c("Estimate")
  colnames(combined_mat) <- c(0:(length(init) -1))
  
  kable(combined_mat, caption = title) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = T) %>%
    group_rows("State 0",1,1) 
}
```

```{r}
GenerateTable <- function(mean_mat,var_mat,title){
  library(knitr)
  library(kableExtra)
  row_names <- c("Estimate", "Std Dev")
  
  length_of_ind <- dim(mean_mat)[1]
  combined_mat <- matrix(0,length_of_ind*2, length_of_ind)
  
  for (i in 1:(length_of_ind * 2)){
    which_one <- i %% 2
    true_ind <- ceiling(i/2)
    if (which_one == 1){
      combined_mat[i,] <- mean_mat[true_ind,]
    } else if (which_one == 0){
      combined_mat[i,] <- var_mat[true_ind,]
    } 
  }
  
  rownames(combined_mat) <- rep(row_names,length_of_ind)

  colnames(combined_mat) <- c(0:(length_of_ind -1))
  
  kable(combined_mat, caption = title) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = T) %>%
    group_rows("State 0",1,2) %>%
    group_rows("State 1",3,4) %>%
    group_rows("State 2",5,6) %>%
    group_rows("State 3",7,8) %>%
    group_rows("State 4",9,10) %>%
    group_rows("State 5",11,12) %>%
    group_rows("State 6",13,14) %>%
    group_rows("State 7",15,16) %>%
    group_rows("State 8",17,18) %>%
    group_rows("State 9",19,20) %>%
    group_rows("State 10",21,22) %>%
    group_rows("State 11",23,24) %>%
    group_rows("State 12",25,26) %>%
    group_rows("State 13",27,28) %>%
    group_rows("State 14",29,30) %>%
    group_rows("State 15",31,32) %>%
    group_rows("State 16",33,34) %>%
    group_rows("State 17",35,36)
    
  
    
}
```

```{r}
GenerateTableSolo <- function(mean_mat,title){
  library(knitr)
  library(kableExtra)
  row_names <- c("Estimate")
  
  length_of_ind <- dim(mean_mat)[1]
  combined_mat <- matrix(0,length_of_ind, length_of_ind)
  combined_mat <- mean_mat
  
  rownames(combined_mat) <- rep(row_names,length_of_ind)

  colnames(combined_mat) <- c(0:(length_of_ind -1))
  
  kable(combined_mat, caption = title) %>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed"), full_width = T) %>%
    group_rows("State 0",1,1) %>%
    group_rows("State 1",2,2) %>%
    group_rows("State 2",3,3) %>%
    group_rows("State 3",4,4) %>%
    group_rows("State 4",5,5) %>%
    group_rows("State 5",6,6) %>%
    group_rows("State 6",7,7) %>%
    group_rows("State 7",8,8) %>%
    group_rows("State 8",9,9) %>%
    group_rows("State 9",10,10) %>%
    group_rows("State 10",11,11) %>%
    group_rows("State 11",12,12) %>%
    group_rows("State 12",13,13) %>%
    group_rows("State 13",14,14) %>%
    group_rows("State 14",15,15) %>%
    group_rows("State 15",16,16) %>%
    group_rows("State 16",17,17) %>%
    group_rows("State 17",18,18)
    
  
    
}
```

```{r}

new_order <- c(1,3,5,7,9,11,13,15,17,2,4,6,8,10,12,14,16,18)

state_labels <- c(0:17)


first <- which.max(likelihood_array)

est_init <- init_est_array[1,,first]
est_tran <- tran_est_array[,,first]
est_class <- class_est_array[,,first]
est_pi <- pi_est_array[first]

parameters <- list(est_init, est_tran,est_class,est_pi)

ClassificationHeatmap(est_tran, state_labels, state_labels) + ggtitle("Transition")

ClassificationHeatmap(est_class, state_labels, state_labels) + ggtitle("Classification")

# GenerateInitTableSolo(est_init, "Initial ")
# 
# GenerateTableSolo(est_tran,"Transition ")
# 
# GenerateTableSolo(est_class,"Classification ")

GenerateInitTable(est_init, init_sd, "Initial")

GenerateTable(est_tran, tran_sd,"Transition")

GenerateTable(est_class, class_sd,"Classification")


# fast_est_init <- est_init
# fast_est_tran <- est_tran
# fast_est_class <- est_class
```



```{r}
library(xtable)
new_order <- c(1,3,5,7,9,11,13,15,17,2,4,6,8,10,12,14,16,18)


big_rows <- 18
table <- ""
sig_fig <- 2
# load("parameters.rda")
#TRAN
true_mat <- est_tran
sd_mat <- tran_sd
hc_mat <- matrix(T,18,18)
hc_mat[1:6,13:18] <- F
hc_mat[7:18,7:12] <- F
hc_mat[new_order,new_order][10:18,1:9] <- F

#CLASS
# true_mat <- est_class
# sd_mat <- class_sd
# hc_mat <- matrix(F,18,18)
# hc_mat[1:6,1:6] <- T
# hc_mat[7:12,7:12] <- T
# hc_mat[13:18,13:18] <- T
# hc_mat[c(new_order[1:9]),c(new_order[10:18])] <- F

adj_state <- "(0,0,0)"

for (i in 1:big_rows){
  
  if(i == 2){adj_state <-"(0,1,0)"}
  else if(i == 3){adj_state <- "(0,2,0)"}
  else if(i == 4){adj_state <- "(1,0,0)"}
  else if(i == 5){adj_state <- "(1,1,0)"}
  else if(i == 6){adj_state <- "(1,2,0)"}
  else if(i == 7){adj_state <- "(2,0,0)"}
  else if(i == 8){adj_state <- "(2,1,0)"}
  else if(i == 9){adj_state <- "(2,2,0)"}
  else if(i == 10){adj_state <- "(0,0,1)"}
  else if(i == 11){adj_state <- "(0,1,1)"}
  else if(i == 12){adj_state <- "(0,2,1)"}
  else if(i == 13){adj_state <- "(1,0,1)"}
  else if(i == 14){adj_state <- "(1,1,1)"}
  else if(i == 15){adj_state <- "(1,2,1)"}
  else if(i == 16){adj_state <- "(2,0,1)"}
  else if(i == 17){adj_state <- "(2,1,1)"}
  else if(i == 18){adj_state <- "(2,2,1)"}

    
 table <- paste(table, "\\multicolumn{1}{c|}{}", "&")
 table <- paste0(table, " \\multicolumn{1}{c|}{", adj_state, "}")
 for (k in 1:big_rows){
   
    lb <- (true_mat[new_order,new_order][i,k]) - 1.96 * sd_mat[new_order,new_order][i,k]
    ub <- (true_mat[new_order,new_order][i,k]) + 1.96 * sd_mat[new_order,new_order][i,k]
    if (lb < 0){lb <- 0}
    if (ub > 1){ub <- 1}
   
    capt <- F
    if (!true_mat[new_order,new_order][i,k] > ub & !true_mat[new_order,new_order][i,k] < lb){capt <- T}
    
    if (k != 9){
      if (!capt){
        table <- paste0(table, "& ", round(true_mat[new_order,new_order][i,k],sig_fig, "^* "))
      } else {table <- paste(table, "& ", round(true_mat[new_order,new_order][i,k],sig_fig))}
      
      if (hc_mat[new_order,new_order][i,k]){
        # table <- paste0(table, "(", round(lb,sig_fig), "-", round(ub,sig_fig) ,") ")
        table <- paste0(table, "(", round(sd_mat[new_order,new_order][i,k],sig_fig) ,") ")
      } 
     
    } else {
      if (!capt){
        table <- paste0(table, "& \\multicolumn{1}{c|}{", round(true_mat[new_order,new_order][i,k],sig_fig), "^*")
      } else {table <- paste0(table, "& \\multicolumn{1}{c|}{", round(true_mat[new_order,new_order][i,k],sig_fig))}
      
     
      if (hc_mat[new_order,new_order][i,k]){
        # table <- paste0(table, "(", round(lb,sig_fig), "-", round(ub,sig_fig) ,")} ")
        table <- paste0(table, "(", round(sd_mat[new_order,new_order][i,k],sig_fig) ,")} ")
      } else {table <- paste0(table, "} ")}
    }
  }
  
  
  table <- paste(table," \\\\ ")
  if (i == 9){table <- paste(table , "\\cmidrule(l){3-20} ")}
  table <- paste(table, "\n")
}

cat(table)
```
