---
title: "Risk"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# load("parameters.rda")
# est_init <- to_save[[2]][[1]]
# est_tran <- to_save[[2]][[2]]
# est_class <- to_save[[2]][[3]]
# est_pi <- to_save[[2]][[4]]

# est_init <- init_est_array[,,23]
# est_tran <- tran_est_array[,,23]
# est_class <- class_est_array[,,23]
# est_pi <- pi_est_array[23]

```

```{r}
forw <- apply(ALTS,1,ForwardIterFull, time = 5, est_init,est_tran,est_class)
backw <- apply(ALTS,1,FUN = BackwardIterFull, time = 1, est_tran, est_class)
to_remove <- numeric(18)
k <- c(1:18)
for (ind in 1:dim(copa)[1]){
  seen_copa <- F
  forward <- forw[[ind]]
  backward <- backw[[ind]]
  for (time in 1:dim(copa)[2]){
    
    if (time != 5){current_backw_length <- dim(GetAllPossibilitiesBackw(ALTS[ind,,],time+1))[2]} 
    else {current_backw_length <- 1}
    current_forw_length <- dim(GetAllPossibilitiesForw(ALTS[ind,,],time-1))[2]
    forward_sum <- numeric(length(k))
    backward_sum <- numeric(length(k))
    
    for (u in 1:current_forw_length){
      forward_sum <- forward_sum + forward[[u]][[time]]
    }

    if (time == dim(ALTS)[2]){
      backward_sum <- rep(1, length(k))
    } else {
      for (v in 1:current_backw_length){
        backward_sum <- backward_sum + backward[[v]][[time]]
      }
    }
    
    
    if (seen_copa){
      if (sum(forward_sum) != 0){
        to_remove <- to_remove + (forward_sum * backward_sum) / sum(forward_sum * backward_sum)
      }
    }
    if (!is.na(copa[ind,time])){
      if (copa[ind,time] == 1){
        seen_copa <- T
      }
    }
  }
}

```

```{r}

RiskCalculator <- function(init, tran, class, pi, latent_states){
  if (missing(latent_states)){
    p_latent <- (init + init %*% tran + init %*% tran %*% tran + init %*% tran %*% tran %*% tran + init %*% tran %*% tran %*% tran %*% tran)
    latent_states <- p_latent * 3488 
    latent_states <- latent_states
  }
  risk <- numeric(states/2)
  latent_states_colpo <- latent_states
  latent_states_colpo[seq(1,states,2)] <- 0
  obs_states <-  latent_states %*% class
  obs_states_colpo <- latent_states_colpo %*% class
  
  for (i in 1:9){
    risk[i] <-(obs_states_colpo[2*i - 1] + obs_states_colpo[2*i])/(obs_states[2*i - 1] + obs_states[2*i])
  }
  
  return(risk)
  
}


p_latent <- (est_init + est_init %*% est_tran + est_init %*% est_tran %*% est_tran + est_init %*% est_tran %*% est_tran %*% est_tran + est_init %*% est_tran %*% est_tran %*% est_tran %*% est_tran)
latent_states <- p_latent * 3488 
latent_states <- latent_states - to_remove

est_risk <- RiskCalculator(est_init,est_tran,est_class,est_pi, latent_states)

risk_ci_lb <- est_risk - (1.96 * risk_sd)
risk_ci_ub <- est_risk + (1.96 * risk_sd)

risk_ci_lb[risk_ci_lb < 0] <- 0
risk_ci_ub[risk_ci_ub > 1] <- 1

round(risk_ci_lb,3)
round(risk_ci_ub,3)

```




```{r}

```

```{r}

# est_init <- parameters2[[1]]
# est_tran <- parameters2[[2]]
# est_class <- parameters2[[3]]
# est_pi <- parameters2[[4]]

forw <- apply(ALTS_pattern,1,ForwardIterFull, time = 5, est_init,est_tran,est_class)
backw <- apply(ALTS_pattern,1,FUN = BackwardIterFull, time = 1, est_tran,est_class)
CalcHiddenCount <- function(data,freq_vec, pi_0, forw, backw, time, class){
  k <- numOfStates(data)
  prob_list <- numeric(length(k))

  for (i in 1:dim(data)[1]){
    forward <- forw[[i]]
    backward <- backw[[i]]
    
    forward_sum <- numeric(length(k))
    backward_sum <- numeric(length(k))
    
    forw_length <- dim(GetAllPossibilitiesForw(data[i,,],1))[2]
    if (time != dim(data)[2]){current_backw_length <- dim(GetAllPossibilitiesBackw(data[i,,],time+1))[2]
    } else {current_backw_length <- 1}
    
    for (u in 1:forw_length){
     forward_sum <- forward_sum + forward[[u]][[time]] 
    }
    for (v in 1:length(current_backw_length)){
     backward_sum <- backward_sum + backward[[v]][[time]] 
    }
    
    mover <- forward_sum * backward_sum 
    mover <- (mover / sum(mover)) * (1 - pi_0)
    prob_list <- prob_list + (mover * freq_vec[i])
  }
  prob_list[1] <- prob_list[1] #+ (sum(freq_vec) * pi_0)
  return(prob_list)
} 

init_lat <- CalcHiddenCount(ALTS_pattern,freq_vec,est_pi,forw,backw,1,est_class)
      
# xtable(round(cbind(c(CalcHiddenCount(ALTS_pattern,freq_vec,est_pi,forw,backw,1,est_class) + CalcHiddenCount(ALTS_pattern,freq_vec,est_pi,forw,backw,2,est_class) + CalcHiddenCount(ALTS_pattern,freq_vec,est_pi,forw,backw,3,est_class) + CalcHiddenCount(ALTS_pattern,freq_vec,est_pi,forw,backw,4,est_class) + CalcHiddenCount(ALTS_pattern,freq_vec,est_pi,forw,backw,5,est_class)), c(CalcHiddenCount(ALTS_pattern,freq_vec,est_pi_n,forw,backw,1,est_class_n) + CalcHiddenCount(ALTS_pattern,freq_vec,est_pi_n,forw,backw,2,est_class_n) + CalcHiddenCount(ALTS_pattern,freq_vec,est_pi_n,forw,backw,3,est_class_n) + CalcHiddenCount(ALTS_pattern,freq_vec,est_pi_n,forw,backw,4,est_class_n) + CalcHiddenCount(ALTS_pattern,freq_vec,est_pi_n,forw,backw,5,est_class_n)))))

```

```{r}
# forw <- apply(ALTS_pattern,1,ForwardIterFull, time = 4, init,tran,class)
# backw <- apply(ALTS_pattern,1,FUN = BackwardIterFull, time = 2, tran, class)
# likelihoods <- apply(ALTS_pattern,1,FUN = CalcIndLikelihood, est_init, est_tran, est_class,est_pi)

CalcHiddenTranCount <- function(data, tran,class,freq_vec, pi_0, forw, backw, likelihoods){
  
  k <- numOfStates(data)
  tran_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
  possible_initial_states <- c(1,3,5,7,9,11)
  possible_initial_states_copa <- c(2,4,6,8,10,12)
  
  for (ind in 1:dim(data)[1]){
    forward <- forw[[ind]]
    backward <- backw[[ind]]
    denom <- likelihoods[[ind]]
    for (time in 2:dim(data)[2]){
      tran_matrix_current <- matrix(0L, nrow = length(k), ncol = length(k))
      possible_x <- unique(GetAllPossibilitiesBackw(data[ind,,], time)[1,])
      
      if (time != 5){current_backw_length <- dim(GetAllPossibilitiesBackw(data[ind,,],time+1))[2]} 
      else {current_backw_length <- 1}
      
      current_forw_length <- dim(GetAllPossibilitiesForw(data[ind,,],time-1))[2]
      
      
      forward_sum <- numeric(length(k))
      backward_sum <- numeric(length(k))
      
      
      for (u in 1:current_forw_length){
        forward_sum <- forward_sum + forward[[u]][[time-1]]
      }
      
      
      if (time == dim(data)[2]){
        backward_sum <- rep(1, length(k))
      } else {
        for (v in 1:current_backw_length){
          backward_sum <- backward_sum + backward[[v]][[time]]
        }
      }
      
      for(gX in possible_x){ 
        
        for (initial_state in possible_initial_states){
          if (initial_state < 4){possible_new_states <- c(1:8)}
          else {possible_new_states <- c(1:4,9:12)}
          
          for(new_state in possible_new_states){
            
            num <- forward_sum[[initial_state]] * backward_sum[[new_state]] * tran[initial_state,new_state] * Classification(gX,new_state-1,class) * (1 - pi_0)
            if(denom != 0){
              tran_matrix_current[initial_state,new_state] <- tran_matrix_current[initial_state,new_state] + (num/denom)
            } 
          }
        }
        
        for (initial_state in possible_initial_states_copa){
          if (initial_state < 5){possible_new_states <- c(2,4,6,8)}
          else {possible_new_states <- c(2,4,10,12)}
          
          for(new_state in possible_new_states){
            
            num <- forward_sum[[initial_state]] * backward_sum[[new_state]] * tran[initial_state,new_state] * Classification(gX,new_state-1,class) * (1 - pi_0)
            if(denom != 0){
              tran_matrix_current[initial_state,new_state] <- tran_matrix_current[initial_state,new_state] + (num/denom)
            } 
          }
        }
        
        
      }
      tran_matrix <- tran_matrix + ((tran_matrix_current) * freq_vec[ind])
    }
  }
  return(tran_matrix)
}

tran_num <- CalcHiddenTranCount(ALTS_pattern,est_tran,est_class,freq_vec,est_pi,forw,backw,likelihoods)
```

```{r}
# forw <- apply(ALTS_pattern,1,ForwardIterFull, time = 5, init,tran,class)
# backw <- apply(ALTS_pattern,1,FUN = BackwardIterFull, time = 1, tran, class)
# likelihoods <- apply(ALTS_pattern,1,FUN = CalcIndLikelihood, init, tran, class,pi)

CalcHiddenClassCount <- function(data,class, freq_vec, forw, backw, likelihoods, pi_0){
  k <- numOfStates(data)
  num_matrix_full <- matrix(0L, nrow = length(k), ncol = length(k))
  for (ind in 1:dim(data)[1]){
    
    forward <- forw[[ind]]
    backward <- backw[[ind]]
    individual_likelihood <- likelihoods[[ind]]
    
    for(time in 1:dim(data)[2]){
      num_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
      
      if (time != dim(data)[2]){current_backw_length <- dim(GetAllPossibilitiesBackw(data[ind,,],time+1))[2]} 
      else {current_backw_length <- 1}
      current_forw_length <- dim(GetAllPossibilitiesForw(data[ind,,],time))[2]

      
      
      beggining_forw <- GetAllPossibilitiesForw(data[ind,,],time)
      if (time != dim(data)[2]){
        ending_backw <- GetAllPossibilitiesBackw(data[ind,,],(time+1))
      }
      x_vals <- unique(beggining_forw[time,])
      
      for (u in 1:current_forw_length){
        x_val <- beggining_forw[time,u]
        for (v in 1:current_backw_length){
          if (!is.na(x_val)){
            
            if (time != dim(data)[2]){
              chain <- c(beggining_forw[,u], as.vector(ending_backw[,v]))
            } else {
              chain <- beggining_forw[,u]
            }
            
            mover <- (forward[[u]][[time]]*backward[[v]][[time]] * (1 - pi_0) / individual_likelihood)
            if (individual_likelihood == 0){
              print(ind)
            }
            
            stayer <- (pi_0 * CalcProdIndAlt(chain,class)) / individual_likelihood
            
            mover_stayer <- mover
            mover_stayer[1] <- mover_stayer[1] + stayer
            
            for (y_state in 1:length(k)){   
              num_matrix[y_state,x_val + 1] <- num_matrix[y_state, x_val+1] + mover_stayer[y_state]
            }
          }
        }
      }
      
      
      #Normalization for partial
      if (sum(num_matrix) != 0){
        num_matrix <- num_matrix/sum(num_matrix)
      }
      num_matrix_full <- num_matrix_full + (num_matrix * freq_vec[ind])
      
    }
  }
  
  return(num_matrix_full)
}

class_num <- CalcHiddenClassCount(ALTS_pattern,est_class,freq_vec,forw,backw,likelihoods,est_pi)
```

```{r}
ALTS1 <- ALTS[,1,]
init_obs <- numeric(12)
part_miss <- 0
fully_miss <- 0

for (i in 1:dim(ALTS1)[1]){
  denom <- sum(!is.na(ALTS1[y,]))
  if (denom == 0){fully_miss <- fully_miss + 1}
  if (denom > 1){part_miss <- part_miss + 1}
  for (j in 1:denom){
    init_obs[ALTS1[i,j]+1] <- init_obs[ALTS1[i,j]+1] + 1/denom
  }
}
```


```{r}
beginning_zero <- 0
entered_colpo <- 0
for (i in 1:dim(ALTS)[1]){
  if (!is.na(ALTS[i,1,1]) & ALTS[i,1,1] == 0 & is.na(ALTS[i,1,2])){
    beginning_zero <- beginning_zero + 1
    for (j in 2:dim(ALTS)[2]){
      if (!is.na(ALTS[i,j,1]) & ALTS[i,j,1] %% 2 == 1){
        entered_colpo <- entered_colpo + 1
      }
    }
  }
}

```

