---
title: "Reduced State Space Sim"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
-------------------------
```{r}
Normalize <- function(data){
  for (i in 1:dim(data)[1]){
    if (sum(data[i,],na.rm = TRUE) != 0){
      data[i,] <- data[i,]/sum(data[i,])
    }
  }
  return(data)
}
```

```{r}
numOfStates <- function(data,type){
  if (missing(type)){
    return(c(0:2))
  }
  else if (type == 1){
    return (c(0:3))
  } else if (type == 2){
    return(c(0:2))
  } else if (type == 3){
    return (c(0:1))
  }else if (type == 4){
    return(c(0:23))
  }else if (missing(type)){
    return (c(min(data, na.rm = T):max(data, na.rm = T)))
  }
  
}
```

```{r}
GenerateData <- function(n,t,p){
  data_mat <- matrix(0L, nrow = n, ncol = t)
  stayer_vec <- rbinom(n,1,p)
  
  for (i in 1:n){
    if (stayer_vec[i] == 0){
      data_mat[i,1] <- which(rmultinom(1,1,init_hc) == 1) - 1
      for (j in 2:t){
        p_current <- tran_hc[data_mat[i,j-1]+1,]
        data_mat[i,j] <- which(rmultinom(1,1,p_current) == 1) - 1
      }
    }
  }
  return(list(data_mat, stayer_vec))
}
```

```{r}
GenerateObs <- function(data_true){
  data_obs <- matrix(0L, nrow = dim(data_true)[1], ncol = dim(data_true)[2])
  for (i in 1:dim(data_true)[1]){
    for (j in 1:dim(data_true)[2]){
      if(!is.na(data_true)[i,j]){
        p_current <- class_hc[data_true[i,j]+1,]
        new_val <- which(rmultinom(1,1,p_current) == 1) - 1
        data_obs[i,j] <- new_val
      }
    }
  }
  return(data_obs)
}
```

```{r}
GenerateObsPartial <- function(data_true, data_obs){
  for (i in 1:dim(data_true)[1]){
    for (j in 1:dim(data_true)[2]){
      if (!is.na(data_obs[i,j]) & !is.na(data_true[i,j])){
        if (rbinom(1,1,3/10) == 1){
          if (data_true[i,j] == 0){
            rand <- runif(1)
            if (rand < (class_hc[1,1] + class_hc[1,2])/2){
              data_obs[i,j] <- 3
            } else if (rand < (class_hc[1,1] + class_hc[1,2] + class_hc[1,1] + class_hc[1,3])/2) {
              data_obs[i,j] <- 4
            } else {
              data_obs[i,j] <- 5
            }
          } else if (data_true[i,j] == 1){
            rand <- runif(1)
            if (rand < (class_hc[2,1] + class_hc[2,2])/2) {
              data_obs[i,j] <- 3
            } else if(rand < (class_hc[2,1] + class_hc[2,2] + class_hc[2,2] + class_hc[2,3])/2) {
              data_obs[i,j] <- 5
            } else {
              data_obs[i,j] <- 4
            }
          } else {
            rand <- runif(1)
            if (rand < (class_hc[3,2] + class_hc[3,3])/2) {
              data_obs[i,j] <- 5
            } else if(rand < (class_hc[3,2] + class_hc[3,3] + class_hc[3,3] + class_hc[3,1])/2) {
              data_obs[i,j] <- 4
            } else {
              data_obs[i,j] <- 3
            }
          }
        }
      }
    }
  }
  return(data_obs)
}
```


```{r}
IntroNA <- function(data, obs, class, data_t){

  for (i in 1:dim(data)[1]){
    for (j in 1:dim(data)[2]){
      
      if (!is.na(data[i,j])){
        if (obs == TRUE){
          #Probability to be missing
          if (rbinom(1,1,0) == 1){
            data[i,j] <- NaN
          }
        } 
      }
      
      if(!is.na(data[i,j])){
        if (data[i,j] == 2){
          if (j < dim(data)[2]){
            data[i,(j+1):dim(data)[2]] <- NaN
          }
        }
      }
    }
  }
  return(data)
}
```

```{r}
GetPatterns <- function(states){
  library(plyr)
  options(scipen = 999)
  vals <- rep(NaN,dim(states)[1])
  for (i in 1:dim(states)[1]){
    val <- ""
    for(j in 1:dim(states)[2]){
      if (!is.na(states[i,j])){
        states_val <- states[i,j] 
      } else {
        states_val <- 6
      }
      val <- paste0(val, states_val)
    }
    
    vals[i] <- val
  }
  return(vals)
}
```

```{r}
Pattern2Data <- function(unique_patterns){
  time_length <- 5
  n <- dim(unique_patterns)[1]
  freq_vec <- numeric(n)
  state_mat <- matrix(0,n,time_length)
  for (i in 1:n){
    freq_vec[i] <- unique_patterns$Freq[[i]]
    pattern <- unique_patterns$all_patterns[[i]]

    for (time in 1:time_length){
      new_val <- as.integer(substr(pattern, time,time))
      if (new_val == 6){
        new_val <- NaN
      }
      state_mat[i,time] <- new_val
    }
  }

  return(list(state_mat, freq_vec))
}

```

```{r}
Data2Array <- function(data){
  data_array <- array(NaN, dim = c(dim(data)[1],dim(data)[2],2))
  for (i in 1:dim(data)[1]){
    for (j in 1:dim(data)[2]){
      
      if (!is.na(data[i,j])){
        
        if (data[i,j] == 0 | data[i,j] == 1 | data[i,j] == 2){
          data_array[i,j,1] <- data[i,j]
        }
        else if (data[i,j] == 3){
          data_array[i,j,1] <- 0
          data_array[i,j,2] <- 1
        }
        else if (data[i,j] == 4){
          data_array[i,j,1] <- 0
          data_array[i,j,2] <- 2
        }
        else if (data[i,j] == 5){
          data_array[i,j,1] <- 1
          data_array[i,j,2] <- 2
        }
        
      } 
      
    }
  }
  return(data_array)
}
```

```{r}
CalcTrueMisclassNoNA <- function(data,true_data){
  misclass_mat <- matrix(0,3,3)
  for (i in 1:dim(data)[1]){
    for (j in 1:dim(data)[2]){
      if (!is.na(data[i,j]) & !is.na(true_data[i,j])){
        if (data[i,j] < 3){
          misclass_mat[true_data[i,j]+1,data[i,j]+1] <- misclass_mat[true_data[i,j]+1,data[i,j]+1] + 1
        } else if (data[i,j] == 3){
          misclass_mat[true_data[i,j]+1,1] <- misclass_mat[true_data[i,j]+1,1] + 1/2
          misclass_mat[true_data[i,j]+1,2] <- misclass_mat[true_data[i,j]+1,2] + 1/2
        } else if (data[i,j] == 4){
          misclass_mat[true_data[i,j]+1,1] <- misclass_mat[true_data[i,j]+1,1] + 1/2
          misclass_mat[true_data[i,j]+1,3] <- misclass_mat[true_data[i,j]+1,3] + 1/2
        } else if (data[i,j] == 5){
          misclass_mat[true_data[i,j]+1,2] <- misclass_mat[true_data[i,j]+1,2] + 1/2
          misclass_mat[true_data[i,j]+1,3] <- misclass_mat[true_data[i,j]+1,3] + 1/2
        }
        
      } 
    }
  }
  return(misclass_mat)
}
```

```{r}
NoPattern <- function(data){
  data_array <- array(NaN,dim = c(dim(data)[1], dim(data)[2], 2))
  
  for (i in 1:dim(data)[1]){
    for (j in 1:dim(data)[2]){
      if (!is.na(data[i,j])){
        if (data[i,j] < 3){
          data_array[i,j,1] <- data[i,j]
        } else if (data[i,j] == 3){
         data_array[i,j,1] <- 0
         data_array[i,j,2] <- 1
        } else if (data[i,j] == 4){
         data_array[i,j,1] <- 0
         data_array[i,j,2] <- 2
        } else if (data[i,j] == 5){
         data_array[i,j,1] <- 1
         data_array[i,j,2] <- 2
        } 
      }
    }
  }
  return(data_array)
}
```

```{r}
GetAllPossibilitiesForw <- function(data, time, individual, only_one){

  if (!missing(only_one)){
    return(matrix(data[individual,1:time]))
  }
  possibilities <- matrix(data[individual,1:time,1], nrow = time)
  for (i in 2:dim(data)[3]){
    for (j in 1:time){
      if (!is.na(data[individual,j,i])){
        to_add <- possibilities
        to_add[j,] <- data[individual,j,i]
        possibilities <- cbind(possibilities,to_add)
      }
    }
  }
  # rownames(possibilities) <- c(1:time)
  return(possibilities)
  
}
```


```{r}
#JASA paper method 
ForwardIterFull <- function(data,time,individual,initial_probabilities,transition,class_matrix, only_one){
  k <- numOfStates(data)
  all_pos_obs <- GetAllPossibilitiesForw(data,time, individual,only_one)
  alpha_matrix_pos <- vector("list", dim(all_pos_obs)[2])
  for(pos in 1:dim(all_pos_obs)[2]){
    pos_ob <- all_pos_obs[,pos]
    
    alpha_matrix<-vector("list",time)
    alpha_i <- numeric(length(k))
    
    for (i in 1:time){
      alpha_matrix[[i]] <- alpha_i
    }
    
    
    for (i in 1:length(k)){
      if (!is.na(pos_ob[1])){
        alpha_matrix[[1]][i] <- initial_probabilities[i] * Classification(pos_ob[1],k[i],class_matrix)
      } else {
        alpha_matrix[[1]][i] <- initial_probabilities[i]
      }
    }

    if (time > 1){
      for (i in 2:time){
        for (j in 1:length(k)){
          if (!is.na(pos_ob[i])){
            alpha_matrix[[i]][j] <- (alpha_matrix[[i-1]] %*% transition[,j]) *  Classification(pos_ob[i],k[j],class_matrix)
          } else {
            alpha_matrix[[i]][j] <- (alpha_matrix[[i-1]] %*% transition[,j])
          }
        }
      }
    }
    
    alpha_matrix_pos[[pos]] <- alpha_matrix
    
  }
  
  return(alpha_matrix_pos)
}
```

```{r}
GetAllPossibilitiesBackw <- function(data, time, individual){

  real_time <- time
  possibilities <- matrix(data[individual,time:dim(data)[2],1], nrow = (dim(data)[2] - time + 1))
  for (i in 2:dim(data)[3]){

    for (j in time:dim(data)[2]){
      if (!is.na(data[individual,j,i])){
        to_add <- possibilities
        to_add[(j - time + 1),] <- data[individual,j,i]
        possibilities <- cbind(possibilities,to_add)
      }
    }
  }
  rownames(possibilities) <- c(real_time:dim(data)[2])
  return(possibilities)
}
```

```{r}
#JASA method 
BackwardIterFull <- function(data,time,individual,transition,class_matrix){
  k <- numOfStates(data)
  length <- dim(data)[2]
  
  #Works since Beta only uses X_t+1
  if (time == 5){
    adj_time <- time
  } else{
    adj_time <- time + 1
  }
  
  all_pos_obs <- GetAllPossibilitiesBackw(data,adj_time,individual)
  beta_matrix_pos <- vector("list", dim(all_pos_obs)[2])
  
  for(pos in 1:dim(all_pos_obs)[2]){
    pos_ob <- all_pos_obs[,pos]
    #Want backward length to always be 5 as it makes future indexing easier
    #Add dummy -1 to inflate length
    pos_ob <- append(pos_ob,rep(-1,adj_time-1),0)
  
    beta_i <- numeric(length(k))
    misclass_vector <- numeric(length(k))
    beta_matrix<-vector("list",length)
    
    for (i in 1:length){
      beta_matrix[[i]] <- beta_i
    }
    
    for (i in 1:length(k)){
      beta_matrix[[length]][i] <- 1
    }
    if (time != length) {
      for (i in (length-1):time){
        if (!is.na(pos_ob[i+1])){
          for (l in 1:length(k)){
            misclass_vector[l] <- Classification(pos_ob[i+1],k[l],class_matrix)
          }
          for (j in 1:length(k)){
            beta_matrix[[i]][j] <- sum(beta_matrix[[i+1]] * transition[j,] * misclass_vector,na.rm = TRUE)
          }
        } else {
          for (j in 1:length(k)){
            if (sum(beta_matrix[[i+1]]) == length(k)){
              beta_matrix[[i]][j] <- 1
            } else {
             beta_matrix[[i]][j] <- sum(beta_matrix[[i+1]] * transition[j,]) 
            }
          }
        }
      }
    }
    
    beta_matrix_pos[[pos]] <- beta_matrix
  }
  
  return(beta_matrix_pos)
}
```




```{r}
CalcIndLikelihoodFast <- function(forward, backward, time){
  #If only forward should be time = 5
  
  if(missing(time)){
    time <- 1
  }
  
  
  if (missing(backward) | time == 5){
    forward_sum <- 0
    for (i in 1:length(forward)){
     forward_sum <- forward_sum + sum(forward[[i]][[length(forward[[i]])]])
    }
    return(forward_sum)
  } 
  
  else {
    k <- length(forward[[1]][[1]])
    forward_sum <- numeric(k)
    backward_sum <- numeric(k)
    
    for (i in 1:length(forward)){
     forward_sum <- forward_sum + forward[[i]][[time]]
    }
    for (i in 1:length(backward)){
     backward_sum <- backward_sum + backward[[i]][[time]]
    }
    
    return((backward_sum %*% forward_sum)[[1]])
    
  }
  
}
```

```{r}
CalcLikelihoodPattern <- function(data, initial_probabilities,transition,class_matrix, freq_vec, pi_0){
  likelihood_sum <- 0
  for (i in 1:dim(data)[1]){
    likelihood <- log(CalcIndLikelihood(data,i,initial_probabilities,transition,class_matrix, pi_0)) * freq_vec[i]
    likelihood_sum <- likelihood_sum + likelihood
  }
  return(likelihood_sum)
}
```

```{r}
CalcIndLikelihood <- function(data, individual, initial_probabilities,transition,class_matrix,pi){
  
  forward <- ForwardIterFull(data,dim(data)[2],individual,initial_probabilities,transition,class_matrix)
  
  forward_sum <- 0
  for (i in 1:length(forward)){
   forward_sum <- forward_sum + sum(forward[[i]][[dim(data)[2]]])
  }
  
  likelihood <- (pi * CalcProdInd(data,individual,class)) + ((1 - pi) * forward_sum)
  return(likelihood)
}
```

```{r}
CalcProdInd <- function(data,individual,class_matrix){
  prod_total <- 0
  partial_data_full <- GetAllPossibilitiesForw(pattern_data,dim(data)[2],individual)
  for (chain in 1:dim(partial_data_full)[2]){
    prod <- 1
    partial_data <- partial_data_full[,chain]
    for (j in 1:length(partial_data)){  
      if (!is.na(partial_data[j])){
        prod <- prod * Classification(partial_data[j], 0, class_matrix)
      }
    }
    prod_total <- prod_total + prod
  }
  return(prod_total)
}
``` 

```{r}
CalcProdIndAlt <- function(data,class_matrix){
  prod <- 1
  for (j in 1:length(data)){
    if (!is.na(data[j])){
      prod <- prod * Classification(data[j], 0, class_matrix)
    }
  }
  return(prod)
}
```


```{r}
CalcStayer <- function(data,init,tran,class,freq_vec,pi_0){
  stayer_vec <- numeric(dim(data)[1])
  for (i in 1:dim(data)[1]){
    stayer_vec[i] <- (pi_0 * CalcProdInd(data,i,class) / CalcIndLikelihood(data,i,init,tran,class,pi_0))
  }
  
  pi_0 <- (stayer_vec %*% freq_vec)/n
  return(pi_0[1])
}
```


```{r}
CalcInitialPattern <- function(data, initial_probabilities, transition, class_matrix, freq_vec, pi_0){
    # THE PROBLEM IS THE PLACEMENT OF FREQ VEC 
  #DONT KNOW WHY NEED TO DO MORE TESTING
  k <- numOfStates(data)
  prob_list <- numeric(length(k))
  workaround <- rep(-2,length(k))
  
  for (i in 1:dim(data)[1]){
    forward <- ForwardIterFull(data,1,i,initial_probabilities, transition,class_matrix)
    backward <- BackwardIterFull(data,1,i,transition,class_matrix)
    
    forward_sum <- numeric(length(k))
    backward_sum <- numeric(length(k))
    
    for (k in 1:length(forward)){
     forward_sum <- forward_sum + forward[[k]][[1]] 
    }
    for (k in 1:length(backward)){
     backward_sum <- backward_sum + backward[[k]][[1]] 
    }
    
    mover <- forward_sum * backward_sum * (1 - pi_0) / CalcIndLikelihood(pattern_data,i,initial_probabilities,transition,class_matrix,pi_0)
    workaround <- rbind(workaround,mover)
    
  }
  workaround <- workaround[-1,]
  # return(workaround)
  
  for (i in 1:length(freq_vec)){
    prob_list <- prob_list + (workaround[i,] * freq_vec[i])
  }

  return(prob_list/sum(prob_list))
} 
```



```{r}
CalcTransitionPattern <- function(data, initial, transition,class,freq_vec, pi_0){
  data2 <- data[1:2,,] 
  data2[,,] <- NaN
  k <- numOfStates(data)
  tran_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
  
  for (ind in 1:dim(data)[1]){
    for (time in 2:dim(data)[2]){
      forward <- ForwardIterFull(data, time - 1, ind, initial, transition, class)
      backward <- BackwardIterFull(data, time, ind, transition, class)
      possible_x <- unique(GetAllPossibilitiesBackw(data, time, ind)[1,])
      
      for (u in 1:length(forward)){
        for(v in 1:length(backward)){
          for(gX in possible_x){

            denom <- CalcIndLikelihood(data,ind,initial,transition,class, pi_0)
            for (initial_state in 1:length(k)){
              for(new_state in 1:length(k)){
                
                num <- forward[[u]][[time-1]][[initial_state]] * backward[[v]][[time]][[new_state]] * transition[initial_state,new_state] * Classification(gX,new_state-1,class) * (1 - pi_0)
                if(denom == 0){
                  frac <- 0
                } else {
                  frac <- (num/denom)
                }
                tran_matrix[initial_state,new_state] <- tran_matrix[initial_state,new_state] + (frac * freq_vec[ind])
              }
            }
          }
        }
      }
    }
  }
  return(Normalize(tran_matrix))
}
```


```{r}
CalcClassificationPattern <- function(data,init,tran,class, freq_vec, pi_0){
  k <- numOfStates(data)
  num_matrix_full <- matrix(0L, nrow = length(k), ncol = length(k))
  
  for (ind in 1:dim(data)[1]){
    
    for(time in 1:dim(data)[2]){
      num_matrix <- matrix(0L, nrow = length(k), ncol = length(k))
      
      forward <- ForwardIterFull(data,time,ind,init, tran,class)
      backward <- BackwardIterFull(data,time,ind,tran,class)
      individual_likelihood <- CalcIndLikelihood(data,ind,init,tran,class,pi_0)
      beggining_forw <- GetAllPossibilitiesForw(data,time,ind)
      if (time != dim(data)[2]){
        ending_backw <- GetAllPossibilitiesBackw(data,(time+1),ind)
      }
      x_vals <- unique(beggining_forw[time,])
      
      for (u in 1:length(forward)){
        x_val <- beggining_forw[time,u]
        
        for (v in 1:length(backward)){
          if (!is.na(x_val)){
            
            if (time != dim(data)[2]){
              chain <- c(beggining_forw[,u], as.vector(ending_backw[,v]))
            } else {
              chain <- beggining_forw[,u]
            }
            
            mover <- (forward[[u]][[time]]*backward[[v]][[time]] * (1 - pi_0) / individual_likelihood)
            stayer <- (pi_0 * CalcProdIndAlt(chain,class)) / individual_likelihood
            
            mover_stayer <- mover
            mover_stayer[1] <- mover_stayer[1] + stayer
            
            for (y_state in 1:length(k)){   
              num_matrix[y_state,x_val + 1] <- num_matrix[y_state, x_val+1] + mover_stayer[y_state]
            }
    
            if (u == length(forward) & v == length(backward)){
              # print(num_matrix)
              if (sum(num_matrix) != 0){
                num_matrix <- num_matrix/sum(num_matrix)
              }
              num_matrix_full <- num_matrix_full + (num_matrix * freq_vec[ind])
            }
            
            
            
          }
        }
      }
    }
  }
  return(Normalize(num_matrix_full))
}
```


```{r}
init_hc <- c(.75,.25,0)

tran_hc <- t(matrix(c(.7,.25,.05,.2,.7,.1,0,0,1),3,3))

class_hc <- t(matrix(c(.95,0.04,.01,.05,.95,.01,0,.05,.95),3,3))
# class_hc <- t(matrix(c(1,0,0,0,1,0,0,0,1),3,3))


n <- 3000
t <- 5
p <- .6
data_true_full <- GenerateData(n,t,p)
data_true <- data_true_full[[1]]
stayer_vec_true <- data_true_full[[2]]
data_obs <- GenerateObs(data_true)

class_true_counts <- CalcTrueMisclassNoNA(data_obs,data_true)
class_true <- Normalize(class_true_counts)

data_obs <- GenerateObsPartial(data_true, data_obs)

class_true_counts_partial <- CalcTrueMisclassNoNA(data_obs,data_true)
class_true_partial <- Normalize(class_true_counts_partial)

data_obs_NA <- IntroNA(data_obs,T, class_hc, data_true)

data_true_NA <- IntroNA(data_true,F, class_hc)

all_patterns <- GetPatterns(data_obs_NA)
unique_patterns <- as.data.frame(table(all_patterns))

all_patterns_true <- GetPatterns(data_true_NA)
unique_patterns_true <- as.data.frame(table(all_patterns_true))

pattern_list <- Pattern2Data(unique_patterns)
pattern_data <- pattern_list[[1]]
pattern_data <- Data2Array(pattern_data)
freq_vec <- pattern_list[[2]]

pattern_list_true <- Pattern2Data(unique_patterns_true)
pattern_data_true <- pattern_list_true[[1]]
pattern_data_true <- Data2Array(pattern_data_true)
freq_vec_true <- pattern_list_true[[2]]
freq_vec_true[1] <- (freq_vec_true[1] - sum(stayer_vec_true))



init_true <- InitialProbFull(pattern_data_true, freq_vec_true)
tran_true_counts <- createTransitionFullPattern(pattern_data_true, freq_vec_true)
tran_true <- Normalize(tran_true_counts)
tran_true[3,3] <- 1

pi_0_true <- sum(stayer_vec_true)/n

```

```{r}
# init_init <- jitter(init_true, amount = .05 )
# init_init[init_init < 0] <- 0
# init_init <- init_init/sum(init_init)
# 
# tran_init <- jitter(tran_true, amount = .05 )
# tran_init[tran_init < 0] <- 0
# tran_init <- Normalize(tran_init)
# 
# class_init <- jitter(class_true, amount = .05 )
# class_init[class_init < 0] <- 0
# class_init <- Normalize(class_init)




init <- init_true
tran <- tran_true
class <- class_true

pi_0 <- p

old_likelihood <- CalcLikelihoodPattern(pattern_data,init,tran,class,freq_vec, pi_0)
init <- CalcInitialPattern(pattern_data,init,tran,class,freq_vec, pi_0)
tran <- CalcTransitionPattern(pattern_data,init,tran,class,freq_vec, pi_0)
class <- CalcClassificationPattern(pattern_data,init,tran,class, freq_vec, pi_0)
pi_0 <- CalcStayer(pattern_data, init, tran, class,freq_vec,pi_0)
new_likelihood <- CalcLikelihoodPattern(pattern_data,init,tran,class,freq_vec, pi_0)
print(new_likelihood - old_likelihood)

while((new_likelihood - old_likelihood ) > .005){
  old_likelihood <- new_likelihood
  init <- CalcInitialPattern(pattern_data,init,tran,class,freq_vec, pi_0)
  tran <- CalcTransitionPattern(pattern_data,init,tran,class,freq_vec, pi_0)
  class <- CalcClassificationPattern(pattern_data,init,tran,class, freq_vec, pi_0)
  pi_0 <- CalcStayer(pattern_data, init, tran, class,freq_vec,pi_0)
  new_likelihood <- CalcLikelihoodPattern(pattern_data,init,tran,class,freq_vec, pi_0)
  print(new_likelihood - old_likelihood)
}
```























